! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.2+fortran
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! Flibcpp project, https://github.com/swig-fortran/flibcpp
! Copyright (c) 2019-2020 Oak Ridge National Laboratory, UT-Battelle, LLC.
! Distributed under an MIT open source license: see LICENSE for details.

MODULE ModLib_FLC_Random
 USE, INTRINSIC :: ISO_C_BINDING
 USE ModLib_FLC
 IMPLICIT NONE
 PRIVATE

 ! DECLARATION CONSTRUCTS

 INTEGER, PARAMETER :: swig_cmem_own_bit = 0
 INTEGER, PARAMETER :: swig_cmem_rvalue_bit = 1
 TYPE, BIND(C) :: SwigClassWrapper
  TYPE(C_PTR), PUBLIC :: cptr = C_NULL_PTR
  INTEGER(C_INT), PUBLIC :: cmemflags = 0
 END TYPE
 ! class std::mt19937
 TYPE, PUBLIC :: MersenneEngine4
  TYPE(SwigClassWrapper), PUBLIC :: swigdata
 CONTAINS
  PROCEDURE :: seed => swigf_MersenneEngine4_seed
  PROCEDURE :: discard => swigf_MersenneEngine4_discard
  PROCEDURE :: next => swigf_MersenneEngine4_next
  PROCEDURE :: release => swigf_MersenneEngine4_release
  PROCEDURE, PRIVATE :: swigf_MersenneEngine4_op_assign__
  GENERIC :: ASSIGNMENT(=) => swigf_MersenneEngine4_op_assign__
 END TYPE MersenneEngine4
 ! class std::mt19937_64
 TYPE, PUBLIC :: MersenneEngine8
  TYPE(SwigClassWrapper), PUBLIC :: swigdata
 CONTAINS
  PROCEDURE :: seed => swigf_MersenneEngine8_seed
  PROCEDURE :: discard => swigf_MersenneEngine8_discard
  PROCEDURE :: next => swigf_MersenneEngine8_next
  PROCEDURE :: release => swigf_MersenneEngine8_release
  PROCEDURE, PRIVATE :: swigf_MersenneEngine8_op_assign__
  GENERIC :: ASSIGNMENT(=) => swigf_MersenneEngine8_op_assign__
 END TYPE MersenneEngine8
 TYPE, BIND(C) :: SwigArrayWrapper
  TYPE(C_PTR), PUBLIC :: DATA = C_NULL_PTR
  INTEGER(C_SIZE_T), PUBLIC :: SIZE = 0
 END TYPE
 PUBLIC :: uniform_real_distribution
 PUBLIC :: normal_distribution
 INTERFACE MersenneEngine8
  MODULE PROCEDURE swigf_new_MersenneEngine8__SWIG_0, swigf_new_MersenneEngine8__SWIG_1
 END INTERFACE
 INTERFACE uniform_int_distribution
  MODULE PROCEDURE swigf_uniform_int_distribution__SWIG_1, swigf_uniform_int_distribution__SWIG_2
 END INTERFACE
 PUBLIC :: uniform_int_distribution
 INTERFACE discrete_distribution
  MODULE PROCEDURE swigf_discrete_distribution__SWIG_1, swigf_discrete_distribution__SWIG_2
 END INTERFACE
 PUBLIC :: discrete_distribution
 INTERFACE MersenneEngine4
  MODULE PROCEDURE swigf_new_MersenneEngine4__SWIG_0, swigf_new_MersenneEngine4__SWIG_1
 END INTERFACE

! WRAPPER DECLARATIONS
INTERFACE
FUNCTION swigc_new_MersenneEngine4__SWIG_0() &
BIND(C, name="_wrap_new_MersenneEngine4__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_MersenneEngine4__SWIG_1(farg1) &
BIND(C, name="_wrap_new_MersenneEngine4__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
INTEGER(C_INT32_T), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_MersenneEngine4_seed(farg1, farg2) &
BIND(C, name="_wrap_MersenneEngine4_seed")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT32_T), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_MersenneEngine4_discard(farg1, farg2) &
BIND(C, name="_wrap_MersenneEngine4_discard")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG_LONG), INTENT(IN) :: farg2
END SUBROUTINE

FUNCTION swigc_MersenneEngine4_next(farg1) &
BIND(C, name="_wrap_MersenneEngine4_next") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT32_T) :: fresult
END FUNCTION

SUBROUTINE swigc_delete_MersenneEngine4(farg1) &
BIND(C, name="_wrap_delete_MersenneEngine4")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
END SUBROUTINE

SUBROUTINE swigc_MersenneEngine4_op_assign__(farg1, farg2) &
BIND(C, name="_wrap_MersenneEngine4_op_assign__")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

FUNCTION swigc_new_MersenneEngine8__SWIG_0() &
BIND(C, name="_wrap_new_MersenneEngine8__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_MersenneEngine8__SWIG_1(farg1) &
BIND(C, name="_wrap_new_MersenneEngine8__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
INTEGER(C_INT64_T), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_MersenneEngine8_seed(farg1, farg2) &
BIND(C, name="_wrap_MersenneEngine8_seed")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT64_T), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_MersenneEngine8_discard(farg1, farg2) &
BIND(C, name="_wrap_MersenneEngine8_discard")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG_LONG), INTENT(IN) :: farg2
END SUBROUTINE

FUNCTION swigc_MersenneEngine8_next(farg1) &
BIND(C, name="_wrap_MersenneEngine8_next") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT64_T) :: fresult
END FUNCTION

SUBROUTINE swigc_delete_MersenneEngine8(farg1) &
BIND(C, name="_wrap_delete_MersenneEngine8")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
END SUBROUTINE

SUBROUTINE swigc_MersenneEngine8_op_assign__(farg1, farg2) &
BIND(C, name="_wrap_MersenneEngine8_op_assign__")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_uniform_int_distribution__SWIG_1(farg1, farg2, farg3, farg4) &
BIND(C, name="_wrap_uniform_int_distribution__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
INTEGER(C_INT32_T), INTENT(IN) :: farg1
INTEGER(C_INT32_T), INTENT(IN) :: farg2
TYPE(SwigClassWrapper), INTENT(IN) :: farg3
TYPE(SwigArrayWrapper) :: farg4
END SUBROUTINE

SUBROUTINE swigc_uniform_int_distribution__SWIG_2(farg1, farg2, farg3, farg4) &
BIND(C, name="_wrap_uniform_int_distribution__SWIG_2")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
INTEGER(C_INT64_T), INTENT(IN) :: farg1
INTEGER(C_INT64_T), INTENT(IN) :: farg2
TYPE(SwigClassWrapper), INTENT(IN) :: farg3
TYPE(SwigArrayWrapper) :: farg4
END SUBROUTINE

SUBROUTINE swigc_uniform_real_distribution(farg1, farg2, farg3, farg4) &
BIND(C, name="_wrap_uniform_real_distribution")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
REAL(C_DOUBLE), INTENT(IN) :: farg1
REAL(C_DOUBLE), INTENT(IN) :: farg2
TYPE(SwigClassWrapper), INTENT(IN) :: farg3
TYPE(SwigArrayWrapper) :: farg4
END SUBROUTINE

SUBROUTINE swigc_normal_distribution(farg1, farg2, farg3, farg4) &
BIND(C, name="_wrap_normal_distribution")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
REAL(C_DOUBLE), INTENT(IN) :: farg1
REAL(C_DOUBLE), INTENT(IN) :: farg2
TYPE(SwigClassWrapper), INTENT(IN) :: farg3
TYPE(SwigArrayWrapper) :: farg4
END SUBROUTINE

SUBROUTINE swigc_discrete_distribution__SWIG_1(farg1, farg3, farg4) &
BIND(C, name="_wrap_discrete_distribution__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
IMPORT :: swigclasswrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg3
TYPE(SwigArrayWrapper) :: farg4
END SUBROUTINE

SUBROUTINE swigc_discrete_distribution__SWIG_2(farg1, farg3, farg4) &
BIND(C, name="_wrap_discrete_distribution__SWIG_2")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
IMPORT :: swigclasswrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg3
TYPE(SwigArrayWrapper) :: farg4
END SUBROUTINE

END INTERFACE


CONTAINS
 ! MODULE SUBPROGRAMS
FUNCTION swigf_new_MersenneEngine4__SWIG_0() &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(MersenneEngine4) :: self
TYPE(SwigClassWrapper) :: fresult

fresult = swigc_new_MersenneEngine4__SWIG_0()
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_MersenneEngine4__SWIG_1(seed_value) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(MersenneEngine4) :: self
INTEGER(C_INT32_T), INTENT(IN) :: seed_value
TYPE(SwigClassWrapper) :: fresult
INTEGER(C_INT32_T) :: farg1

farg1 = seed_value
fresult = swigc_new_MersenneEngine4__SWIG_1(farg1)
self%swigdata = fresult
END FUNCTION

SUBROUTINE swigf_MersenneEngine4_seed(self, seed_value)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MersenneEngine4), INTENT(IN) :: self
INTEGER(C_INT32_T), INTENT(IN) :: seed_value
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_INT32_T) :: farg2

farg1 = self%swigdata
farg2 = seed_value
CALL swigc_MersenneEngine4_seed(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_MersenneEngine4_discard(self, COUNT)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MersenneEngine4), INTENT(IN) :: self
INTEGER(C_LONG_LONG), INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG_LONG) :: farg2

farg1 = self%swigdata
farg2 = COUNT
CALL swigc_MersenneEngine4_discard(farg1, farg2)
END SUBROUTINE

FUNCTION swigf_MersenneEngine4_next(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T) :: swig_result
CLASS(MersenneEngine4), INTENT(IN) :: self
INTEGER(C_INT32_T) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_MersenneEngine4_next(farg1)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_MersenneEngine4_release(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MersenneEngine4), INTENT(INOUT) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
IF (BTEST(farg1%cmemflags, swig_cmem_own_bit)) THEN
CALL swigc_delete_MersenneEngine4(farg1)
END IF
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE swigf_MersenneEngine4_op_assign__(self, other)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MersenneEngine4), INTENT(INOUT) :: self
TYPE(MersenneEngine4), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
CALL swigc_MersenneEngine4_op_assign__(farg1, farg2)
self%swigdata = farg1
END SUBROUTINE

FUNCTION swigf_new_MersenneEngine8__SWIG_0() &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(MersenneEngine8) :: self
TYPE(SwigClassWrapper) :: fresult

fresult = swigc_new_MersenneEngine8__SWIG_0()
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_MersenneEngine8__SWIG_1(seed_value) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(MersenneEngine8) :: self
INTEGER(C_INT64_T), INTENT(IN) :: seed_value
TYPE(SwigClassWrapper) :: fresult
INTEGER(C_INT64_T) :: farg1

farg1 = seed_value
fresult = swigc_new_MersenneEngine8__SWIG_1(farg1)
self%swigdata = fresult
END FUNCTION

SUBROUTINE swigf_MersenneEngine8_seed(self, seed_value)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MersenneEngine8), INTENT(IN) :: self
INTEGER(C_INT64_T), INTENT(IN) :: seed_value
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_INT64_T) :: farg2

farg1 = self%swigdata
farg2 = seed_value
CALL swigc_MersenneEngine8_seed(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_MersenneEngine8_discard(self, COUNT)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MersenneEngine8), INTENT(IN) :: self
INTEGER(C_LONG_LONG), INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG_LONG) :: farg2

farg1 = self%swigdata
farg2 = COUNT
CALL swigc_MersenneEngine8_discard(farg1, farg2)
END SUBROUTINE

FUNCTION swigf_MersenneEngine8_next(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T) :: swig_result
CLASS(MersenneEngine8), INTENT(IN) :: self
INTEGER(C_INT64_T) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_MersenneEngine8_next(farg1)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_MersenneEngine8_release(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MersenneEngine8), INTENT(INOUT) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
IF (BTEST(farg1%cmemflags, swig_cmem_own_bit)) THEN
CALL swigc_delete_MersenneEngine8(farg1)
END IF
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE swigf_MersenneEngine8_op_assign__(self, other)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MersenneEngine8), INTENT(INOUT) :: self
TYPE(MersenneEngine8), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
CALL swigc_MersenneEngine8_op_assign__(farg1, farg2)
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE SWIGTM_fin_int32_t_Sb__SB_(finp, iminp)
  USE, INTRINSIC :: ISO_C_BINDING
  INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  INTEGER(C_SIZE_T) :: sz
  INTEGER(C_INT32_T), POINTER :: imtemp

  sz = SIZE(finp, KIND=C_SIZE_T)
  IF (sz > 0_c_size_t) THEN
    imtemp => finp(1)
    iminp%DATA = c_loc(imtemp)
  ELSE
    iminp%DATA = c_null_ptr
  END IF
  iminp%SIZE = sz
END SUBROUTINE
SUBROUTINE swigf_uniform_int_distribution__SWIG_1(left, right, engine, DATA)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), INTENT(IN) :: left
INTEGER(C_INT32_T), INTENT(IN) :: right
CLASS(MersenneEngine4), INTENT(IN) :: engine
INTEGER(C_INT32_T), DIMENSION(:), TARGET :: DATA
INTEGER(C_INT32_T) :: farg1
INTEGER(C_INT32_T) :: farg2
TYPE(SwigClassWrapper) :: farg3
TYPE(SwigArrayWrapper) :: farg4

farg1 = left
farg2 = right
farg3 = engine%swigdata
CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg4)
CALL swigc_uniform_int_distribution__SWIG_1(farg1, farg2, farg3, farg4)
END SUBROUTINE

SUBROUTINE SWIGTM_fin_int64_t_Sb__SB_(finp, iminp)
  USE, INTRINSIC :: ISO_C_BINDING
  INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  INTEGER(C_SIZE_T) :: sz
  INTEGER(C_INT64_T), POINTER :: imtemp

  sz = SIZE(finp, KIND=C_SIZE_T)
  IF (sz > 0_c_size_t) THEN
    imtemp => finp(1)
    iminp%DATA = c_loc(imtemp)
  ELSE
    iminp%DATA = c_null_ptr
  END IF
  iminp%SIZE = sz
END SUBROUTINE
SUBROUTINE swigf_uniform_int_distribution__SWIG_2(left, right, engine, DATA)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), INTENT(IN) :: left
INTEGER(C_INT64_T), INTENT(IN) :: right
CLASS(MersenneEngine4), INTENT(IN) :: engine
INTEGER(C_INT64_T), DIMENSION(:), TARGET :: DATA
INTEGER(C_INT64_T) :: farg1
INTEGER(C_INT64_T) :: farg2
TYPE(SwigClassWrapper) :: farg3
TYPE(SwigArrayWrapper) :: farg4

farg1 = left
farg2 = right
farg3 = engine%swigdata
CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg4)
CALL swigc_uniform_int_distribution__SWIG_2(farg1, farg2, farg3, farg4)
END SUBROUTINE

SUBROUTINE SWIGTM_fin_double_Sb__SB_(finp, iminp)
  USE, INTRINSIC :: ISO_C_BINDING
  REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  INTEGER(C_SIZE_T) :: sz
  REAL(C_DOUBLE), POINTER :: imtemp

  sz = SIZE(finp, KIND=C_SIZE_T)
  IF (sz > 0_c_size_t) THEN
    imtemp => finp(1)
    iminp%DATA = c_loc(imtemp)
  ELSE
    iminp%DATA = c_null_ptr
  END IF
  iminp%SIZE = sz
END SUBROUTINE
SUBROUTINE uniform_real_distribution(left, right, engine, DATA)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), INTENT(IN) :: left
REAL(C_DOUBLE), INTENT(IN) :: right
CLASS(MersenneEngine4), INTENT(IN) :: engine
REAL(C_DOUBLE), DIMENSION(:), TARGET :: DATA
REAL(C_DOUBLE) :: farg1
REAL(C_DOUBLE) :: farg2
TYPE(SwigClassWrapper) :: farg3
TYPE(SwigArrayWrapper) :: farg4

farg1 = left
farg2 = right
farg3 = engine%swigdata
CALL SWIGTM_fin_double_Sb__SB_(DATA, farg4)
CALL swigc_uniform_real_distribution(farg1, farg2, farg3, farg4)
END SUBROUTINE

SUBROUTINE normal_distribution(mean, stddev, engine, DATA)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), INTENT(IN) :: mean
REAL(C_DOUBLE), INTENT(IN) :: stddev
CLASS(MersenneEngine4), INTENT(IN) :: engine
REAL(C_DOUBLE), DIMENSION(:), TARGET :: DATA
REAL(C_DOUBLE) :: farg1
REAL(C_DOUBLE) :: farg2
TYPE(SwigClassWrapper) :: farg3
TYPE(SwigArrayWrapper) :: farg4

farg1 = mean
farg2 = stddev
farg3 = engine%swigdata
CALL SWIGTM_fin_double_Sb__SB_(DATA, farg4)
CALL swigc_normal_distribution(farg1, farg2, farg3, farg4)
END SUBROUTINE

SUBROUTINE swigf_discrete_distribution__SWIG_1(weights, engine, DATA)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: weights
CLASS(MersenneEngine4), INTENT(IN) :: engine
INTEGER(C_INT32_T), DIMENSION(:), TARGET :: DATA
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg3
TYPE(SwigArrayWrapper) :: farg4

CALL SWIGTM_fin_double_Sb__SB_(weights, farg1)
farg3 = engine%swigdata
CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg4)
CALL swigc_discrete_distribution__SWIG_1(farg1, farg3, farg4)
END SUBROUTINE

SUBROUTINE swigf_discrete_distribution__SWIG_2(weights, engine, DATA)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: weights
CLASS(MersenneEngine4), INTENT(IN) :: engine
INTEGER(C_INT64_T), DIMENSION(:), TARGET :: DATA
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg3
TYPE(SwigArrayWrapper) :: farg4

CALL SWIGTM_fin_double_Sb__SB_(weights, farg1)
farg3 = engine%swigdata
CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg4)
CALL swigc_discrete_distribution__SWIG_2(farg1, farg3, farg4)
END SUBROUTINE


END MODULE
