! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.2+fortran
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! Flibcpp project, https://github.com/swig-fortran/flibcpp
! Copyright (c) 2019-2020 Oak Ridge National Laboratory, UT-Battelle, LLC.
! Distributed under an MIT open source license: see LICENSE for details.

MODULE ModLib_FLC_Map
 USE, INTRINSIC :: ISO_C_BINDING
 USE ModLib_FLC
 USE ModLib_FLC_String
 IMPLICIT NONE
 PRIVATE

 ! DECLARATION CONSTRUCTS

 INTEGER, PARAMETER :: swig_cmem_own_bit = 0
 INTEGER, PARAMETER :: swig_cmem_rvalue_bit = 1
 TYPE, BIND(C) :: SwigClassWrapper
  TYPE(C_PTR), PUBLIC :: cptr = C_NULL_PTR
  INTEGER(C_INT), PUBLIC :: cmemflags = 0
 END TYPE
 ! class std::map< int,int >
 TYPE, PUBLIC :: MapIntInt
  TYPE(SwigClassWrapper), PUBLIC :: swigdata
 CONTAINS
  PROCEDURE :: empty => swigf_MapIntInt_empty
  PROCEDURE :: SIZE => swigf_MapIntInt_size
  PROCEDURE :: clear => swigf_MapIntInt_clear
  PROCEDURE :: erase => swigf_MapIntInt_erase
  PROCEDURE :: COUNT => swigf_MapIntInt_count
  PROCEDURE :: insert => swigf_MapIntInt_insert
  PROCEDURE :: get => swigf_MapIntInt_get
  PROCEDURE :: set => swigf_MapIntInt_set
  PROCEDURE :: release => swigf_MapIntInt_release
  PROCEDURE, PRIVATE :: swigf_MapIntInt_op_assign__
  GENERIC :: ASSIGNMENT(=) => swigf_MapIntInt_op_assign__
 END TYPE MapIntInt
 TYPE, BIND(C) :: SwigArrayWrapper
  TYPE(C_PTR), PUBLIC :: DATA = C_NULL_PTR
  INTEGER(C_SIZE_T), PUBLIC :: SIZE = 0
 END TYPE
 ! class std::map< std::string,int >
 TYPE, PUBLIC :: MapStringInt
  TYPE(SwigClassWrapper), PUBLIC :: swigdata
 CONTAINS
  PROCEDURE :: empty => swigf_MapStringInt_empty
  PROCEDURE :: SIZE => swigf_MapStringInt_size
  PROCEDURE :: clear => swigf_MapStringInt_clear
  PROCEDURE :: erase => swigf_MapStringInt_erase
  PROCEDURE :: COUNT => swigf_MapStringInt_count
  PROCEDURE :: insert => swigf_MapStringInt_insert
  PROCEDURE :: get => swigf_MapStringInt_get
  PROCEDURE :: set => swigf_MapStringInt_set
  PROCEDURE :: release => swigf_MapStringInt_release
  PROCEDURE, PRIVATE :: swigf_MapStringInt_op_assign__
  GENERIC :: ASSIGNMENT(=) => swigf_MapStringInt_op_assign__
 END TYPE MapStringInt
 ! class std::map< std::string,std::string >
 TYPE, PUBLIC :: MapStringString
  TYPE(SwigClassWrapper), PUBLIC :: swigdata
 CONTAINS
  PROCEDURE :: empty => swigf_MapStringString_empty
  PROCEDURE :: SIZE => swigf_MapStringString_size
  PROCEDURE :: clear => swigf_MapStringString_clear
  PROCEDURE :: erase => swigf_MapStringString_erase
  PROCEDURE :: COUNT => swigf_MapStringString_count
  PROCEDURE :: insert => swigf_MapStringString_insert
  PROCEDURE :: get => swigf_MapStringString_get
  PROCEDURE :: set => swigf_MapStringString_set
  PROCEDURE :: release => swigf_MapStringString_release
  PROCEDURE, PRIVATE :: swigf_MapStringString_op_assign__
  GENERIC :: ASSIGNMENT(=) => swigf_MapStringString_op_assign__
 END TYPE MapStringString
 INTERFACE MapIntInt
  MODULE PROCEDURE swigf_new_MapIntInt
 END INTERFACE
 INTERFACE MapStringInt
  MODULE PROCEDURE swigf_new_MapStringInt
 END INTERFACE
 INTERFACE MapStringString
  MODULE PROCEDURE swigf_new_MapStringString
 END INTERFACE

! WRAPPER DECLARATIONS
INTERFACE
FUNCTION swigc_new_MapIntInt() &
BIND(C, name="_wrap_new_MapIntInt") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_MapIntInt_empty(farg1) &
BIND(C, name="_wrap_MapIntInt_empty") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_MapIntInt_size(farg1) &
BIND(C, name="_wrap_MapIntInt_size") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

SUBROUTINE swigc_MapIntInt_clear(farg1) &
BIND(C, name="_wrap_MapIntInt_clear")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

FUNCTION swigc_MapIntInt_erase(farg1, farg2) &
BIND(C, name="_wrap_MapIntInt_erase") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT), INTENT(IN) :: farg2
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_MapIntInt_count(farg1, farg2) &
BIND(C, name="_wrap_MapIntInt_count") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT), INTENT(IN) :: farg2
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_MapIntInt_insert(farg1, farg2, farg3) &
BIND(C, name="_wrap_MapIntInt_insert") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT), INTENT(IN) :: farg2
INTEGER(C_INT), INTENT(IN) :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_MapIntInt_get(farg1, farg2) &
BIND(C, name="_wrap_MapIntInt_get") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT), INTENT(IN) :: farg2
INTEGER(C_INT) :: fresult
END FUNCTION

SUBROUTINE swigc_MapIntInt_set(farg1, farg2, farg3) &
BIND(C, name="_wrap_MapIntInt_set")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT), INTENT(IN) :: farg2
INTEGER(C_INT), INTENT(IN) :: farg3
END SUBROUTINE

SUBROUTINE swigc_delete_MapIntInt(farg1) &
BIND(C, name="_wrap_delete_MapIntInt")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
END SUBROUTINE

SUBROUTINE swigc_MapIntInt_op_assign__(farg1, farg2) &
BIND(C, name="_wrap_MapIntInt_op_assign__")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

FUNCTION swigc_new_MapStringInt() &
BIND(C, name="_wrap_new_MapStringInt") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_MapStringInt_empty(farg1) &
BIND(C, name="_wrap_MapStringInt_empty") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_MapStringInt_size(farg1) &
BIND(C, name="_wrap_MapStringInt_size") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

SUBROUTINE swigc_MapStringInt_clear(farg1) &
BIND(C, name="_wrap_MapStringInt_clear")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

FUNCTION swigc_MapStringInt_erase(farg1, farg2) &
BIND(C, name="_wrap_MapStringInt_erase") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_MapStringInt_count(farg1, farg2) &
BIND(C, name="_wrap_MapStringInt_count") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_MapStringInt_insert(farg1, farg2, farg3) &
BIND(C, name="_wrap_MapStringInt_insert") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_INT), INTENT(IN) :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_MapStringInt_get(farg1, farg2) &
BIND(C, name="_wrap_MapStringInt_get") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_INT) :: fresult
END FUNCTION

SUBROUTINE swigc_MapStringInt_set(farg1, farg2, farg3) &
BIND(C, name="_wrap_MapStringInt_set")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_INT), INTENT(IN) :: farg3
END SUBROUTINE

SUBROUTINE swigc_delete_MapStringInt(farg1) &
BIND(C, name="_wrap_delete_MapStringInt")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
END SUBROUTINE

SUBROUTINE swigc_MapStringInt_op_assign__(farg1, farg2) &
BIND(C, name="_wrap_MapStringInt_op_assign__")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

FUNCTION swigc_new_MapStringString() &
BIND(C, name="_wrap_new_MapStringString") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_MapStringString_empty(farg1) &
BIND(C, name="_wrap_MapStringString_empty") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_MapStringString_size(farg1) &
BIND(C, name="_wrap_MapStringString_size") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

SUBROUTINE swigc_MapStringString_clear(farg1) &
BIND(C, name="_wrap_MapStringString_clear")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

FUNCTION swigc_MapStringString_erase(farg1, farg2) &
BIND(C, name="_wrap_MapStringString_erase") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_MapStringString_count(farg1, farg2) &
BIND(C, name="_wrap_MapStringString_count") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_MapStringString_insert(farg1, farg2, farg3) &
BIND(C, name="_wrap_MapStringString_insert") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
TYPE(SwigArrayWrapper) :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

 SUBROUTINE SWIG_free(cptr) &
  BIND(C, name="free")
 USE, INTRINSIC :: ISO_C_BINDING
 TYPE(C_PTR), VALUE :: cptr
END SUBROUTINE
FUNCTION swigc_MapStringString_get(farg1, farg2) &
BIND(C, name="_wrap_MapStringString_get") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
TYPE(SwigArrayWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_MapStringString_set(farg1, farg2, farg3) &
BIND(C, name="_wrap_MapStringString_set")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
TYPE(SwigArrayWrapper) :: farg3
END SUBROUTINE

SUBROUTINE swigc_delete_MapStringString(farg1) &
BIND(C, name="_wrap_delete_MapStringString")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
END SUBROUTINE

SUBROUTINE swigc_MapStringString_op_assign__(farg1, farg2) &
BIND(C, name="_wrap_MapStringString_op_assign__")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

END INTERFACE


CONTAINS
 ! MODULE SUBPROGRAMS
FUNCTION swigf_new_MapIntInt() &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(MapIntInt) :: self
TYPE(SwigClassWrapper) :: fresult

fresult = swigc_new_MapIntInt()
self%swigdata = fresult
END FUNCTION


SUBROUTINE SWIGTM_fout_bool(imout, fout)
  USE, INTRINSIC :: ISO_C_BINDING
  INTEGER(KIND=C_INT), INTENT(IN) :: imout
  LOGICAL, INTENT(OUT) :: fout
  fout = (imout /= 0)
END SUBROUTINE

FUNCTION swigf_MapIntInt_empty(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
CLASS(MapIntInt), INTENT(IN) :: self
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_MapIntInt_empty(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_MapIntInt_size(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(MapIntInt), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_MapIntInt_size(farg1)
swig_result = INT(fresult)
END FUNCTION

SUBROUTINE swigf_MapIntInt_clear(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapIntInt), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_MapIntInt_clear(farg1)
END SUBROUTINE

SUBROUTINE swigf_MapIntInt_erase(self, x, swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapIntInt), INTENT(IN) :: self
INTEGER(C_INT), INTENT(IN) :: x
INTEGER, INTENT(OUT), OPTIONAL :: swig_result
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_INT) :: farg2

farg1 = self%swigdata
farg2 = x
fresult = swigc_MapIntInt_erase(farg1, farg2)
IF (PRESENT(swig_result)) THEN
swig_result = INT(fresult)
END IF

END SUBROUTINE

FUNCTION swigf_MapIntInt_count(self, x) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(MapIntInt), INTENT(IN) :: self
INTEGER(C_INT), INTENT(IN) :: x
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_INT) :: farg2

farg1 = self%swigdata
farg2 = x
fresult = swigc_MapIntInt_count(farg1, farg2)
swig_result = INT(fresult)
END FUNCTION

SUBROUTINE swigf_MapIntInt_insert(self, k, v, swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapIntInt), INTENT(IN) :: self
INTEGER(C_INT), INTENT(IN) :: k
INTEGER(C_INT), INTENT(IN) :: v
LOGICAL, INTENT(OUT), OPTIONAL :: swig_result
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_INT) :: farg2
INTEGER(C_INT) :: farg3

farg1 = self%swigdata
farg2 = k
farg3 = v
fresult = swigc_MapIntInt_insert(farg1, farg2, farg3)
IF (PRESENT(swig_result)) THEN
CALL SWIGTM_fout_bool(fresult, swig_result)
END IF

END SUBROUTINE

FUNCTION swigf_MapIntInt_get(self, k) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT) :: swig_result
CLASS(MapIntInt), INTENT(IN) :: self
INTEGER(C_INT), INTENT(IN) :: k
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_INT) :: farg2

farg1 = self%swigdata
farg2 = k
fresult = swigc_MapIntInt_get(farg1, farg2)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_MapIntInt_set(self, k, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapIntInt), INTENT(IN) :: self
INTEGER(C_INT), INTENT(IN) :: k
INTEGER(C_INT), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_INT) :: farg2
INTEGER(C_INT) :: farg3

farg1 = self%swigdata
farg2 = k
farg3 = v
CALL swigc_MapIntInt_set(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_MapIntInt_release(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapIntInt), INTENT(INOUT) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
IF (BTEST(farg1%cmemflags, swig_cmem_own_bit)) THEN
CALL swigc_delete_MapIntInt(farg1)
END IF
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE swigf_MapIntInt_op_assign__(self, other)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapIntInt), INTENT(INOUT) :: self
TYPE(MapIntInt), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
CALL swigc_MapIntInt_op_assign__(farg1, farg2)
self%swigdata = farg1
END SUBROUTINE

FUNCTION swigf_new_MapStringInt() &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(MapStringInt) :: self
TYPE(SwigClassWrapper) :: fresult

fresult = swigc_new_MapStringInt()
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_MapStringInt_empty(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
CLASS(MapStringInt), INTENT(IN) :: self
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_MapStringInt_empty(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_MapStringInt_size(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(MapStringInt), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_MapStringInt_size(farg1)
swig_result = INT(fresult)
END FUNCTION

SUBROUTINE swigf_MapStringInt_clear(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapStringInt), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_MapStringInt_clear(farg1)
END SUBROUTINE


SUBROUTINE SWIGTM_fin_char_Sm_(finp, iminp, temp)
  USE, INTRINSIC :: ISO_C_BINDING
  CHARACTER(LEN=*), INTENT(IN) :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  CHARACTER(KIND=C_CHAR), DIMENSION(:), TARGET, ALLOCATABLE, INTENT(OUT) :: temp
  INTEGER :: i

  ALLOCATE(CHARACTER(KIND=C_CHAR) :: temp(LEN(finp) + 1))
  DO i=1,LEN(finp)
    temp(i) = CHAR(ICHAR(finp(i:i)), KIND=C_CHAR)
  END DO
  i = LEN(finp) + 1
  temp(i) = C_NULL_CHAR ! C finp compatibility
  iminp%DATA = c_loc(temp)
  iminp%SIZE = LEN(finp, KIND=C_SIZE_T)
END SUBROUTINE

SUBROUTINE swigf_MapStringInt_erase(self, x, swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapStringInt), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: x
INTEGER, INTENT(OUT), OPTIONAL :: swig_result
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(x, farg2, farg2_temp)
fresult = swigc_MapStringInt_erase(farg1, farg2)
IF (PRESENT(swig_result)) THEN
swig_result = INT(fresult)
END IF

END SUBROUTINE

FUNCTION swigf_MapStringInt_count(self, x) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(MapStringInt), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: x
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(x, farg2, farg2_temp)
fresult = swigc_MapStringInt_count(farg1, farg2)
swig_result = INT(fresult)
END FUNCTION

SUBROUTINE swigf_MapStringInt_insert(self, k, v, swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapStringInt), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: k
INTEGER(C_INT), INTENT(IN) :: v
LOGICAL, INTENT(OUT), OPTIONAL :: swig_result
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_INT) :: farg3

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(k, farg2, farg2_temp)
farg3 = v
fresult = swigc_MapStringInt_insert(farg1, farg2, farg3)
IF (PRESENT(swig_result)) THEN
CALL SWIGTM_fout_bool(fresult, swig_result)
END IF

END SUBROUTINE

FUNCTION swigf_MapStringInt_get(self, k) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT) :: swig_result
CLASS(MapStringInt), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: k
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(k, farg2, farg2_temp)
fresult = swigc_MapStringInt_get(farg1, farg2)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_MapStringInt_set(self, k, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapStringInt), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: k
INTEGER(C_INT), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_INT) :: farg3

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(k, farg2, farg2_temp)
farg3 = v
CALL swigc_MapStringInt_set(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_MapStringInt_release(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapStringInt), INTENT(INOUT) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
IF (BTEST(farg1%cmemflags, swig_cmem_own_bit)) THEN
CALL swigc_delete_MapStringInt(farg1)
END IF
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE swigf_MapStringInt_op_assign__(self, other)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapStringInt), INTENT(INOUT) :: self
TYPE(MapStringInt), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
CALL swigc_MapStringInt_op_assign__(farg1, farg2)
self%swigdata = farg1
END SUBROUTINE

FUNCTION swigf_new_MapStringString() &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(MapStringString) :: self
TYPE(SwigClassWrapper) :: fresult

fresult = swigc_new_MapStringString()
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_MapStringString_empty(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
CLASS(MapStringString), INTENT(IN) :: self
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_MapStringString_empty(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_MapStringString_size(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(MapStringString), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_MapStringString_size(farg1)
swig_result = INT(fresult)
END FUNCTION

SUBROUTINE swigf_MapStringString_clear(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapStringString), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_MapStringString_clear(farg1)
END SUBROUTINE

SUBROUTINE swigf_MapStringString_erase(self, x, swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapStringString), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: x
INTEGER, INTENT(OUT), OPTIONAL :: swig_result
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(x, farg2, farg2_temp)
fresult = swigc_MapStringString_erase(farg1, farg2)
IF (PRESENT(swig_result)) THEN
swig_result = INT(fresult)
END IF

END SUBROUTINE

FUNCTION swigf_MapStringString_count(self, x) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(MapStringString), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: x
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(x, farg2, farg2_temp)
fresult = swigc_MapStringString_count(farg1, farg2)
swig_result = INT(fresult)
END FUNCTION

SUBROUTINE swigf_MapStringString_insert(self, k, v, swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapStringString), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: k
CHARACTER(LEN=*), TARGET :: v
LOGICAL, INTENT(OUT), OPTIONAL :: swig_result
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg3_temp
TYPE(SwigArrayWrapper) :: farg3

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(k, farg2, farg2_temp)
CALL SWIGTM_fin_char_Sm_(v, farg3, farg3_temp)
fresult = swigc_MapStringString_insert(farg1, farg2, farg3)
IF (PRESENT(swig_result)) THEN
CALL SWIGTM_fout_bool(fresult, swig_result)
END IF

END SUBROUTINE


SUBROUTINE SWIGTM_fout_char_Sm_(imout, fout)
  USE, INTRINSIC :: ISO_C_BINDING
  TYPE(SwigArrayWrapper), INTENT(IN) :: imout
  CHARACTER(LEN=:), ALLOCATABLE, INTENT(OUT) :: fout
  CHARACTER(KIND=C_CHAR), DIMENSION(:), POINTER :: chars
  INTEGER(KIND=C_SIZE_T) :: i
  CALL c_f_pointer(imout%DATA, chars, [imout%SIZE])
  ALLOCATE(CHARACTER(LEN=imout%SIZE) :: fout)
  DO i=1, imout%SIZE
    fout(i:i) = CHAR(ICHAR(chars(i)))
  END DO
END SUBROUTINE

FUNCTION swigf_MapStringString_get(self, k) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CHARACTER(LEN=:), ALLOCATABLE :: swig_result
CLASS(MapStringString), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: k
TYPE(SwigArrayWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(k, farg2, farg2_temp)
fresult = swigc_MapStringString_get(farg1, farg2)
CALL SWIGTM_fout_char_Sm_(fresult, swig_result)
CALL SWIG_free(fresult%DATA)
END FUNCTION

SUBROUTINE swigf_MapStringString_set(self, k, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapStringString), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: k
CHARACTER(LEN=*), TARGET :: v
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg3_temp
TYPE(SwigArrayWrapper) :: farg3

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(k, farg2, farg2_temp)
CALL SWIGTM_fin_char_Sm_(v, farg3, farg3_temp)
CALL swigc_MapStringString_set(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_MapStringString_release(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapStringString), INTENT(INOUT) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
IF (BTEST(farg1%cmemflags, swig_cmem_own_bit)) THEN
CALL swigc_delete_MapStringString(farg1)
END IF
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE swigf_MapStringString_op_assign__(self, other)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MapStringString), INTENT(INOUT) :: self
TYPE(MapStringString), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
CALL swigc_MapStringString_op_assign__(farg1, farg2)
self%swigdata = farg1
END SUBROUTINE


END MODULE
