! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.2+fortran
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! Flibcpp project, https://github.com/swig-fortran/flibcpp
! Copyright (c) 2019-2020 Oak Ridge National Laboratory, UT-Battelle, LLC.
! Distributed under an MIT open source license: see LICENSE for details.

MODULE ModLib_FLC_Vector
 USE, INTRINSIC :: ISO_C_BINDING
 USE ModLib_FLC
 USE ModLib_FLC_String
 IMPLICIT NONE
 PRIVATE

 ! DECLARATION CONSTRUCTS

 INTEGER, PARAMETER :: swig_cmem_own_bit = 0
 INTEGER, PARAMETER :: swig_cmem_rvalue_bit = 1
 TYPE, BIND(C) :: SwigClassWrapper
  TYPE(C_PTR), PUBLIC :: cptr = C_NULL_PTR
  INTEGER(C_INT), PUBLIC :: cmemflags = 0
 END TYPE
 TYPE, BIND(C) :: SwigArrayWrapper
  TYPE(C_PTR), PUBLIC :: DATA = C_NULL_PTR
  INTEGER(C_SIZE_T), PUBLIC :: SIZE = 0
 END TYPE
 ! class std::vector< int32_t >
 TYPE, PUBLIC :: VectorInt4
  TYPE(SwigClassWrapper), PUBLIC :: swigdata
 CONTAINS
  PROCEDURE :: SIZE => swigf_VectorInt4_size
  PROCEDURE :: capacity => swigf_VectorInt4_capacity
  PROCEDURE :: empty => swigf_VectorInt4_empty
  PROCEDURE :: front => swigf_VectorInt4_front
  PROCEDURE :: back => swigf_VectorInt4_back
  PROCEDURE :: reserve => swigf_VectorInt4_reserve
  PROCEDURE, PRIVATE :: swigf_VectorInt4_resize__SWIG_0
  PROCEDURE, PRIVATE :: swigf_VectorInt4_resize__SWIG_1
  PROCEDURE :: push_back => swigf_VectorInt4_push_back
  PROCEDURE :: pop_back => swigf_VectorInt4_pop_back
  PROCEDURE :: clear => swigf_VectorInt4_clear
  PROCEDURE :: set => swigf_VectorInt4_set
  PROCEDURE :: get => swigf_VectorInt4_get
  PROCEDURE :: insert => swigf_VectorInt4_insert
  PROCEDURE, PRIVATE :: swigf_VectorInt4_erase__SWIG_0
  PROCEDURE, PRIVATE :: swigf_VectorInt4_erase__SWIG_1
  PROCEDURE :: front_ref => swigf_VectorInt4_front_ref
  PROCEDURE :: back_ref => swigf_VectorInt4_back_ref
  PROCEDURE :: get_ref => swigf_VectorInt4_get_ref
  PROCEDURE :: ASSIGN => swigf_VectorInt4_assign
  PROCEDURE :: view => swigf_VectorInt4_view
  PROCEDURE :: release => swigf_VectorInt4_release
  PROCEDURE, PRIVATE :: swigf_VectorInt4_op_assign__
  GENERIC :: ASSIGNMENT(=) => swigf_VectorInt4_op_assign__
  GENERIC :: resize => swigf_VectorInt4_resize__SWIG_0, swigf_VectorInt4_resize__SWIG_1
  GENERIC :: erase => swigf_VectorInt4_erase__SWIG_0, swigf_VectorInt4_erase__SWIG_1
 END TYPE VectorInt4
 ! class std::vector< int64_t >
 TYPE, PUBLIC :: VectorInt8
  TYPE(SwigClassWrapper), PUBLIC :: swigdata
 CONTAINS
  PROCEDURE :: SIZE => swigf_VectorInt8_size
  PROCEDURE :: capacity => swigf_VectorInt8_capacity
  PROCEDURE :: empty => swigf_VectorInt8_empty
  PROCEDURE :: front => swigf_VectorInt8_front
  PROCEDURE :: back => swigf_VectorInt8_back
  PROCEDURE :: reserve => swigf_VectorInt8_reserve
  PROCEDURE, PRIVATE :: swigf_VectorInt8_resize__SWIG_0
  PROCEDURE, PRIVATE :: swigf_VectorInt8_resize__SWIG_1
  PROCEDURE :: push_back => swigf_VectorInt8_push_back
  PROCEDURE :: pop_back => swigf_VectorInt8_pop_back
  PROCEDURE :: clear => swigf_VectorInt8_clear
  PROCEDURE :: set => swigf_VectorInt8_set
  PROCEDURE :: get => swigf_VectorInt8_get
  PROCEDURE :: insert => swigf_VectorInt8_insert
  PROCEDURE, PRIVATE :: swigf_VectorInt8_erase__SWIG_0
  PROCEDURE, PRIVATE :: swigf_VectorInt8_erase__SWIG_1
  PROCEDURE :: front_ref => swigf_VectorInt8_front_ref
  PROCEDURE :: back_ref => swigf_VectorInt8_back_ref
  PROCEDURE :: get_ref => swigf_VectorInt8_get_ref
  PROCEDURE :: ASSIGN => swigf_VectorInt8_assign
  PROCEDURE :: view => swigf_VectorInt8_view
  PROCEDURE :: release => swigf_VectorInt8_release
  PROCEDURE, PRIVATE :: swigf_VectorInt8_op_assign__
  GENERIC :: ASSIGNMENT(=) => swigf_VectorInt8_op_assign__
  GENERIC :: resize => swigf_VectorInt8_resize__SWIG_0, swigf_VectorInt8_resize__SWIG_1
  GENERIC :: erase => swigf_VectorInt8_erase__SWIG_0, swigf_VectorInt8_erase__SWIG_1
 END TYPE VectorInt8
 ! class std::vector< double >
 TYPE, PUBLIC :: VectorReal8
  TYPE(SwigClassWrapper), PUBLIC :: swigdata
 CONTAINS
  PROCEDURE :: SIZE => swigf_VectorReal8_size
  PROCEDURE :: capacity => swigf_VectorReal8_capacity
  PROCEDURE :: empty => swigf_VectorReal8_empty
  PROCEDURE :: front => swigf_VectorReal8_front
  PROCEDURE :: back => swigf_VectorReal8_back
  PROCEDURE :: reserve => swigf_VectorReal8_reserve
  PROCEDURE, PRIVATE :: swigf_VectorReal8_resize__SWIG_0
  PROCEDURE, PRIVATE :: swigf_VectorReal8_resize__SWIG_1
  PROCEDURE :: push_back => swigf_VectorReal8_push_back
  PROCEDURE :: pop_back => swigf_VectorReal8_pop_back
  PROCEDURE :: clear => swigf_VectorReal8_clear
  PROCEDURE :: set => swigf_VectorReal8_set
  PROCEDURE :: get => swigf_VectorReal8_get
  PROCEDURE :: insert => swigf_VectorReal8_insert
  PROCEDURE, PRIVATE :: swigf_VectorReal8_erase__SWIG_0
  PROCEDURE, PRIVATE :: swigf_VectorReal8_erase__SWIG_1
  PROCEDURE :: front_ref => swigf_VectorReal8_front_ref
  PROCEDURE :: back_ref => swigf_VectorReal8_back_ref
  PROCEDURE :: get_ref => swigf_VectorReal8_get_ref
  PROCEDURE :: ASSIGN => swigf_VectorReal8_assign
  PROCEDURE :: view => swigf_VectorReal8_view
  PROCEDURE :: release => swigf_VectorReal8_release
  PROCEDURE, PRIVATE :: swigf_VectorReal8_op_assign__
  GENERIC :: ASSIGNMENT(=) => swigf_VectorReal8_op_assign__
  GENERIC :: resize => swigf_VectorReal8_resize__SWIG_0, swigf_VectorReal8_resize__SWIG_1
  GENERIC :: erase => swigf_VectorReal8_erase__SWIG_0, swigf_VectorReal8_erase__SWIG_1
 END TYPE VectorReal8
 ! class std::vector< std::complex< double > >
 TYPE, PUBLIC :: VectorComplex8
  TYPE(SwigClassWrapper), PUBLIC :: swigdata
 CONTAINS
  PROCEDURE :: SIZE => swigf_VectorComplex8_size
  PROCEDURE :: capacity => swigf_VectorComplex8_capacity
  PROCEDURE :: empty => swigf_VectorComplex8_empty
  PROCEDURE :: front => swigf_VectorComplex8_front
  PROCEDURE :: back => swigf_VectorComplex8_back
  PROCEDURE :: reserve => swigf_VectorComplex8_reserve
  PROCEDURE, PRIVATE :: swigf_VectorComplex8_resize__SWIG_0
  PROCEDURE, PRIVATE :: swigf_VectorComplex8_resize__SWIG_1
  PROCEDURE :: push_back => swigf_VectorComplex8_push_back
  PROCEDURE :: pop_back => swigf_VectorComplex8_pop_back
  PROCEDURE :: clear => swigf_VectorComplex8_clear
  PROCEDURE :: set => swigf_VectorComplex8_set
  PROCEDURE :: get => swigf_VectorComplex8_get
  PROCEDURE :: insert => swigf_VectorComplex8_insert
  PROCEDURE, PRIVATE :: swigf_VectorComplex8_erase__SWIG_0
  PROCEDURE, PRIVATE :: swigf_VectorComplex8_erase__SWIG_1
  PROCEDURE :: front_ref => swigf_VectorComplex8_front_ref
  PROCEDURE :: back_ref => swigf_VectorComplex8_back_ref
  PROCEDURE :: get_ref => swigf_VectorComplex8_get_ref
  PROCEDURE :: ASSIGN => swigf_VectorComplex8_assign
  PROCEDURE :: view => swigf_VectorComplex8_view
  PROCEDURE :: release => swigf_VectorComplex8_release
  PROCEDURE, PRIVATE :: swigf_VectorComplex8_op_assign__
  GENERIC :: ASSIGNMENT(=) => swigf_VectorComplex8_op_assign__
  GENERIC :: resize => swigf_VectorComplex8_resize__SWIG_0, swigf_VectorComplex8_resize__SWIG_1
  GENERIC :: erase => swigf_VectorComplex8_erase__SWIG_0, swigf_VectorComplex8_erase__SWIG_1
 END TYPE VectorComplex8
 ! class std::vector< std::string >
 TYPE, PUBLIC :: VectorString
  TYPE(SwigClassWrapper), PUBLIC :: swigdata
 CONTAINS
  PROCEDURE :: SIZE => swigf_VectorString_size
  PROCEDURE :: capacity => swigf_VectorString_capacity
  PROCEDURE :: empty => swigf_VectorString_empty
  PROCEDURE :: front => swigf_VectorString_front
  PROCEDURE :: back => swigf_VectorString_back
  PROCEDURE :: reserve => swigf_VectorString_reserve
  PROCEDURE, PRIVATE :: swigf_VectorString_resize__SWIG_0
  PROCEDURE, PRIVATE :: swigf_VectorString_resize__SWIG_1
  PROCEDURE :: push_back => swigf_VectorString_push_back
  PROCEDURE :: pop_back => swigf_VectorString_pop_back
  PROCEDURE :: clear => swigf_VectorString_clear
  PROCEDURE :: set => swigf_VectorString_set
  PROCEDURE :: get => swigf_VectorString_get
  PROCEDURE :: insert => swigf_VectorString_insert
  PROCEDURE, PRIVATE :: swigf_VectorString_erase__SWIG_0
  PROCEDURE, PRIVATE :: swigf_VectorString_erase__SWIG_1
  PROCEDURE :: front_ref => swigf_VectorString_front_ref
  PROCEDURE :: back_ref => swigf_VectorString_back_ref
  PROCEDURE :: get_ref => swigf_VectorString_get_ref
  PROCEDURE :: set_ref => swigf_VectorString_set_ref
  PROCEDURE :: release => swigf_VectorString_release
  PROCEDURE, PRIVATE :: swigf_VectorString_op_assign__
  GENERIC :: ASSIGNMENT(=) => swigf_VectorString_op_assign__
  GENERIC :: resize => swigf_VectorString_resize__SWIG_0, swigf_VectorString_resize__SWIG_1
  GENERIC :: erase => swigf_VectorString_erase__SWIG_0, swigf_VectorString_erase__SWIG_1
 END TYPE VectorString
 INTERFACE VectorInt4
  MODULE PROCEDURE swigf_new_VectorInt4__SWIG_0, swigf_new_VectorInt4__SWIG_1, swigf_new_VectorInt4__SWIG_2, &
    swigf_new_VectorInt4__SWIG_3, swigf_new_VectorInt4__SWIG_4
 END INTERFACE
 INTERFACE VectorComplex8
  MODULE PROCEDURE swigf_new_VectorComplex8__SWIG_0, swigf_new_VectorComplex8__SWIG_1, swigf_new_VectorComplex8__SWIG_2, &
    swigf_new_VectorComplex8__SWIG_3, swigf_new_VectorComplex8__SWIG_4
 END INTERFACE
 INTERFACE VectorString
  MODULE PROCEDURE swigf_new_VectorString__SWIG_0, swigf_new_VectorString__SWIG_1, swigf_new_VectorString__SWIG_2, &
    swigf_new_VectorString__SWIG_3
 END INTERFACE
 INTERFACE VectorInt8
  MODULE PROCEDURE swigf_new_VectorInt8__SWIG_0, swigf_new_VectorInt8__SWIG_1, swigf_new_VectorInt8__SWIG_2, &
    swigf_new_VectorInt8__SWIG_3, swigf_new_VectorInt8__SWIG_4
 END INTERFACE
 INTERFACE VectorReal8
  MODULE PROCEDURE swigf_new_VectorReal8__SWIG_0, swigf_new_VectorReal8__SWIG_1, swigf_new_VectorReal8__SWIG_2, &
    swigf_new_VectorReal8__SWIG_3, swigf_new_VectorReal8__SWIG_4
 END INTERFACE

! WRAPPER DECLARATIONS
INTERFACE
FUNCTION swigc_new_VectorInt4__SWIG_0() &
BIND(C, name="_wrap_new_VectorInt4__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorInt4__SWIG_1(farg1) &
BIND(C, name="_wrap_new_VectorInt4__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorInt4__SWIG_2(farg1) &
BIND(C, name="_wrap_new_VectorInt4__SWIG_2") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
INTEGER(C_LONG), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorInt4__SWIG_3(farg1, farg2) &
BIND(C, name="_wrap_new_VectorInt4__SWIG_3") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
INTEGER(C_LONG), INTENT(IN) :: farg1
INTEGER(C_INT32_T), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt4_size(farg1) &
BIND(C, name="_wrap_VectorInt4_size") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt4_capacity(farg1) &
BIND(C, name="_wrap_VectorInt4_capacity") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt4_empty(farg1) &
BIND(C, name="_wrap_VectorInt4_empty") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt4_front(farg1) &
BIND(C, name="_wrap_VectorInt4_front") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT32_T) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt4_back(farg1) &
BIND(C, name="_wrap_VectorInt4_back") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT32_T) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorInt4_reserve(farg1, farg2) &
BIND(C, name="_wrap_VectorInt4_reserve")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorInt4_resize__SWIG_0(farg1, farg2) &
BIND(C, name="_wrap_VectorInt4_resize__SWIG_0")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorInt4_resize__SWIG_1(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorInt4_resize__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
INTEGER(C_INT32_T), INTENT(IN) :: farg3
END SUBROUTINE

SUBROUTINE swigc_VectorInt4_push_back(farg1, farg2) &
BIND(C, name="_wrap_VectorInt4_push_back")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT32_T), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorInt4_pop_back(farg1) &
BIND(C, name="_wrap_VectorInt4_pop_back")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorInt4_clear(farg1) &
BIND(C, name="_wrap_VectorInt4_clear")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorInt4_set(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorInt4_set")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
INTEGER(C_INT32_T), INTENT(IN) :: farg3
END SUBROUTINE

FUNCTION swigc_VectorInt4_get(farg1, farg2) &
BIND(C, name="_wrap_VectorInt4_get") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
INTEGER(C_INT32_T) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorInt4_insert(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorInt4_insert")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
INTEGER(C_INT32_T), INTENT(IN) :: farg3
END SUBROUTINE

SUBROUTINE swigc_VectorInt4_erase__SWIG_0(farg1, farg2) &
BIND(C, name="_wrap_VectorInt4_erase__SWIG_0")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorInt4_erase__SWIG_1(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorInt4_erase__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
INTEGER(C_LONG), INTENT(IN) :: farg3
END SUBROUTINE

FUNCTION swigc_VectorInt4_front_ref(farg1) &
BIND(C, name="_wrap_VectorInt4_front_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(C_PTR) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt4_back_ref(farg1) &
BIND(C, name="_wrap_VectorInt4_back_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(C_PTR) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt4_get_ref(farg1, farg2) &
BIND(C, name="_wrap_VectorInt4_get_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
TYPE(C_PTR) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorInt4__SWIG_4(farg1) &
BIND(C, name="_wrap_new_VectorInt4__SWIG_4") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorInt4_assign(farg1, farg2) &
BIND(C, name="_wrap_VectorInt4_assign")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
END SUBROUTINE

FUNCTION swigc_VectorInt4_view(farg1) &
BIND(C, name="_wrap_VectorInt4_view") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_delete_VectorInt4(farg1) &
BIND(C, name="_wrap_delete_VectorInt4")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorInt4_op_assign__(farg1, farg2) &
BIND(C, name="_wrap_VectorInt4_op_assign__")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

FUNCTION swigc_new_VectorInt8__SWIG_0() &
BIND(C, name="_wrap_new_VectorInt8__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorInt8__SWIG_1(farg1) &
BIND(C, name="_wrap_new_VectorInt8__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorInt8__SWIG_2(farg1) &
BIND(C, name="_wrap_new_VectorInt8__SWIG_2") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
INTEGER(C_LONG), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorInt8__SWIG_3(farg1, farg2) &
BIND(C, name="_wrap_new_VectorInt8__SWIG_3") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
INTEGER(C_LONG), INTENT(IN) :: farg1
INTEGER(C_INT64_T), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt8_size(farg1) &
BIND(C, name="_wrap_VectorInt8_size") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt8_capacity(farg1) &
BIND(C, name="_wrap_VectorInt8_capacity") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt8_empty(farg1) &
BIND(C, name="_wrap_VectorInt8_empty") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt8_front(farg1) &
BIND(C, name="_wrap_VectorInt8_front") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT64_T) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt8_back(farg1) &
BIND(C, name="_wrap_VectorInt8_back") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT64_T) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorInt8_reserve(farg1, farg2) &
BIND(C, name="_wrap_VectorInt8_reserve")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorInt8_resize__SWIG_0(farg1, farg2) &
BIND(C, name="_wrap_VectorInt8_resize__SWIG_0")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorInt8_resize__SWIG_1(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorInt8_resize__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
INTEGER(C_INT64_T), INTENT(IN) :: farg3
END SUBROUTINE

SUBROUTINE swigc_VectorInt8_push_back(farg1, farg2) &
BIND(C, name="_wrap_VectorInt8_push_back")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT64_T), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorInt8_pop_back(farg1) &
BIND(C, name="_wrap_VectorInt8_pop_back")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorInt8_clear(farg1) &
BIND(C, name="_wrap_VectorInt8_clear")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorInt8_set(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorInt8_set")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
INTEGER(C_INT64_T), INTENT(IN) :: farg3
END SUBROUTINE

FUNCTION swigc_VectorInt8_get(farg1, farg2) &
BIND(C, name="_wrap_VectorInt8_get") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
INTEGER(C_INT64_T) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorInt8_insert(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorInt8_insert")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
INTEGER(C_INT64_T), INTENT(IN) :: farg3
END SUBROUTINE

SUBROUTINE swigc_VectorInt8_erase__SWIG_0(farg1, farg2) &
BIND(C, name="_wrap_VectorInt8_erase__SWIG_0")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorInt8_erase__SWIG_1(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorInt8_erase__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
INTEGER(C_LONG), INTENT(IN) :: farg3
END SUBROUTINE

FUNCTION swigc_VectorInt8_front_ref(farg1) &
BIND(C, name="_wrap_VectorInt8_front_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(C_PTR) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt8_back_ref(farg1) &
BIND(C, name="_wrap_VectorInt8_back_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(C_PTR) :: fresult
END FUNCTION

FUNCTION swigc_VectorInt8_get_ref(farg1, farg2) &
BIND(C, name="_wrap_VectorInt8_get_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
TYPE(C_PTR) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorInt8__SWIG_4(farg1) &
BIND(C, name="_wrap_new_VectorInt8__SWIG_4") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorInt8_assign(farg1, farg2) &
BIND(C, name="_wrap_VectorInt8_assign")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
END SUBROUTINE

FUNCTION swigc_VectorInt8_view(farg1) &
BIND(C, name="_wrap_VectorInt8_view") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_delete_VectorInt8(farg1) &
BIND(C, name="_wrap_delete_VectorInt8")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorInt8_op_assign__(farg1, farg2) &
BIND(C, name="_wrap_VectorInt8_op_assign__")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

FUNCTION swigc_new_VectorReal8__SWIG_0() &
BIND(C, name="_wrap_new_VectorReal8__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorReal8__SWIG_1(farg1) &
BIND(C, name="_wrap_new_VectorReal8__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorReal8__SWIG_2(farg1) &
BIND(C, name="_wrap_new_VectorReal8__SWIG_2") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
INTEGER(C_LONG), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorReal8__SWIG_3(farg1, farg2) &
BIND(C, name="_wrap_new_VectorReal8__SWIG_3") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
INTEGER(C_LONG), INTENT(IN) :: farg1
REAL(C_DOUBLE), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_VectorReal8_size(farg1) &
BIND(C, name="_wrap_VectorReal8_size") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_VectorReal8_capacity(farg1) &
BIND(C, name="_wrap_VectorReal8_capacity") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_VectorReal8_empty(farg1) &
BIND(C, name="_wrap_VectorReal8_empty") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_VectorReal8_front(farg1) &
BIND(C, name="_wrap_VectorReal8_front") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
REAL(C_DOUBLE) :: fresult
END FUNCTION

FUNCTION swigc_VectorReal8_back(farg1) &
BIND(C, name="_wrap_VectorReal8_back") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
REAL(C_DOUBLE) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorReal8_reserve(farg1, farg2) &
BIND(C, name="_wrap_VectorReal8_reserve")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorReal8_resize__SWIG_0(farg1, farg2) &
BIND(C, name="_wrap_VectorReal8_resize__SWIG_0")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorReal8_resize__SWIG_1(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorReal8_resize__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
REAL(C_DOUBLE), INTENT(IN) :: farg3
END SUBROUTINE

SUBROUTINE swigc_VectorReal8_push_back(farg1, farg2) &
BIND(C, name="_wrap_VectorReal8_push_back")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
REAL(C_DOUBLE), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorReal8_pop_back(farg1) &
BIND(C, name="_wrap_VectorReal8_pop_back")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorReal8_clear(farg1) &
BIND(C, name="_wrap_VectorReal8_clear")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorReal8_set(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorReal8_set")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
REAL(C_DOUBLE), INTENT(IN) :: farg3
END SUBROUTINE

FUNCTION swigc_VectorReal8_get(farg1, farg2) &
BIND(C, name="_wrap_VectorReal8_get") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
REAL(C_DOUBLE) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorReal8_insert(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorReal8_insert")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
REAL(C_DOUBLE), INTENT(IN) :: farg3
END SUBROUTINE

SUBROUTINE swigc_VectorReal8_erase__SWIG_0(farg1, farg2) &
BIND(C, name="_wrap_VectorReal8_erase__SWIG_0")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorReal8_erase__SWIG_1(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorReal8_erase__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
INTEGER(C_LONG), INTENT(IN) :: farg3
END SUBROUTINE

FUNCTION swigc_VectorReal8_front_ref(farg1) &
BIND(C, name="_wrap_VectorReal8_front_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(C_PTR) :: fresult
END FUNCTION

FUNCTION swigc_VectorReal8_back_ref(farg1) &
BIND(C, name="_wrap_VectorReal8_back_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(C_PTR) :: fresult
END FUNCTION

FUNCTION swigc_VectorReal8_get_ref(farg1, farg2) &
BIND(C, name="_wrap_VectorReal8_get_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
TYPE(C_PTR) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorReal8__SWIG_4(farg1) &
BIND(C, name="_wrap_new_VectorReal8__SWIG_4") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorReal8_assign(farg1, farg2) &
BIND(C, name="_wrap_VectorReal8_assign")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
END SUBROUTINE

FUNCTION swigc_VectorReal8_view(farg1) &
BIND(C, name="_wrap_VectorReal8_view") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_delete_VectorReal8(farg1) &
BIND(C, name="_wrap_delete_VectorReal8")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorReal8_op_assign__(farg1, farg2) &
BIND(C, name="_wrap_VectorReal8_op_assign__")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

FUNCTION swigc_new_VectorComplex8__SWIG_0() &
BIND(C, name="_wrap_new_VectorComplex8__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorComplex8__SWIG_1(farg1) &
BIND(C, name="_wrap_new_VectorComplex8__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorComplex8__SWIG_2(farg1) &
BIND(C, name="_wrap_new_VectorComplex8__SWIG_2") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
INTEGER(C_LONG), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorComplex8__SWIG_3(farg1, farg2) &
BIND(C, name="_wrap_new_VectorComplex8__SWIG_3") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
INTEGER(C_LONG), INTENT(IN) :: farg1
COMPLEX(C_DOUBLE_COMPLEX), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_VectorComplex8_size(farg1) &
BIND(C, name="_wrap_VectorComplex8_size") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_VectorComplex8_capacity(farg1) &
BIND(C, name="_wrap_VectorComplex8_capacity") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_VectorComplex8_empty(farg1) &
BIND(C, name="_wrap_VectorComplex8_empty") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_VectorComplex8_front(farg1) &
BIND(C, name="_wrap_VectorComplex8_front") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
COMPLEX(C_DOUBLE_COMPLEX) :: fresult
END FUNCTION

FUNCTION swigc_VectorComplex8_back(farg1) &
BIND(C, name="_wrap_VectorComplex8_back") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
COMPLEX(C_DOUBLE_COMPLEX) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorComplex8_reserve(farg1, farg2) &
BIND(C, name="_wrap_VectorComplex8_reserve")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorComplex8_resize__SWIG_0(farg1, farg2) &
BIND(C, name="_wrap_VectorComplex8_resize__SWIG_0")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorComplex8_resize__SWIG_1(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorComplex8_resize__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
COMPLEX(C_DOUBLE_COMPLEX), INTENT(IN) :: farg3
END SUBROUTINE

SUBROUTINE swigc_VectorComplex8_push_back(farg1, farg2) &
BIND(C, name="_wrap_VectorComplex8_push_back")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
COMPLEX(C_DOUBLE_COMPLEX), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorComplex8_pop_back(farg1) &
BIND(C, name="_wrap_VectorComplex8_pop_back")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorComplex8_clear(farg1) &
BIND(C, name="_wrap_VectorComplex8_clear")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorComplex8_set(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorComplex8_set")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
COMPLEX(C_DOUBLE_COMPLEX), INTENT(IN) :: farg3
END SUBROUTINE

FUNCTION swigc_VectorComplex8_get(farg1, farg2) &
BIND(C, name="_wrap_VectorComplex8_get") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
COMPLEX(C_DOUBLE_COMPLEX) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorComplex8_insert(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorComplex8_insert")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
COMPLEX(C_DOUBLE_COMPLEX), INTENT(IN) :: farg3
END SUBROUTINE

SUBROUTINE swigc_VectorComplex8_erase__SWIG_0(farg1, farg2) &
BIND(C, name="_wrap_VectorComplex8_erase__SWIG_0")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorComplex8_erase__SWIG_1(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorComplex8_erase__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
INTEGER(C_LONG), INTENT(IN) :: farg3
END SUBROUTINE

FUNCTION swigc_VectorComplex8_front_ref(farg1) &
BIND(C, name="_wrap_VectorComplex8_front_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(C_PTR) :: fresult
END FUNCTION

FUNCTION swigc_VectorComplex8_back_ref(farg1) &
BIND(C, name="_wrap_VectorComplex8_back_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(C_PTR) :: fresult
END FUNCTION

FUNCTION swigc_VectorComplex8_get_ref(farg1, farg2) &
BIND(C, name="_wrap_VectorComplex8_get_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
TYPE(C_PTR) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorComplex8__SWIG_4(farg1) &
BIND(C, name="_wrap_new_VectorComplex8__SWIG_4") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorComplex8_assign(farg1, farg2) &
BIND(C, name="_wrap_VectorComplex8_assign")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
END SUBROUTINE

FUNCTION swigc_VectorComplex8_view(farg1) &
BIND(C, name="_wrap_VectorComplex8_view") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_delete_VectorComplex8(farg1) &
BIND(C, name="_wrap_delete_VectorComplex8")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorComplex8_op_assign__(farg1, farg2) &
BIND(C, name="_wrap_VectorComplex8_op_assign__")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

FUNCTION swigc_new_VectorString__SWIG_0() &
BIND(C, name="_wrap_new_VectorString__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorString__SWIG_1(farg1) &
BIND(C, name="_wrap_new_VectorString__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorString__SWIG_2(farg1) &
BIND(C, name="_wrap_new_VectorString__SWIG_2") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
INTEGER(C_LONG), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_VectorString__SWIG_3(farg1, farg2) &
BIND(C, name="_wrap_new_VectorString__SWIG_3") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
INTEGER(C_LONG), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_VectorString_size(farg1) &
BIND(C, name="_wrap_VectorString_size") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_VectorString_capacity(farg1) &
BIND(C, name="_wrap_VectorString_capacity") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_VectorString_empty(farg1) &
BIND(C, name="_wrap_VectorString_empty") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

 SUBROUTINE SWIG_free(cptr) &
  BIND(C, name="free")
 USE, INTRINSIC :: ISO_C_BINDING
 TYPE(C_PTR), VALUE :: cptr
END SUBROUTINE
FUNCTION swigc_VectorString_front(farg1) &
BIND(C, name="_wrap_VectorString_front") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: fresult
END FUNCTION

FUNCTION swigc_VectorString_back(farg1) &
BIND(C, name="_wrap_VectorString_back") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorString_reserve(farg1, farg2) &
BIND(C, name="_wrap_VectorString_reserve")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorString_resize__SWIG_0(farg1, farg2) &
BIND(C, name="_wrap_VectorString_resize__SWIG_0")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorString_resize__SWIG_1(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorString_resize__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
TYPE(SwigArrayWrapper) :: farg3
END SUBROUTINE

SUBROUTINE swigc_VectorString_push_back(farg1, farg2) &
BIND(C, name="_wrap_VectorString_push_back")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorString_pop_back(farg1) &
BIND(C, name="_wrap_VectorString_pop_back")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorString_clear(farg1) &
BIND(C, name="_wrap_VectorString_clear")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorString_set(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorString_set")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
TYPE(SwigArrayWrapper) :: farg3
END SUBROUTINE

FUNCTION swigc_VectorString_get(farg1, farg2) &
BIND(C, name="_wrap_VectorString_get") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
TYPE(SwigArrayWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorString_insert(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorString_insert")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
TYPE(SwigArrayWrapper) :: farg3
END SUBROUTINE

SUBROUTINE swigc_VectorString_erase__SWIG_0(farg1, farg2) &
BIND(C, name="_wrap_VectorString_erase__SWIG_0")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_VectorString_erase__SWIG_1(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorString_erase__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
INTEGER(C_LONG), INTENT(IN) :: farg3
END SUBROUTINE

FUNCTION swigc_VectorString_front_ref(farg1) &
BIND(C, name="_wrap_VectorString_front_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_VectorString_back_ref(farg1) &
BIND(C, name="_wrap_VectorString_back_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_VectorString_get_ref(farg1, farg2) &
BIND(C, name="_wrap_VectorString_get_ref") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_VectorString_set_ref(farg1, farg2, farg3) &
BIND(C, name="_wrap_VectorString_set_ref")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
TYPE(SwigClassWrapper), INTENT(IN) :: farg3
END SUBROUTINE

SUBROUTINE swigc_delete_VectorString(farg1) &
BIND(C, name="_wrap_delete_VectorString")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
END SUBROUTINE

SUBROUTINE swigc_VectorString_op_assign__(farg1, farg2) &
BIND(C, name="_wrap_VectorString_op_assign__")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

END INTERFACE


CONTAINS
 ! MODULE SUBPROGRAMS
FUNCTION swigf_new_VectorInt4__SWIG_0() &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorInt4) :: self
TYPE(SwigClassWrapper) :: fresult

fresult = swigc_new_VectorInt4__SWIG_0()
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorInt4__SWIG_1(other) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorInt4) :: self
CLASS(VectorInt4), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = other%swigdata
fresult = swigc_new_VectorInt4__SWIG_1(farg1)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorInt4__SWIG_2(COUNT) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorInt4) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: fresult
INTEGER(C_LONG) :: farg1

farg1 = INT(COUNT, C_INT)
fresult = swigc_new_VectorInt4__SWIG_2(farg1)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorInt4__SWIG_3(COUNT, v) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorInt4) :: self
INTEGER, INTENT(IN) :: COUNT
INTEGER(C_INT32_T), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: fresult
INTEGER(C_LONG) :: farg1
INTEGER(C_INT32_T) :: farg2

farg1 = INT(COUNT, C_INT)
farg2 = v
fresult = swigc_new_VectorInt4__SWIG_3(farg1, farg2)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_VectorInt4_size(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt4_size(farg1)
swig_result = INT(fresult)
END FUNCTION

FUNCTION swigf_VectorInt4_capacity(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt4_capacity(farg1)
swig_result = INT(fresult)
END FUNCTION


SUBROUTINE SWIGTM_fout_bool(imout, fout)
  USE, INTRINSIC :: ISO_C_BINDING
  INTEGER(KIND=C_INT), INTENT(IN) :: imout
  LOGICAL, INTENT(OUT) :: fout
  fout = (imout /= 0)
END SUBROUTINE

FUNCTION swigf_VectorInt4_empty(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt4_empty(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_VectorInt4_front(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T) :: swig_result
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER(C_INT32_T) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt4_front(farg1)
swig_result = fresult
END FUNCTION

FUNCTION swigf_VectorInt4_back(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T) :: swig_result
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER(C_INT32_T) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt4_back(farg1)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_VectorInt4_reserve(self, COUNT)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
CALL swigc_VectorInt4_reserve(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorInt4_resize__SWIG_0(self, COUNT)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
CALL swigc_VectorInt4_resize__SWIG_0(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorInt4_resize__SWIG_1(self, COUNT, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
INTEGER(C_INT32_T), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
INTEGER(C_INT32_T) :: farg3

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
farg3 = v
CALL swigc_VectorInt4_resize__SWIG_1(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_VectorInt4_push_back(self, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER(C_INT32_T), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_INT32_T) :: farg2

farg1 = self%swigdata
farg2 = v
CALL swigc_VectorInt4_push_back(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorInt4_pop_back(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt4), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_VectorInt4_pop_back(farg1)
END SUBROUTINE

SUBROUTINE swigf_VectorInt4_clear(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt4), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_VectorInt4_clear(farg1)
END SUBROUTINE

SUBROUTINE swigf_VectorInt4_set(self, INDEX, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
INTEGER(C_INT32_T), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
INTEGER(C_INT32_T) :: farg3

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
farg3 = v
CALL swigc_VectorInt4_set(farg1, farg2, farg3)
END SUBROUTINE

FUNCTION swigf_VectorInt4_get(self, INDEX) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T) :: swig_result
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
INTEGER(C_INT32_T) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
fresult = swigc_VectorInt4_get(farg1, farg2)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_VectorInt4_insert(self, INDEX, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
INTEGER(C_INT32_T), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
INTEGER(C_INT32_T) :: farg3

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
farg3 = v
CALL swigc_VectorInt4_insert(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_VectorInt4_erase__SWIG_0(self, INDEX)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
CALL swigc_VectorInt4_erase__SWIG_0(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorInt4_erase__SWIG_1(self, start_index, stop_index)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER, INTENT(IN) :: start_index
INTEGER, INTENT(IN) :: stop_index
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
INTEGER(C_LONG) :: farg3

farg1 = self%swigdata
farg2 = INT(start_index, C_INT)
farg3 = INT(stop_index, C_INT)
CALL swigc_VectorInt4_erase__SWIG_1(farg1, farg2, farg3)
END SUBROUTINE

FUNCTION swigf_VectorInt4_front_ref(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), POINTER :: swig_result
CLASS(VectorInt4), INTENT(IN) :: self
TYPE(C_PTR) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt4_front_ref(farg1)
CALL c_f_pointer(fresult, swig_result)
END FUNCTION

FUNCTION swigf_VectorInt4_back_ref(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), POINTER :: swig_result
CLASS(VectorInt4), INTENT(IN) :: self
TYPE(C_PTR) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt4_back_ref(farg1)
CALL c_f_pointer(fresult, swig_result)
END FUNCTION

FUNCTION swigf_VectorInt4_get_ref(self, INDEX) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), POINTER :: swig_result
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
TYPE(C_PTR) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
fresult = swigc_VectorInt4_get_ref(farg1, farg2)
CALL c_f_pointer(fresult, swig_result)
END FUNCTION

SUBROUTINE SWIGTM_fin_int32_t_Sb__SB_(finp, iminp)
  USE, INTRINSIC :: ISO_C_BINDING
  INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  INTEGER(C_SIZE_T) :: sz
  INTEGER(C_INT32_T), POINTER :: imtemp

  sz = SIZE(finp, KIND=C_SIZE_T)
  IF (sz > 0_c_size_t) THEN
    imtemp => finp(1)
    iminp%DATA = c_loc(imtemp)
  ELSE
    iminp%DATA = c_null_ptr
  END IF
  iminp%SIZE = sz
END SUBROUTINE
FUNCTION swigf_new_VectorInt4__SWIG_4(DATA) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorInt4) :: self
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg1)
fresult = swigc_new_VectorInt4__SWIG_4(farg1)
self%swigdata = fresult
END FUNCTION

SUBROUTINE swigf_VectorInt4_assign(self, DATA)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt4), INTENT(IN) :: self
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg2)
CALL swigc_VectorInt4_assign(farg1, farg2)
END SUBROUTINE

SUBROUTINE SWIGTM_fout_int32_t_Sb__SB_(imout, fout)
  USE, INTRINSIC :: ISO_C_BINDING
  TYPE(SwigArrayWrapper), INTENT(IN) :: imout
  INTEGER(C_INT32_T), DIMENSION(:), POINTER, INTENT(OUT) :: fout

  IF (imout%SIZE > 0) THEN
    CALL c_f_pointer(imout%DATA, fout, [imout%SIZE])
  ELSE
    fout => NULL()
  END IF
END SUBROUTINE
FUNCTION swigf_VectorInt4_view(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), DIMENSION(:), POINTER :: swig_result
CLASS(VectorInt4), INTENT(IN) :: self
TYPE(SwigArrayWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt4_view(farg1)
CALL SWIGTM_fout_int32_t_Sb__SB_(fresult, swig_result)
END FUNCTION

SUBROUTINE swigf_VectorInt4_release(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt4), INTENT(INOUT) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
IF (BTEST(farg1%cmemflags, swig_cmem_own_bit)) THEN
CALL swigc_delete_VectorInt4(farg1)
END IF
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE swigf_VectorInt4_op_assign__(self, other)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt4), INTENT(INOUT) :: self
TYPE(VectorInt4), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
CALL swigc_VectorInt4_op_assign__(farg1, farg2)
self%swigdata = farg1
END SUBROUTINE

FUNCTION swigf_new_VectorInt8__SWIG_0() &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorInt8) :: self
TYPE(SwigClassWrapper) :: fresult

fresult = swigc_new_VectorInt8__SWIG_0()
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorInt8__SWIG_1(other) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorInt8) :: self
CLASS(VectorInt8), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = other%swigdata
fresult = swigc_new_VectorInt8__SWIG_1(farg1)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorInt8__SWIG_2(COUNT) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorInt8) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: fresult
INTEGER(C_LONG) :: farg1

farg1 = INT(COUNT, C_INT)
fresult = swigc_new_VectorInt8__SWIG_2(farg1)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorInt8__SWIG_3(COUNT, v) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorInt8) :: self
INTEGER, INTENT(IN) :: COUNT
INTEGER(C_INT64_T), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: fresult
INTEGER(C_LONG) :: farg1
INTEGER(C_INT64_T) :: farg2

farg1 = INT(COUNT, C_INT)
farg2 = v
fresult = swigc_new_VectorInt8__SWIG_3(farg1, farg2)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_VectorInt8_size(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt8_size(farg1)
swig_result = INT(fresult)
END FUNCTION

FUNCTION swigf_VectorInt8_capacity(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt8_capacity(farg1)
swig_result = INT(fresult)
END FUNCTION

FUNCTION swigf_VectorInt8_empty(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt8_empty(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_VectorInt8_front(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T) :: swig_result
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER(C_INT64_T) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt8_front(farg1)
swig_result = fresult
END FUNCTION

FUNCTION swigf_VectorInt8_back(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T) :: swig_result
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER(C_INT64_T) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt8_back(farg1)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_VectorInt8_reserve(self, COUNT)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
CALL swigc_VectorInt8_reserve(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorInt8_resize__SWIG_0(self, COUNT)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
CALL swigc_VectorInt8_resize__SWIG_0(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorInt8_resize__SWIG_1(self, COUNT, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
INTEGER(C_INT64_T), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
INTEGER(C_INT64_T) :: farg3

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
farg3 = v
CALL swigc_VectorInt8_resize__SWIG_1(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_VectorInt8_push_back(self, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER(C_INT64_T), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_INT64_T) :: farg2

farg1 = self%swigdata
farg2 = v
CALL swigc_VectorInt8_push_back(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorInt8_pop_back(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt8), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_VectorInt8_pop_back(farg1)
END SUBROUTINE

SUBROUTINE swigf_VectorInt8_clear(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt8), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_VectorInt8_clear(farg1)
END SUBROUTINE

SUBROUTINE swigf_VectorInt8_set(self, INDEX, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
INTEGER(C_INT64_T), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
INTEGER(C_INT64_T) :: farg3

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
farg3 = v
CALL swigc_VectorInt8_set(farg1, farg2, farg3)
END SUBROUTINE

FUNCTION swigf_VectorInt8_get(self, INDEX) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T) :: swig_result
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
INTEGER(C_INT64_T) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
fresult = swigc_VectorInt8_get(farg1, farg2)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_VectorInt8_insert(self, INDEX, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
INTEGER(C_INT64_T), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
INTEGER(C_INT64_T) :: farg3

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
farg3 = v
CALL swigc_VectorInt8_insert(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_VectorInt8_erase__SWIG_0(self, INDEX)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
CALL swigc_VectorInt8_erase__SWIG_0(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorInt8_erase__SWIG_1(self, start_index, stop_index)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: start_index
INTEGER, INTENT(IN) :: stop_index
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
INTEGER(C_LONG) :: farg3

farg1 = self%swigdata
farg2 = INT(start_index, C_INT)
farg3 = INT(stop_index, C_INT)
CALL swigc_VectorInt8_erase__SWIG_1(farg1, farg2, farg3)
END SUBROUTINE

FUNCTION swigf_VectorInt8_front_ref(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), POINTER :: swig_result
CLASS(VectorInt8), INTENT(IN) :: self
TYPE(C_PTR) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt8_front_ref(farg1)
CALL c_f_pointer(fresult, swig_result)
END FUNCTION

FUNCTION swigf_VectorInt8_back_ref(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), POINTER :: swig_result
CLASS(VectorInt8), INTENT(IN) :: self
TYPE(C_PTR) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt8_back_ref(farg1)
CALL c_f_pointer(fresult, swig_result)
END FUNCTION

FUNCTION swigf_VectorInt8_get_ref(self, INDEX) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), POINTER :: swig_result
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
TYPE(C_PTR) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
fresult = swigc_VectorInt8_get_ref(farg1, farg2)
CALL c_f_pointer(fresult, swig_result)
END FUNCTION

SUBROUTINE SWIGTM_fin_int64_t_Sb__SB_(finp, iminp)
  USE, INTRINSIC :: ISO_C_BINDING
  INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  INTEGER(C_SIZE_T) :: sz
  INTEGER(C_INT64_T), POINTER :: imtemp

  sz = SIZE(finp, KIND=C_SIZE_T)
  IF (sz > 0_c_size_t) THEN
    imtemp => finp(1)
    iminp%DATA = c_loc(imtemp)
  ELSE
    iminp%DATA = c_null_ptr
  END IF
  iminp%SIZE = sz
END SUBROUTINE
FUNCTION swigf_new_VectorInt8__SWIG_4(DATA) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorInt8) :: self
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg1)
fresult = swigc_new_VectorInt8__SWIG_4(farg1)
self%swigdata = fresult
END FUNCTION

SUBROUTINE swigf_VectorInt8_assign(self, DATA)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt8), INTENT(IN) :: self
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg2)
CALL swigc_VectorInt8_assign(farg1, farg2)
END SUBROUTINE

SUBROUTINE SWIGTM_fout_int64_t_Sb__SB_(imout, fout)
  USE, INTRINSIC :: ISO_C_BINDING
  TYPE(SwigArrayWrapper), INTENT(IN) :: imout
  INTEGER(C_INT64_T), DIMENSION(:), POINTER, INTENT(OUT) :: fout

  IF (imout%SIZE > 0) THEN
    CALL c_f_pointer(imout%DATA, fout, [imout%SIZE])
  ELSE
    fout => NULL()
  END IF
END SUBROUTINE
FUNCTION swigf_VectorInt8_view(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), DIMENSION(:), POINTER :: swig_result
CLASS(VectorInt8), INTENT(IN) :: self
TYPE(SwigArrayWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorInt8_view(farg1)
CALL SWIGTM_fout_int64_t_Sb__SB_(fresult, swig_result)
END FUNCTION

SUBROUTINE swigf_VectorInt8_release(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt8), INTENT(INOUT) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
IF (BTEST(farg1%cmemflags, swig_cmem_own_bit)) THEN
CALL swigc_delete_VectorInt8(farg1)
END IF
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE swigf_VectorInt8_op_assign__(self, other)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorInt8), INTENT(INOUT) :: self
TYPE(VectorInt8), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
CALL swigc_VectorInt8_op_assign__(farg1, farg2)
self%swigdata = farg1
END SUBROUTINE

FUNCTION swigf_new_VectorReal8__SWIG_0() &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorReal8) :: self
TYPE(SwigClassWrapper) :: fresult

fresult = swigc_new_VectorReal8__SWIG_0()
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorReal8__SWIG_1(other) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorReal8) :: self
CLASS(VectorReal8), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = other%swigdata
fresult = swigc_new_VectorReal8__SWIG_1(farg1)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorReal8__SWIG_2(COUNT) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorReal8) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: fresult
INTEGER(C_LONG) :: farg1

farg1 = INT(COUNT, C_INT)
fresult = swigc_new_VectorReal8__SWIG_2(farg1)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorReal8__SWIG_3(COUNT, v) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorReal8) :: self
INTEGER, INTENT(IN) :: COUNT
REAL(C_DOUBLE), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: fresult
INTEGER(C_LONG) :: farg1
REAL(C_DOUBLE) :: farg2

farg1 = INT(COUNT, C_INT)
farg2 = v
fresult = swigc_new_VectorReal8__SWIG_3(farg1, farg2)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_VectorReal8_size(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(VectorReal8), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorReal8_size(farg1)
swig_result = INT(fresult)
END FUNCTION

FUNCTION swigf_VectorReal8_capacity(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(VectorReal8), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorReal8_capacity(farg1)
swig_result = INT(fresult)
END FUNCTION

FUNCTION swigf_VectorReal8_empty(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
CLASS(VectorReal8), INTENT(IN) :: self
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorReal8_empty(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_VectorReal8_front(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE) :: swig_result
CLASS(VectorReal8), INTENT(IN) :: self
REAL(C_DOUBLE) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorReal8_front(farg1)
swig_result = fresult
END FUNCTION

FUNCTION swigf_VectorReal8_back(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE) :: swig_result
CLASS(VectorReal8), INTENT(IN) :: self
REAL(C_DOUBLE) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorReal8_back(farg1)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_VectorReal8_reserve(self, COUNT)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorReal8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
CALL swigc_VectorReal8_reserve(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorReal8_resize__SWIG_0(self, COUNT)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorReal8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
CALL swigc_VectorReal8_resize__SWIG_0(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorReal8_resize__SWIG_1(self, COUNT, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorReal8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
REAL(C_DOUBLE), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
REAL(C_DOUBLE) :: farg3

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
farg3 = v
CALL swigc_VectorReal8_resize__SWIG_1(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_VectorReal8_push_back(self, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorReal8), INTENT(IN) :: self
REAL(C_DOUBLE), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
REAL(C_DOUBLE) :: farg2

farg1 = self%swigdata
farg2 = v
CALL swigc_VectorReal8_push_back(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorReal8_pop_back(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorReal8), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_VectorReal8_pop_back(farg1)
END SUBROUTINE

SUBROUTINE swigf_VectorReal8_clear(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorReal8), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_VectorReal8_clear(farg1)
END SUBROUTINE

SUBROUTINE swigf_VectorReal8_set(self, INDEX, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorReal8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
REAL(C_DOUBLE), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
REAL(C_DOUBLE) :: farg3

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
farg3 = v
CALL swigc_VectorReal8_set(farg1, farg2, farg3)
END SUBROUTINE

FUNCTION swigf_VectorReal8_get(self, INDEX) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE) :: swig_result
CLASS(VectorReal8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
REAL(C_DOUBLE) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
fresult = swigc_VectorReal8_get(farg1, farg2)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_VectorReal8_insert(self, INDEX, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorReal8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
REAL(C_DOUBLE), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
REAL(C_DOUBLE) :: farg3

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
farg3 = v
CALL swigc_VectorReal8_insert(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_VectorReal8_erase__SWIG_0(self, INDEX)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorReal8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
CALL swigc_VectorReal8_erase__SWIG_0(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorReal8_erase__SWIG_1(self, start_index, stop_index)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorReal8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: start_index
INTEGER, INTENT(IN) :: stop_index
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
INTEGER(C_LONG) :: farg3

farg1 = self%swigdata
farg2 = INT(start_index, C_INT)
farg3 = INT(stop_index, C_INT)
CALL swigc_VectorReal8_erase__SWIG_1(farg1, farg2, farg3)
END SUBROUTINE

FUNCTION swigf_VectorReal8_front_ref(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), POINTER :: swig_result
CLASS(VectorReal8), INTENT(IN) :: self
TYPE(C_PTR) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorReal8_front_ref(farg1)
CALL c_f_pointer(fresult, swig_result)
END FUNCTION

FUNCTION swigf_VectorReal8_back_ref(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), POINTER :: swig_result
CLASS(VectorReal8), INTENT(IN) :: self
TYPE(C_PTR) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorReal8_back_ref(farg1)
CALL c_f_pointer(fresult, swig_result)
END FUNCTION

FUNCTION swigf_VectorReal8_get_ref(self, INDEX) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), POINTER :: swig_result
CLASS(VectorReal8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
TYPE(C_PTR) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
fresult = swigc_VectorReal8_get_ref(farg1, farg2)
CALL c_f_pointer(fresult, swig_result)
END FUNCTION

SUBROUTINE SWIGTM_fin_double_Sb__SB_(finp, iminp)
  USE, INTRINSIC :: ISO_C_BINDING
  REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  INTEGER(C_SIZE_T) :: sz
  REAL(C_DOUBLE), POINTER :: imtemp

  sz = SIZE(finp, KIND=C_SIZE_T)
  IF (sz > 0_c_size_t) THEN
    imtemp => finp(1)
    iminp%DATA = c_loc(imtemp)
  ELSE
    iminp%DATA = c_null_ptr
  END IF
  iminp%SIZE = sz
END SUBROUTINE
FUNCTION swigf_new_VectorReal8__SWIG_4(DATA) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorReal8) :: self
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: DATA
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_double_Sb__SB_(DATA, farg1)
fresult = swigc_new_VectorReal8__SWIG_4(farg1)
self%swigdata = fresult
END FUNCTION

SUBROUTINE swigf_VectorReal8_assign(self, DATA)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorReal8), INTENT(IN) :: self
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: DATA
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_double_Sb__SB_(DATA, farg2)
CALL swigc_VectorReal8_assign(farg1, farg2)
END SUBROUTINE

SUBROUTINE SWIGTM_fout_double_Sb__SB_(imout, fout)
  USE, INTRINSIC :: ISO_C_BINDING
  TYPE(SwigArrayWrapper), INTENT(IN) :: imout
  REAL(C_DOUBLE), DIMENSION(:), POINTER, INTENT(OUT) :: fout

  IF (imout%SIZE > 0) THEN
    CALL c_f_pointer(imout%DATA, fout, [imout%SIZE])
  ELSE
    fout => NULL()
  END IF
END SUBROUTINE
FUNCTION swigf_VectorReal8_view(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), DIMENSION(:), POINTER :: swig_result
CLASS(VectorReal8), INTENT(IN) :: self
TYPE(SwigArrayWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorReal8_view(farg1)
CALL SWIGTM_fout_double_Sb__SB_(fresult, swig_result)
END FUNCTION

SUBROUTINE swigf_VectorReal8_release(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorReal8), INTENT(INOUT) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
IF (BTEST(farg1%cmemflags, swig_cmem_own_bit)) THEN
CALL swigc_delete_VectorReal8(farg1)
END IF
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE swigf_VectorReal8_op_assign__(self, other)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorReal8), INTENT(INOUT) :: self
TYPE(VectorReal8), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
CALL swigc_VectorReal8_op_assign__(farg1, farg2)
self%swigdata = farg1
END SUBROUTINE

FUNCTION swigf_new_VectorComplex8__SWIG_0() &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorComplex8) :: self
TYPE(SwigClassWrapper) :: fresult

fresult = swigc_new_VectorComplex8__SWIG_0()
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorComplex8__SWIG_1(other) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorComplex8) :: self
CLASS(VectorComplex8), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = other%swigdata
fresult = swigc_new_VectorComplex8__SWIG_1(farg1)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorComplex8__SWIG_2(COUNT) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorComplex8) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: fresult
INTEGER(C_LONG) :: farg1

farg1 = INT(COUNT, C_INT)
fresult = swigc_new_VectorComplex8__SWIG_2(farg1)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorComplex8__SWIG_3(COUNT, v) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorComplex8) :: self
INTEGER, INTENT(IN) :: COUNT
COMPLEX(C_DOUBLE_COMPLEX), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: fresult
INTEGER(C_LONG) :: farg1
COMPLEX(C_DOUBLE_COMPLEX) :: farg2

farg1 = INT(COUNT, C_INT)
farg2 = v
fresult = swigc_new_VectorComplex8__SWIG_3(farg1, farg2)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_VectorComplex8_size(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(VectorComplex8), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorComplex8_size(farg1)
swig_result = INT(fresult)
END FUNCTION

FUNCTION swigf_VectorComplex8_capacity(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(VectorComplex8), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorComplex8_capacity(farg1)
swig_result = INT(fresult)
END FUNCTION

FUNCTION swigf_VectorComplex8_empty(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
CLASS(VectorComplex8), INTENT(IN) :: self
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorComplex8_empty(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_VectorComplex8_front(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
COMPLEX(C_DOUBLE_COMPLEX) :: swig_result
CLASS(VectorComplex8), INTENT(IN) :: self
COMPLEX(C_DOUBLE_COMPLEX) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorComplex8_front(farg1)
swig_result = fresult
END FUNCTION

FUNCTION swigf_VectorComplex8_back(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
COMPLEX(C_DOUBLE_COMPLEX) :: swig_result
CLASS(VectorComplex8), INTENT(IN) :: self
COMPLEX(C_DOUBLE_COMPLEX) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorComplex8_back(farg1)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_VectorComplex8_reserve(self, COUNT)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorComplex8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
CALL swigc_VectorComplex8_reserve(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorComplex8_resize__SWIG_0(self, COUNT)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorComplex8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
CALL swigc_VectorComplex8_resize__SWIG_0(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorComplex8_resize__SWIG_1(self, COUNT, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorComplex8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
COMPLEX(C_DOUBLE_COMPLEX), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
COMPLEX(C_DOUBLE_COMPLEX) :: farg3

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
farg3 = v
CALL swigc_VectorComplex8_resize__SWIG_1(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_VectorComplex8_push_back(self, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorComplex8), INTENT(IN) :: self
COMPLEX(C_DOUBLE_COMPLEX), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
COMPLEX(C_DOUBLE_COMPLEX) :: farg2

farg1 = self%swigdata
farg2 = v
CALL swigc_VectorComplex8_push_back(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorComplex8_pop_back(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorComplex8), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_VectorComplex8_pop_back(farg1)
END SUBROUTINE

SUBROUTINE swigf_VectorComplex8_clear(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorComplex8), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_VectorComplex8_clear(farg1)
END SUBROUTINE

SUBROUTINE swigf_VectorComplex8_set(self, INDEX, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorComplex8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
COMPLEX(C_DOUBLE_COMPLEX), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
COMPLEX(C_DOUBLE_COMPLEX) :: farg3

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
farg3 = v
CALL swigc_VectorComplex8_set(farg1, farg2, farg3)
END SUBROUTINE

FUNCTION swigf_VectorComplex8_get(self, INDEX) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
COMPLEX(C_DOUBLE_COMPLEX) :: swig_result
CLASS(VectorComplex8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
COMPLEX(C_DOUBLE_COMPLEX) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
fresult = swigc_VectorComplex8_get(farg1, farg2)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_VectorComplex8_insert(self, INDEX, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorComplex8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
COMPLEX(C_DOUBLE_COMPLEX), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
COMPLEX(C_DOUBLE_COMPLEX) :: farg3

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
farg3 = v
CALL swigc_VectorComplex8_insert(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_VectorComplex8_erase__SWIG_0(self, INDEX)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorComplex8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
CALL swigc_VectorComplex8_erase__SWIG_0(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorComplex8_erase__SWIG_1(self, start_index, stop_index)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorComplex8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: start_index
INTEGER, INTENT(IN) :: stop_index
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
INTEGER(C_LONG) :: farg3

farg1 = self%swigdata
farg2 = INT(start_index, C_INT)
farg3 = INT(stop_index, C_INT)
CALL swigc_VectorComplex8_erase__SWIG_1(farg1, farg2, farg3)
END SUBROUTINE

FUNCTION swigf_VectorComplex8_front_ref(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
COMPLEX(C_DOUBLE_COMPLEX), POINTER :: swig_result
CLASS(VectorComplex8), INTENT(IN) :: self
TYPE(C_PTR) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorComplex8_front_ref(farg1)
CALL c_f_pointer(fresult, swig_result)
END FUNCTION

FUNCTION swigf_VectorComplex8_back_ref(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
COMPLEX(C_DOUBLE_COMPLEX), POINTER :: swig_result
CLASS(VectorComplex8), INTENT(IN) :: self
TYPE(C_PTR) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorComplex8_back_ref(farg1)
CALL c_f_pointer(fresult, swig_result)
END FUNCTION

FUNCTION swigf_VectorComplex8_get_ref(self, INDEX) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
COMPLEX(C_DOUBLE_COMPLEX), POINTER :: swig_result
CLASS(VectorComplex8), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
TYPE(C_PTR) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
fresult = swigc_VectorComplex8_get_ref(farg1, farg2)
CALL c_f_pointer(fresult, swig_result)
END FUNCTION

SUBROUTINE SWIGTM_fin_SwigComplex_double_Sb__SB_(finp, iminp)
  USE, INTRINSIC :: ISO_C_BINDING
  COMPLEX(C_DOUBLE_COMPLEX), DIMENSION(:), INTENT(IN), TARGET :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  INTEGER(C_SIZE_T) :: sz
  COMPLEX(C_DOUBLE_COMPLEX), POINTER :: imtemp

  sz = SIZE(finp, KIND=C_SIZE_T)
  IF (sz > 0_c_size_t) THEN
    imtemp => finp(1)
    iminp%DATA = c_loc(imtemp)
  ELSE
    iminp%DATA = c_null_ptr
  END IF
  iminp%SIZE = sz
END SUBROUTINE
FUNCTION swigf_new_VectorComplex8__SWIG_4(DATA) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorComplex8) :: self
COMPLEX(C_DOUBLE_COMPLEX), DIMENSION(:), INTENT(IN), TARGET :: DATA
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_SwigComplex_double_Sb__SB_(DATA, farg1)
fresult = swigc_new_VectorComplex8__SWIG_4(farg1)
self%swigdata = fresult
END FUNCTION

SUBROUTINE swigf_VectorComplex8_assign(self, DATA)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorComplex8), INTENT(IN) :: self
COMPLEX(C_DOUBLE_COMPLEX), DIMENSION(:), INTENT(IN), TARGET :: DATA
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_SwigComplex_double_Sb__SB_(DATA, farg2)
CALL swigc_VectorComplex8_assign(farg1, farg2)
END SUBROUTINE

SUBROUTINE SWIGTM_fout_SwigComplex_double_Sb__SB_(imout, fout)
  USE, INTRINSIC :: ISO_C_BINDING
  TYPE(SwigArrayWrapper), INTENT(IN) :: imout
  COMPLEX(C_DOUBLE_COMPLEX), DIMENSION(:), POINTER, INTENT(OUT) :: fout

  IF (imout%SIZE > 0) THEN
    CALL c_f_pointer(imout%DATA, fout, [imout%SIZE])
  ELSE
    fout => NULL()
  END IF
END SUBROUTINE
FUNCTION swigf_VectorComplex8_view(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
COMPLEX(C_DOUBLE_COMPLEX), DIMENSION(:), POINTER :: swig_result
CLASS(VectorComplex8), INTENT(IN) :: self
TYPE(SwigArrayWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorComplex8_view(farg1)
CALL SWIGTM_fout_SwigComplex_double_Sb__SB_(fresult, swig_result)
END FUNCTION

SUBROUTINE swigf_VectorComplex8_release(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorComplex8), INTENT(INOUT) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
IF (BTEST(farg1%cmemflags, swig_cmem_own_bit)) THEN
CALL swigc_delete_VectorComplex8(farg1)
END IF
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE swigf_VectorComplex8_op_assign__(self, other)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorComplex8), INTENT(INOUT) :: self
TYPE(VectorComplex8), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
CALL swigc_VectorComplex8_op_assign__(farg1, farg2)
self%swigdata = farg1
END SUBROUTINE

FUNCTION swigf_new_VectorString__SWIG_0() &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorString) :: self
TYPE(SwigClassWrapper) :: fresult

fresult = swigc_new_VectorString__SWIG_0()
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorString__SWIG_1(other) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorString) :: self
CLASS(VectorString), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = other%swigdata
fresult = swigc_new_VectorString__SWIG_1(farg1)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_VectorString__SWIG_2(COUNT) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorString) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: fresult
INTEGER(C_LONG) :: farg1

farg1 = INT(COUNT, C_INT)
fresult = swigc_new_VectorString__SWIG_2(farg1)
self%swigdata = fresult
END FUNCTION


SUBROUTINE SWIGTM_fin_char_Sm_(finp, iminp, temp)
  USE, INTRINSIC :: ISO_C_BINDING
  CHARACTER(LEN=*), INTENT(IN) :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  CHARACTER(KIND=C_CHAR), DIMENSION(:), TARGET, ALLOCATABLE, INTENT(OUT) :: temp
  INTEGER :: i

  ALLOCATE(CHARACTER(KIND=C_CHAR) :: temp(LEN(finp) + 1))
  DO i=1,LEN(finp)
    temp(i) = CHAR(ICHAR(finp(i:i)), KIND=C_CHAR)
  END DO
  i = LEN(finp) + 1
  temp(i) = C_NULL_CHAR ! C finp compatibility
  iminp%DATA = c_loc(temp)
  iminp%SIZE = LEN(finp, KIND=C_SIZE_T)
END SUBROUTINE

FUNCTION swigf_new_VectorString__SWIG_3(COUNT, v) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(VectorString) :: self
INTEGER, INTENT(IN) :: COUNT
CHARACTER(LEN=*), TARGET :: v
TYPE(SwigClassWrapper) :: fresult
INTEGER(C_LONG) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = INT(COUNT, C_INT)
CALL SWIGTM_fin_char_Sm_(v, farg2, farg2_temp)
fresult = swigc_new_VectorString__SWIG_3(farg1, farg2)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_VectorString_size(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(VectorString), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorString_size(farg1)
swig_result = INT(fresult)
END FUNCTION

FUNCTION swigf_VectorString_capacity(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(VectorString), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorString_capacity(farg1)
swig_result = INT(fresult)
END FUNCTION

FUNCTION swigf_VectorString_empty(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
CLASS(VectorString), INTENT(IN) :: self
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorString_empty(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION


SUBROUTINE SWIGTM_fout_char_Sm_(imout, fout)
  USE, INTRINSIC :: ISO_C_BINDING
  TYPE(SwigArrayWrapper), INTENT(IN) :: imout
  CHARACTER(LEN=:), ALLOCATABLE, INTENT(OUT) :: fout
  CHARACTER(KIND=C_CHAR), DIMENSION(:), POINTER :: chars
  INTEGER(KIND=C_SIZE_T) :: i
  CALL c_f_pointer(imout%DATA, chars, [imout%SIZE])
  ALLOCATE(CHARACTER(LEN=imout%SIZE) :: fout)
  DO i=1, imout%SIZE
    fout(i:i) = CHAR(ICHAR(chars(i)))
  END DO
END SUBROUTINE

FUNCTION swigf_VectorString_front(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CHARACTER(LEN=:), ALLOCATABLE :: swig_result
CLASS(VectorString), INTENT(IN) :: self
TYPE(SwigArrayWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorString_front(farg1)
CALL SWIGTM_fout_char_Sm_(fresult, swig_result)
CALL SWIG_free(fresult%DATA)
END FUNCTION

FUNCTION swigf_VectorString_back(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CHARACTER(LEN=:), ALLOCATABLE :: swig_result
CLASS(VectorString), INTENT(IN) :: self
TYPE(SwigArrayWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorString_back(farg1)
CALL SWIGTM_fout_char_Sm_(fresult, swig_result)
CALL SWIG_free(fresult%DATA)
END FUNCTION

SUBROUTINE swigf_VectorString_reserve(self, COUNT)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorString), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
CALL swigc_VectorString_reserve(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorString_resize__SWIG_0(self, COUNT)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorString), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
CALL swigc_VectorString_resize__SWIG_0(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorString_resize__SWIG_1(self, COUNT, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorString), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
CHARACTER(LEN=*), TARGET :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg3_temp
TYPE(SwigArrayWrapper) :: farg3

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
CALL SWIGTM_fin_char_Sm_(v, farg3, farg3_temp)
CALL swigc_VectorString_resize__SWIG_1(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_VectorString_push_back(self, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorString), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: v
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(v, farg2, farg2_temp)
CALL swigc_VectorString_push_back(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorString_pop_back(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorString), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_VectorString_pop_back(farg1)
END SUBROUTINE

SUBROUTINE swigf_VectorString_clear(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorString), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_VectorString_clear(farg1)
END SUBROUTINE

SUBROUTINE swigf_VectorString_set(self, INDEX, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorString), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
CHARACTER(LEN=*), TARGET :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg3_temp
TYPE(SwigArrayWrapper) :: farg3

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
CALL SWIGTM_fin_char_Sm_(v, farg3, farg3_temp)
CALL swigc_VectorString_set(farg1, farg2, farg3)
END SUBROUTINE

FUNCTION swigf_VectorString_get(self, INDEX) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CHARACTER(LEN=:), ALLOCATABLE :: swig_result
CLASS(VectorString), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
TYPE(SwigArrayWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
fresult = swigc_VectorString_get(farg1, farg2)
CALL SWIGTM_fout_char_Sm_(fresult, swig_result)
CALL SWIG_free(fresult%DATA)
END FUNCTION

SUBROUTINE swigf_VectorString_insert(self, INDEX, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorString), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
CHARACTER(LEN=*), TARGET :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg3_temp
TYPE(SwigArrayWrapper) :: farg3

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
CALL SWIGTM_fin_char_Sm_(v, farg3, farg3_temp)
CALL swigc_VectorString_insert(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_VectorString_erase__SWIG_0(self, INDEX)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorString), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
CALL swigc_VectorString_erase__SWIG_0(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_VectorString_erase__SWIG_1(self, start_index, stop_index)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorString), INTENT(IN) :: self
INTEGER, INTENT(IN) :: start_index
INTEGER, INTENT(IN) :: stop_index
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
INTEGER(C_LONG) :: farg3

farg1 = self%swigdata
farg2 = INT(start_index, C_INT)
farg3 = INT(stop_index, C_INT)
CALL swigc_VectorString_erase__SWIG_1(farg1, farg2, farg3)
END SUBROUTINE

FUNCTION swigf_VectorString_front_ref(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(string) :: swig_result
CLASS(VectorString), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorString_front_ref(farg1)
swig_result%swigdata = fresult
END FUNCTION

FUNCTION swigf_VectorString_back_ref(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(string) :: swig_result
CLASS(VectorString), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_VectorString_back_ref(farg1)
swig_result%swigdata = fresult
END FUNCTION

FUNCTION swigf_VectorString_get_ref(self, INDEX) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(string) :: swig_result
CLASS(VectorString), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
fresult = swigc_VectorString_get_ref(farg1, farg2)
swig_result%swigdata = fresult
END FUNCTION

SUBROUTINE swigf_VectorString_set_ref(self, INDEX, VALUE)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorString), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
CLASS(string), INTENT(IN) :: VALUE
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
TYPE(SwigClassWrapper) :: farg3

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
farg3 = VALUE%swigdata
CALL swigc_VectorString_set_ref(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_VectorString_release(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorString), INTENT(INOUT) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
IF (BTEST(farg1%cmemflags, swig_cmem_own_bit)) THEN
CALL swigc_delete_VectorString(farg1)
END IF
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE swigf_VectorString_op_assign__(self, other)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(VectorString), INTENT(INOUT) :: self
TYPE(VectorString), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
CALL swigc_VectorString_op_assign__(farg1, farg2)
self%swigdata = farg1
END SUBROUTINE


END MODULE
