! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.2+fortran
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! Flibcpp project, https://github.com/swig-fortran/flibcpp
! Copyright (c) 2019-2020 Oak Ridge National Laboratory, UT-Battelle, LLC.
! Distributed under an MIT open source license: see LICENSE for details.

MODULE ModLib_FLC_Algorithm
 USE, INTRINSIC :: ISO_C_BINDING
 USE ModLib_FLC
 USE ModLib_FLC_Random
 IMPLICIT NONE
 PRIVATE

 ! DECLARATION CONSTRUCTS
INTEGER, PARAMETER, PUBLIC :: INDEX_INT = C_INT

 PUBLIC :: flc_cmp_int4
 PUBLIC :: flc_cmp_int8
 PUBLIC :: flc_cmp_real8
 PUBLIC :: flc_cmp_index
 PUBLIC :: flc_cmp_ptr
 TYPE, BIND(C) :: SwigArrayWrapper
  TYPE(C_PTR), PUBLIC :: DATA = C_NULL_PTR
  INTEGER(C_SIZE_T), PUBLIC :: SIZE = 0
 END TYPE

 INTEGER, PARAMETER :: swig_cmem_own_bit = 0
 INTEGER, PARAMETER :: swig_cmem_rvalue_bit = 1
 TYPE, BIND(C) :: SwigClassWrapper
  TYPE(C_PTR), PUBLIC :: cptr = C_NULL_PTR
  INTEGER(C_INT), PUBLIC :: cmemflags = 0
 END TYPE
 INTERFACE binary_search
  MODULE PROCEDURE swigf_binary_search__SWIG_1, swigf_binary_search__SWIG_2, swigf_binary_search__SWIG_3, &
    swigf_binary_search__SWIG_4, swigf_binary_search__SWIG_5, swigf_binary_search__SWIG_6, swigf_binary_search__SWIG_7
 END INTERFACE
 PUBLIC :: binary_search
 INTERFACE minmax_element
  MODULE PROCEDURE swigf_minmax_element__SWIG_1, swigf_minmax_element__SWIG_2, swigf_minmax_element__SWIG_3, &
    swigf_minmax_element__SWIG_4, swigf_minmax_element__SWIG_5, swigf_minmax_element__SWIG_6, swigf_minmax_element__SWIG_7
 END INTERFACE
 PUBLIC :: minmax_element
 INTERFACE shuffle
  MODULE PROCEDURE swigf_shuffle__SWIG_1, swigf_shuffle__SWIG_2, swigf_shuffle__SWIG_3, swigf_shuffle__SWIG_4
 END INTERFACE
 PUBLIC :: shuffle
 INTERFACE includes
  MODULE PROCEDURE swigf_includes__SWIG_1, swigf_includes__SWIG_2, swigf_includes__SWIG_3, swigf_includes__SWIG_4, &
    swigf_includes__SWIG_5, swigf_includes__SWIG_6, swigf_includes__SWIG_7
 END INTERFACE
 PUBLIC :: includes
 INTERFACE is_sorted
  MODULE PROCEDURE swigf_is_sorted__SWIG_1, swigf_is_sorted__SWIG_2, swigf_is_sorted__SWIG_3, swigf_is_sorted__SWIG_4, &
    swigf_is_sorted__SWIG_5, swigf_is_sorted__SWIG_6, swigf_is_sorted__SWIG_7
 END INTERFACE
 PUBLIC :: is_sorted
 INTERFACE equal_range
  MODULE PROCEDURE swigf_equal_range__SWIG_1, swigf_equal_range__SWIG_2, swigf_equal_range__SWIG_3, swigf_equal_range__SWIG_4, &
    swigf_equal_range__SWIG_5, swigf_equal_range__SWIG_6, swigf_equal_range__SWIG_7
 END INTERFACE
 PUBLIC :: equal_range
 INTERFACE sort
  MODULE PROCEDURE swigf_sort__SWIG_1, swigf_sort__SWIG_2, swigf_sort__SWIG_3, swigf_sort__SWIG_4, swigf_sort__SWIG_5, &
    swigf_sort__SWIG_6, swigf_sort__SWIG_7
 END INTERFACE
 PUBLIC :: sort
 INTERFACE argsort
  MODULE PROCEDURE swigf_argsort__SWIG_1, swigf_argsort__SWIG_2, swigf_argsort__SWIG_3, swigf_argsort__SWIG_4, &
    swigf_argsort__SWIG_5, swigf_argsort__SWIG_6, swigf_argsort__SWIG_7
 END INTERFACE
 PUBLIC :: argsort

! FUNCTION POINTER DECLARATIONS
abstract INTERFACE
FUNCTION flc_cmp_int4(left, right) &
BIND(C) &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), INTENT(IN), VALUE :: left
INTEGER(C_INT32_T), INTENT(IN), VALUE :: right
LOGICAL(C_BOOL) :: fresult
END FUNCTION

FUNCTION flc_cmp_int8(left, right) &
BIND(C) &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), INTENT(IN), VALUE :: left
INTEGER(C_INT64_T), INTENT(IN), VALUE :: right
LOGICAL(C_BOOL) :: fresult
END FUNCTION

FUNCTION flc_cmp_real8(left, right) &
BIND(C) &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), INTENT(IN), VALUE :: left
REAL(C_DOUBLE), INTENT(IN), VALUE :: right
LOGICAL(C_BOOL) :: fresult
END FUNCTION

FUNCTION flc_cmp_index(left, right) &
BIND(C) &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT), INTENT(IN), VALUE :: left
INTEGER(C_INT), INTENT(IN), VALUE :: right
LOGICAL(C_BOOL) :: fresult
END FUNCTION

FUNCTION flc_cmp_ptr(left, right) &
BIND(C) &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(C_PTR), INTENT(IN), VALUE :: left
TYPE(C_PTR), INTENT(IN), VALUE :: right
LOGICAL(C_BOOL) :: fresult
END FUNCTION

END INTERFACE


! WRAPPER DECLARATIONS
INTERFACE
SUBROUTINE swigc_sort__SWIG_1(farg1) &
BIND(C, name="_wrap_sort__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
END SUBROUTINE

SUBROUTINE swigc_sort__SWIG_2(farg1) &
BIND(C, name="_wrap_sort__SWIG_2")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
END SUBROUTINE

SUBROUTINE swigc_sort__SWIG_3(farg1) &
BIND(C, name="_wrap_sort__SWIG_3")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
END SUBROUTINE

SUBROUTINE swigc_sort__SWIG_4(farg1, farg3) &
BIND(C, name="_wrap_sort__SWIG_4")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR), VALUE :: farg3
END SUBROUTINE

SUBROUTINE swigc_sort__SWIG_5(farg1, farg3) &
BIND(C, name="_wrap_sort__SWIG_5")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR), VALUE :: farg3
END SUBROUTINE

SUBROUTINE swigc_sort__SWIG_6(farg1, farg3) &
BIND(C, name="_wrap_sort__SWIG_6")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR), VALUE :: farg3
END SUBROUTINE

SUBROUTINE swigc_sort__SWIG_7(farg1, farg3) &
BIND(C, name="_wrap_sort__SWIG_7")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR), VALUE :: farg3
END SUBROUTINE

FUNCTION swigc_is_sorted__SWIG_1(farg1) &
BIND(C, name="_wrap_is_sorted__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_is_sorted__SWIG_2(farg1) &
BIND(C, name="_wrap_is_sorted__SWIG_2") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_is_sorted__SWIG_3(farg1) &
BIND(C, name="_wrap_is_sorted__SWIG_3") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_is_sorted__SWIG_4(farg1, farg3) &
BIND(C, name="_wrap_is_sorted__SWIG_4") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR), VALUE :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_is_sorted__SWIG_5(farg1, farg3) &
BIND(C, name="_wrap_is_sorted__SWIG_5") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR), VALUE :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_is_sorted__SWIG_6(farg1, farg3) &
BIND(C, name="_wrap_is_sorted__SWIG_6") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR), VALUE :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_is_sorted__SWIG_7(farg1, farg3) &
BIND(C, name="_wrap_is_sorted__SWIG_7") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR), VALUE :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

SUBROUTINE swigc_argsort__SWIG_1(farg1, farg3) &
BIND(C, name="_wrap_argsort__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
END SUBROUTINE

SUBROUTINE swigc_argsort__SWIG_2(farg1, farg3) &
BIND(C, name="_wrap_argsort__SWIG_2")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
END SUBROUTINE

SUBROUTINE swigc_argsort__SWIG_3(farg1, farg3) &
BIND(C, name="_wrap_argsort__SWIG_3")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
END SUBROUTINE

SUBROUTINE swigc_argsort__SWIG_4(farg1, farg3, farg5) &
BIND(C, name="_wrap_argsort__SWIG_4")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR), VALUE :: farg5
END SUBROUTINE

SUBROUTINE swigc_argsort__SWIG_5(farg1, farg3, farg5) &
BIND(C, name="_wrap_argsort__SWIG_5")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR), VALUE :: farg5
END SUBROUTINE

SUBROUTINE swigc_argsort__SWIG_6(farg1, farg3, farg5) &
BIND(C, name="_wrap_argsort__SWIG_6")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR), VALUE :: farg5
END SUBROUTINE

SUBROUTINE swigc_argsort__SWIG_7(farg1, farg3, farg5) &
BIND(C, name="_wrap_argsort__SWIG_7")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR), VALUE :: farg5
END SUBROUTINE

FUNCTION swigc_binary_search__SWIG_1(farg1, farg3) &
BIND(C, name="_wrap_binary_search__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT32_T), INTENT(IN) :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_binary_search__SWIG_2(farg1, farg3) &
BIND(C, name="_wrap_binary_search__SWIG_2") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT64_T), INTENT(IN) :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_binary_search__SWIG_3(farg1, farg3) &
BIND(C, name="_wrap_binary_search__SWIG_3") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
REAL(C_DOUBLE), INTENT(IN) :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_binary_search__SWIG_4(farg1, farg3, farg4) &
BIND(C, name="_wrap_binary_search__SWIG_4") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT32_T), INTENT(IN) :: farg3
TYPE(C_FUNPTR), VALUE :: farg4
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_binary_search__SWIG_5(farg1, farg3, farg4) &
BIND(C, name="_wrap_binary_search__SWIG_5") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT64_T), INTENT(IN) :: farg3
TYPE(C_FUNPTR), VALUE :: farg4
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_binary_search__SWIG_6(farg1, farg3, farg4) &
BIND(C, name="_wrap_binary_search__SWIG_6") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
REAL(C_DOUBLE), INTENT(IN) :: farg3
TYPE(C_FUNPTR), VALUE :: farg4
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_binary_search__SWIG_7(farg1, farg3, farg4) &
BIND(C, name="_wrap_binary_search__SWIG_7") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR), INTENT(IN) :: farg3
TYPE(C_FUNPTR), VALUE :: farg4
INTEGER(C_INT) :: fresult
END FUNCTION

SUBROUTINE swigc_equal_range__SWIG_1(farg1, farg3, farg4, farg5) &
BIND(C, name="_wrap_equal_range__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT32_T), INTENT(IN) :: farg3
TYPE(C_PTR), VALUE :: farg4
TYPE(C_PTR), VALUE :: farg5
END SUBROUTINE

SUBROUTINE swigc_equal_range__SWIG_2(farg1, farg3, farg4, farg5) &
BIND(C, name="_wrap_equal_range__SWIG_2")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT64_T), INTENT(IN) :: farg3
TYPE(C_PTR), VALUE :: farg4
TYPE(C_PTR), VALUE :: farg5
END SUBROUTINE

SUBROUTINE swigc_equal_range__SWIG_3(farg1, farg3, farg4, farg5) &
BIND(C, name="_wrap_equal_range__SWIG_3")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
REAL(C_DOUBLE), INTENT(IN) :: farg3
TYPE(C_PTR), VALUE :: farg4
TYPE(C_PTR), VALUE :: farg5
END SUBROUTINE

SUBROUTINE swigc_equal_range__SWIG_4(farg1, farg3, farg4, farg5, farg6) &
BIND(C, name="_wrap_equal_range__SWIG_4")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT32_T), INTENT(IN) :: farg3
TYPE(C_PTR), VALUE :: farg4
TYPE(C_PTR), VALUE :: farg5
TYPE(C_FUNPTR), VALUE :: farg6
END SUBROUTINE

SUBROUTINE swigc_equal_range__SWIG_5(farg1, farg3, farg4, farg5, farg6) &
BIND(C, name="_wrap_equal_range__SWIG_5")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT64_T), INTENT(IN) :: farg3
TYPE(C_PTR), VALUE :: farg4
TYPE(C_PTR), VALUE :: farg5
TYPE(C_FUNPTR), VALUE :: farg6
END SUBROUTINE

SUBROUTINE swigc_equal_range__SWIG_6(farg1, farg3, farg4, farg5, farg6) &
BIND(C, name="_wrap_equal_range__SWIG_6")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
REAL(C_DOUBLE), INTENT(IN) :: farg3
TYPE(C_PTR), VALUE :: farg4
TYPE(C_PTR), VALUE :: farg5
TYPE(C_FUNPTR), VALUE :: farg6
END SUBROUTINE

SUBROUTINE swigc_equal_range__SWIG_7(farg1, farg3, farg4, farg5, farg6) &
BIND(C, name="_wrap_equal_range__SWIG_7")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR), INTENT(IN) :: farg3
TYPE(C_PTR), VALUE :: farg4
TYPE(C_PTR), VALUE :: farg5
TYPE(C_FUNPTR), VALUE :: farg6
END SUBROUTINE

SUBROUTINE swigc_minmax_element__SWIG_1(farg1, farg3, farg4) &
BIND(C, name="_wrap_minmax_element__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR), VALUE :: farg3
TYPE(C_PTR), VALUE :: farg4
END SUBROUTINE

SUBROUTINE swigc_minmax_element__SWIG_2(farg1, farg3, farg4) &
BIND(C, name="_wrap_minmax_element__SWIG_2")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR), VALUE :: farg3
TYPE(C_PTR), VALUE :: farg4
END SUBROUTINE

SUBROUTINE swigc_minmax_element__SWIG_3(farg1, farg3, farg4) &
BIND(C, name="_wrap_minmax_element__SWIG_3")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR), VALUE :: farg3
TYPE(C_PTR), VALUE :: farg4
END SUBROUTINE

SUBROUTINE swigc_minmax_element__SWIG_4(farg1, farg3, farg4, farg5) &
BIND(C, name="_wrap_minmax_element__SWIG_4")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR), VALUE :: farg3
TYPE(C_PTR), VALUE :: farg4
TYPE(C_FUNPTR), VALUE :: farg5
END SUBROUTINE

SUBROUTINE swigc_minmax_element__SWIG_5(farg1, farg3, farg4, farg5) &
BIND(C, name="_wrap_minmax_element__SWIG_5")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR), VALUE :: farg3
TYPE(C_PTR), VALUE :: farg4
TYPE(C_FUNPTR), VALUE :: farg5
END SUBROUTINE

SUBROUTINE swigc_minmax_element__SWIG_6(farg1, farg3, farg4, farg5) &
BIND(C, name="_wrap_minmax_element__SWIG_6")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR), VALUE :: farg3
TYPE(C_PTR), VALUE :: farg4
TYPE(C_FUNPTR), VALUE :: farg5
END SUBROUTINE

SUBROUTINE swigc_minmax_element__SWIG_7(farg1, farg3, farg4, farg5) &
BIND(C, name="_wrap_minmax_element__SWIG_7")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR), VALUE :: farg3
TYPE(C_PTR), VALUE :: farg4
TYPE(C_FUNPTR), VALUE :: farg5
END SUBROUTINE

FUNCTION swigc_includes__SWIG_1(farg1, farg3) &
BIND(C, name="_wrap_includes__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_includes__SWIG_2(farg1, farg3) &
BIND(C, name="_wrap_includes__SWIG_2") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_includes__SWIG_3(farg1, farg3) &
BIND(C, name="_wrap_includes__SWIG_3") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_includes__SWIG_4(farg1, farg3, farg5) &
BIND(C, name="_wrap_includes__SWIG_4") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR), VALUE :: farg5
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_includes__SWIG_5(farg1, farg3, farg5) &
BIND(C, name="_wrap_includes__SWIG_5") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR), VALUE :: farg5
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_includes__SWIG_6(farg1, farg3, farg5) &
BIND(C, name="_wrap_includes__SWIG_6") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR), VALUE :: farg5
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_includes__SWIG_7(farg1, farg3, farg5) &
BIND(C, name="_wrap_includes__SWIG_7") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR), VALUE :: farg5
INTEGER(C_INT) :: fresult
END FUNCTION

SUBROUTINE swigc_shuffle__SWIG_1(farg1, farg2) &
BIND(C, name="_wrap_shuffle__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
END SUBROUTINE

SUBROUTINE swigc_shuffle__SWIG_2(farg1, farg2) &
BIND(C, name="_wrap_shuffle__SWIG_2")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
END SUBROUTINE

SUBROUTINE swigc_shuffle__SWIG_3(farg1, farg2) &
BIND(C, name="_wrap_shuffle__SWIG_3")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
END SUBROUTINE

SUBROUTINE swigc_shuffle__SWIG_4(farg1, farg2) &
BIND(C, name="_wrap_shuffle__SWIG_4")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
END SUBROUTINE

END INTERFACE


CONTAINS
 ! MODULE SUBPROGRAMS
SUBROUTINE SWIGTM_fin_int32_t_Sb__SB_(finp, iminp)
  USE, INTRINSIC :: ISO_C_BINDING
  INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  INTEGER(C_SIZE_T) :: sz
  INTEGER(C_INT32_T), POINTER :: imtemp

  sz = SIZE(finp, KIND=C_SIZE_T)
  IF (sz > 0_c_size_t) THEN
    imtemp => finp(1)
    iminp%DATA = c_loc(imtemp)
  ELSE
    iminp%DATA = c_null_ptr
  END IF
  iminp%SIZE = sz
END SUBROUTINE
SUBROUTINE swigf_sort__SWIG_1(DATA)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), DIMENSION(:), TARGET :: DATA
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg1)
CALL swigc_sort__SWIG_1(farg1)
END SUBROUTINE

SUBROUTINE SWIGTM_fin_int64_t_Sb__SB_(finp, iminp)
  USE, INTRINSIC :: ISO_C_BINDING
  INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  INTEGER(C_SIZE_T) :: sz
  INTEGER(C_INT64_T), POINTER :: imtemp

  sz = SIZE(finp, KIND=C_SIZE_T)
  IF (sz > 0_c_size_t) THEN
    imtemp => finp(1)
    iminp%DATA = c_loc(imtemp)
  ELSE
    iminp%DATA = c_null_ptr
  END IF
  iminp%SIZE = sz
END SUBROUTINE
SUBROUTINE swigf_sort__SWIG_2(DATA)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), DIMENSION(:), TARGET :: DATA
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg1)
CALL swigc_sort__SWIG_2(farg1)
END SUBROUTINE

SUBROUTINE SWIGTM_fin_double_Sb__SB_(finp, iminp)
  USE, INTRINSIC :: ISO_C_BINDING
  REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  INTEGER(C_SIZE_T) :: sz
  REAL(C_DOUBLE), POINTER :: imtemp

  sz = SIZE(finp, KIND=C_SIZE_T)
  IF (sz > 0_c_size_t) THEN
    imtemp => finp(1)
    iminp%DATA = c_loc(imtemp)
  ELSE
    iminp%DATA = c_null_ptr
  END IF
  iminp%SIZE = sz
END SUBROUTINE
SUBROUTINE swigf_sort__SWIG_3(DATA)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), DIMENSION(:), TARGET :: DATA
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_double_Sb__SB_(DATA, farg1)
CALL swigc_sort__SWIG_3(farg1)
END SUBROUTINE

SUBROUTINE swigf_sort__SWIG_4(DATA, cmp)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), DIMENSION(:), TARGET :: DATA
PROCEDURE(flc_cmp_int4) :: cmp
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR) :: farg3

CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg1)
farg3 = c_funloc(cmp)
CALL swigc_sort__SWIG_4(farg1, farg3)
END SUBROUTINE

SUBROUTINE swigf_sort__SWIG_5(DATA, cmp)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), DIMENSION(:), TARGET :: DATA
PROCEDURE(flc_cmp_int8) :: cmp
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR) :: farg3

CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg1)
farg3 = c_funloc(cmp)
CALL swigc_sort__SWIG_5(farg1, farg3)
END SUBROUTINE

SUBROUTINE swigf_sort__SWIG_6(DATA, cmp)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), DIMENSION(:), TARGET :: DATA
PROCEDURE(flc_cmp_real8) :: cmp
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR) :: farg3

CALL SWIGTM_fin_double_Sb__SB_(DATA, farg1)
farg3 = c_funloc(cmp)
CALL swigc_sort__SWIG_6(farg1, farg3)
END SUBROUTINE

SUBROUTINE SWIGTM_fin_void_Sm__Sb__SB_(finp, iminp)
  USE, INTRINSIC :: ISO_C_BINDING
  TYPE(C_PTR), DIMENSION(:), INTENT(IN), TARGET :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  INTEGER(C_SIZE_T) :: sz
  TYPE(C_PTR), POINTER :: imtemp

  sz = SIZE(finp, KIND=C_SIZE_T)
  IF (sz > 0_c_size_t) THEN
    imtemp => finp(1)
    iminp%DATA = c_loc(imtemp)
  ELSE
    iminp%DATA = c_null_ptr
  END IF
  iminp%SIZE = sz
END SUBROUTINE
SUBROUTINE swigf_sort__SWIG_7(DATA, cmp)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(C_PTR), DIMENSION(:), TARGET :: DATA
PROCEDURE(flc_cmp_ptr) :: cmp
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR) :: farg3

CALL SWIGTM_fin_void_Sm__Sb__SB_(DATA, farg1)
farg3 = c_funloc(cmp)
CALL swigc_sort__SWIG_7(farg1, farg3)
END SUBROUTINE


SUBROUTINE SWIGTM_fout_bool(imout, fout)
  USE, INTRINSIC :: ISO_C_BINDING
  INTEGER(KIND=C_INT), INTENT(IN) :: imout
  LOGICAL, INTENT(OUT) :: fout
  fout = (imout /= 0)
END SUBROUTINE

FUNCTION swigf_is_sorted__SWIG_1(DATA) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg1)
fresult = swigc_is_sorted__SWIG_1(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_is_sorted__SWIG_2(DATA) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg1)
fresult = swigc_is_sorted__SWIG_2(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_is_sorted__SWIG_3(DATA) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_double_Sb__SB_(DATA, farg1)
fresult = swigc_is_sorted__SWIG_3(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_is_sorted__SWIG_4(DATA, cmp) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
PROCEDURE(flc_cmp_int4) :: cmp
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR) :: farg3

CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg1)
farg3 = c_funloc(cmp)
fresult = swigc_is_sorted__SWIG_4(farg1, farg3)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_is_sorted__SWIG_5(DATA, cmp) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
PROCEDURE(flc_cmp_int8) :: cmp
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR) :: farg3

CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg1)
farg3 = c_funloc(cmp)
fresult = swigc_is_sorted__SWIG_5(farg1, farg3)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_is_sorted__SWIG_6(DATA, cmp) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: DATA
PROCEDURE(flc_cmp_real8) :: cmp
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR) :: farg3

CALL SWIGTM_fin_double_Sb__SB_(DATA, farg1)
farg3 = c_funloc(cmp)
fresult = swigc_is_sorted__SWIG_6(farg1, farg3)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_is_sorted__SWIG_7(DATA, cmp) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
TYPE(C_PTR), DIMENSION(:), INTENT(IN), TARGET :: DATA
PROCEDURE(flc_cmp_ptr) :: cmp
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_FUNPTR) :: farg3

CALL SWIGTM_fin_void_Sm__Sb__SB_(DATA, farg1)
farg3 = c_funloc(cmp)
fresult = swigc_is_sorted__SWIG_7(farg1, farg3)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

SUBROUTINE SWIGTM_fin_int_Sb__SB_(finp, iminp)
  USE, INTRINSIC :: ISO_C_BINDING
  INTEGER(C_INT), DIMENSION(:), INTENT(IN), TARGET :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  INTEGER(C_SIZE_T) :: sz
  INTEGER(C_INT), POINTER :: imtemp

  sz = SIZE(finp, KIND=C_SIZE_T)
  IF (sz > 0_c_size_t) THEN
    imtemp => finp(1)
    iminp%DATA = c_loc(imtemp)
  ELSE
    iminp%DATA = c_null_ptr
  END IF
  iminp%SIZE = sz
END SUBROUTINE
SUBROUTINE swigf_argsort__SWIG_1(DATA, idx)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT), DIMENSION(:), TARGET :: idx
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3

CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg1)
CALL SWIGTM_fin_int_Sb__SB_(idx, farg3)
CALL swigc_argsort__SWIG_1(farg1, farg3)
END SUBROUTINE

SUBROUTINE swigf_argsort__SWIG_2(DATA, idx)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT), DIMENSION(:), TARGET :: idx
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3

CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg1)
CALL SWIGTM_fin_int_Sb__SB_(idx, farg3)
CALL swigc_argsort__SWIG_2(farg1, farg3)
END SUBROUTINE

SUBROUTINE swigf_argsort__SWIG_3(DATA, idx)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT), DIMENSION(:), TARGET :: idx
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3

CALL SWIGTM_fin_double_Sb__SB_(DATA, farg1)
CALL SWIGTM_fin_int_Sb__SB_(idx, farg3)
CALL swigc_argsort__SWIG_3(farg1, farg3)
END SUBROUTINE

SUBROUTINE swigf_argsort__SWIG_4(DATA, idx, cmp)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT), DIMENSION(:), TARGET :: idx
PROCEDURE(flc_cmp_int4) :: cmp
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR) :: farg5

CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg1)
CALL SWIGTM_fin_int_Sb__SB_(idx, farg3)
farg5 = c_funloc(cmp)
CALL swigc_argsort__SWIG_4(farg1, farg3, farg5)
END SUBROUTINE

SUBROUTINE swigf_argsort__SWIG_5(DATA, idx, cmp)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT), DIMENSION(:), TARGET :: idx
PROCEDURE(flc_cmp_int8) :: cmp
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR) :: farg5

CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg1)
CALL SWIGTM_fin_int_Sb__SB_(idx, farg3)
farg5 = c_funloc(cmp)
CALL swigc_argsort__SWIG_5(farg1, farg3, farg5)
END SUBROUTINE

SUBROUTINE swigf_argsort__SWIG_6(DATA, idx, cmp)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT), DIMENSION(:), TARGET :: idx
PROCEDURE(flc_cmp_real8) :: cmp
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR) :: farg5

CALL SWIGTM_fin_double_Sb__SB_(DATA, farg1)
CALL SWIGTM_fin_int_Sb__SB_(idx, farg3)
farg5 = c_funloc(cmp)
CALL swigc_argsort__SWIG_6(farg1, farg3, farg5)
END SUBROUTINE

SUBROUTINE swigf_argsort__SWIG_7(DATA, idx, cmp)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(C_PTR), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT), DIMENSION(:), TARGET :: idx
PROCEDURE(flc_cmp_ptr) :: cmp
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR) :: farg5

CALL SWIGTM_fin_void_Sm__Sb__SB_(DATA, farg1)
CALL SWIGTM_fin_int_Sb__SB_(idx, farg3)
farg5 = c_funloc(cmp)
CALL swigc_argsort__SWIG_7(farg1, farg3, farg5)
END SUBROUTINE

FUNCTION swigf_binary_search__SWIG_1(DATA, VALUE) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(INDEX_INT) :: swig_result
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT32_T), INTENT(IN) :: VALUE
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT32_T) :: farg3

CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg1)
farg3 = VALUE
fresult = swigc_binary_search__SWIG_1(farg1, farg3)
swig_result = fresult
END FUNCTION

FUNCTION swigf_binary_search__SWIG_2(DATA, VALUE) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(INDEX_INT) :: swig_result
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT64_T), INTENT(IN) :: VALUE
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT64_T) :: farg3

CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg1)
farg3 = VALUE
fresult = swigc_binary_search__SWIG_2(farg1, farg3)
swig_result = fresult
END FUNCTION

FUNCTION swigf_binary_search__SWIG_3(DATA, VALUE) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(INDEX_INT) :: swig_result
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: DATA
REAL(C_DOUBLE), INTENT(IN) :: VALUE
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
REAL(C_DOUBLE) :: farg3

CALL SWIGTM_fin_double_Sb__SB_(DATA, farg1)
farg3 = VALUE
fresult = swigc_binary_search__SWIG_3(farg1, farg3)
swig_result = fresult
END FUNCTION

FUNCTION swigf_binary_search__SWIG_4(DATA, VALUE, cmp) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(INDEX_INT) :: swig_result
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT32_T), INTENT(IN) :: VALUE
PROCEDURE(flc_cmp_int4) :: cmp
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT32_T) :: farg3
TYPE(C_FUNPTR) :: farg4

CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg1)
farg3 = VALUE
farg4 = c_funloc(cmp)
fresult = swigc_binary_search__SWIG_4(farg1, farg3, farg4)
swig_result = fresult
END FUNCTION

FUNCTION swigf_binary_search__SWIG_5(DATA, VALUE, cmp) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(INDEX_INT) :: swig_result
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT64_T), INTENT(IN) :: VALUE
PROCEDURE(flc_cmp_int8) :: cmp
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT64_T) :: farg3
TYPE(C_FUNPTR) :: farg4

CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg1)
farg3 = VALUE
farg4 = c_funloc(cmp)
fresult = swigc_binary_search__SWIG_5(farg1, farg3, farg4)
swig_result = fresult
END FUNCTION

FUNCTION swigf_binary_search__SWIG_6(DATA, VALUE, cmp) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(INDEX_INT) :: swig_result
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: DATA
REAL(C_DOUBLE), INTENT(IN) :: VALUE
PROCEDURE(flc_cmp_real8) :: cmp
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
REAL(C_DOUBLE) :: farg3
TYPE(C_FUNPTR) :: farg4

CALL SWIGTM_fin_double_Sb__SB_(DATA, farg1)
farg3 = VALUE
farg4 = c_funloc(cmp)
fresult = swigc_binary_search__SWIG_6(farg1, farg3, farg4)
swig_result = fresult
END FUNCTION

FUNCTION swigf_binary_search__SWIG_7(DATA, VALUE, cmp) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(INDEX_INT) :: swig_result
TYPE(C_PTR), DIMENSION(:), INTENT(IN), TARGET :: DATA
TYPE(C_PTR), INTENT(IN) :: VALUE
PROCEDURE(flc_cmp_ptr) :: cmp
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR) :: farg3
TYPE(C_FUNPTR) :: farg4

CALL SWIGTM_fin_void_Sm__Sb__SB_(DATA, farg1)
farg3 = VALUE
farg4 = c_funloc(cmp)
fresult = swigc_binary_search__SWIG_7(farg1, farg3, farg4)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_equal_range__SWIG_1(DATA, VALUE, first_index, last_index)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT32_T), INTENT(IN) :: VALUE
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: first_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: last_index
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT32_T) :: farg3
TYPE(C_PTR) :: farg4
TYPE(C_PTR) :: farg5

CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg1)
farg3 = VALUE
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
CALL swigc_equal_range__SWIG_1(farg1, farg3, farg4, farg5)
END SUBROUTINE

SUBROUTINE swigf_equal_range__SWIG_2(DATA, VALUE, first_index, last_index)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT64_T), INTENT(IN) :: VALUE
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: first_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: last_index
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT64_T) :: farg3
TYPE(C_PTR) :: farg4
TYPE(C_PTR) :: farg5

CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg1)
farg3 = VALUE
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
CALL swigc_equal_range__SWIG_2(farg1, farg3, farg4, farg5)
END SUBROUTINE

SUBROUTINE swigf_equal_range__SWIG_3(DATA, VALUE, first_index, last_index)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: DATA
REAL(C_DOUBLE), INTENT(IN) :: VALUE
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: first_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: last_index
TYPE(SwigArrayWrapper) :: farg1
REAL(C_DOUBLE) :: farg3
TYPE(C_PTR) :: farg4
TYPE(C_PTR) :: farg5

CALL SWIGTM_fin_double_Sb__SB_(DATA, farg1)
farg3 = VALUE
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
CALL swigc_equal_range__SWIG_3(farg1, farg3, farg4, farg5)
END SUBROUTINE

SUBROUTINE swigf_equal_range__SWIG_4(DATA, VALUE, first_index, last_index, cmp)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT32_T), INTENT(IN) :: VALUE
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: first_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: last_index
PROCEDURE(flc_cmp_int4) :: cmp
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT32_T) :: farg3
TYPE(C_PTR) :: farg4
TYPE(C_PTR) :: farg5
TYPE(C_FUNPTR) :: farg6

CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg1)
farg3 = VALUE
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
farg6 = c_funloc(cmp)
CALL swigc_equal_range__SWIG_4(farg1, farg3, farg4, farg5, farg6)
END SUBROUTINE

SUBROUTINE swigf_equal_range__SWIG_5(DATA, VALUE, first_index, last_index, cmp)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(C_INT64_T), INTENT(IN) :: VALUE
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: first_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: last_index
PROCEDURE(flc_cmp_int8) :: cmp
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT64_T) :: farg3
TYPE(C_PTR) :: farg4
TYPE(C_PTR) :: farg5
TYPE(C_FUNPTR) :: farg6

CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg1)
farg3 = VALUE
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
farg6 = c_funloc(cmp)
CALL swigc_equal_range__SWIG_5(farg1, farg3, farg4, farg5, farg6)
END SUBROUTINE

SUBROUTINE swigf_equal_range__SWIG_6(DATA, VALUE, first_index, last_index, cmp)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: DATA
REAL(C_DOUBLE), INTENT(IN) :: VALUE
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: first_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: last_index
PROCEDURE(flc_cmp_real8) :: cmp
TYPE(SwigArrayWrapper) :: farg1
REAL(C_DOUBLE) :: farg3
TYPE(C_PTR) :: farg4
TYPE(C_PTR) :: farg5
TYPE(C_FUNPTR) :: farg6

CALL SWIGTM_fin_double_Sb__SB_(DATA, farg1)
farg3 = VALUE
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
farg6 = c_funloc(cmp)
CALL swigc_equal_range__SWIG_6(farg1, farg3, farg4, farg5, farg6)
END SUBROUTINE

SUBROUTINE swigf_equal_range__SWIG_7(DATA, VALUE, first_index, last_index, cmp)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(C_PTR), DIMENSION(:), INTENT(IN), TARGET :: DATA
TYPE(C_PTR), INTENT(IN) :: VALUE
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: first_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: last_index
PROCEDURE(flc_cmp_ptr) :: cmp
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR) :: farg3
TYPE(C_PTR) :: farg4
TYPE(C_PTR) :: farg5
TYPE(C_FUNPTR) :: farg6

CALL SWIGTM_fin_void_Sm__Sb__SB_(DATA, farg1)
farg3 = VALUE
farg4 = c_loc(first_index)
farg5 = c_loc(last_index)
farg6 = c_funloc(cmp)
CALL swigc_equal_range__SWIG_7(farg1, farg3, farg4, farg5, farg6)
END SUBROUTINE

SUBROUTINE swigf_minmax_element__SWIG_1(DATA, min_index, max_index)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: min_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: max_index
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR) :: farg3
TYPE(C_PTR) :: farg4

CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
CALL swigc_minmax_element__SWIG_1(farg1, farg3, farg4)
END SUBROUTINE

SUBROUTINE swigf_minmax_element__SWIG_2(DATA, min_index, max_index)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: min_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: max_index
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR) :: farg3
TYPE(C_PTR) :: farg4

CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
CALL swigc_minmax_element__SWIG_2(farg1, farg3, farg4)
END SUBROUTINE

SUBROUTINE swigf_minmax_element__SWIG_3(DATA, min_index, max_index)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: min_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: max_index
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR) :: farg3
TYPE(C_PTR) :: farg4

CALL SWIGTM_fin_double_Sb__SB_(DATA, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
CALL swigc_minmax_element__SWIG_3(farg1, farg3, farg4)
END SUBROUTINE

SUBROUTINE swigf_minmax_element__SWIG_4(DATA, min_index, max_index, cmp)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: min_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: max_index
PROCEDURE(flc_cmp_int4) :: cmp
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR) :: farg3
TYPE(C_PTR) :: farg4
TYPE(C_FUNPTR) :: farg5

CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
farg5 = c_funloc(cmp)
CALL swigc_minmax_element__SWIG_4(farg1, farg3, farg4, farg5)
END SUBROUTINE

SUBROUTINE swigf_minmax_element__SWIG_5(DATA, min_index, max_index, cmp)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: min_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: max_index
PROCEDURE(flc_cmp_int8) :: cmp
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR) :: farg3
TYPE(C_PTR) :: farg4
TYPE(C_FUNPTR) :: farg5

CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
farg5 = c_funloc(cmp)
CALL swigc_minmax_element__SWIG_5(farg1, farg3, farg4, farg5)
END SUBROUTINE

SUBROUTINE swigf_minmax_element__SWIG_6(DATA, min_index, max_index, cmp)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: min_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: max_index
PROCEDURE(flc_cmp_real8) :: cmp
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR) :: farg3
TYPE(C_PTR) :: farg4
TYPE(C_FUNPTR) :: farg5

CALL SWIGTM_fin_double_Sb__SB_(DATA, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
farg5 = c_funloc(cmp)
CALL swigc_minmax_element__SWIG_6(farg1, farg3, farg4, farg5)
END SUBROUTINE

SUBROUTINE swigf_minmax_element__SWIG_7(DATA, min_index, max_index, cmp)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(C_PTR), DIMENSION(:), INTENT(IN), TARGET :: DATA
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: min_index
INTEGER(INDEX_INT), TARGET, INTENT(INOUT) :: max_index
PROCEDURE(flc_cmp_ptr) :: cmp
TYPE(SwigArrayWrapper) :: farg1
TYPE(C_PTR) :: farg3
TYPE(C_PTR) :: farg4
TYPE(C_FUNPTR) :: farg5

CALL SWIGTM_fin_void_Sm__Sb__SB_(DATA, farg1)
farg3 = c_loc(min_index)
farg4 = c_loc(max_index)
farg5 = c_funloc(cmp)
CALL swigc_minmax_element__SWIG_7(farg1, farg3, farg4, farg5)
END SUBROUTINE

FUNCTION swigf_includes__SWIG_1(data1, data2) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: data1
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: data2
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3

CALL SWIGTM_fin_int32_t_Sb__SB_(data1, farg1)
CALL SWIGTM_fin_int32_t_Sb__SB_(data2, farg3)
fresult = swigc_includes__SWIG_1(farg1, farg3)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_includes__SWIG_2(data1, data2) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: data1
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: data2
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3

CALL SWIGTM_fin_int64_t_Sb__SB_(data1, farg1)
CALL SWIGTM_fin_int64_t_Sb__SB_(data2, farg3)
fresult = swigc_includes__SWIG_2(farg1, farg3)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_includes__SWIG_3(data1, data2) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: data1
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: data2
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3

CALL SWIGTM_fin_double_Sb__SB_(data1, farg1)
CALL SWIGTM_fin_double_Sb__SB_(data2, farg3)
fresult = swigc_includes__SWIG_3(farg1, farg3)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_includes__SWIG_4(data1, data2, cmp) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: data1
INTEGER(C_INT32_T), DIMENSION(:), INTENT(IN), TARGET :: data2
PROCEDURE(flc_cmp_int4) :: cmp
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR) :: farg5

CALL SWIGTM_fin_int32_t_Sb__SB_(data1, farg1)
CALL SWIGTM_fin_int32_t_Sb__SB_(data2, farg3)
farg5 = c_funloc(cmp)
fresult = swigc_includes__SWIG_4(farg1, farg3, farg5)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_includes__SWIG_5(data1, data2, cmp) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: data1
INTEGER(C_INT64_T), DIMENSION(:), INTENT(IN), TARGET :: data2
PROCEDURE(flc_cmp_int8) :: cmp
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR) :: farg5

CALL SWIGTM_fin_int64_t_Sb__SB_(data1, farg1)
CALL SWIGTM_fin_int64_t_Sb__SB_(data2, farg3)
farg5 = c_funloc(cmp)
fresult = swigc_includes__SWIG_5(farg1, farg3, farg5)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_includes__SWIG_6(data1, data2, cmp) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: data1
REAL(C_DOUBLE), DIMENSION(:), INTENT(IN), TARGET :: data2
PROCEDURE(flc_cmp_real8) :: cmp
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR) :: farg5

CALL SWIGTM_fin_double_Sb__SB_(data1, farg1)
CALL SWIGTM_fin_double_Sb__SB_(data2, farg3)
farg5 = c_funloc(cmp)
fresult = swigc_includes__SWIG_6(farg1, farg3, farg5)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_includes__SWIG_7(data1, data2, cmp) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
TYPE(C_PTR), DIMENSION(:), INTENT(IN), TARGET :: data1
TYPE(C_PTR), DIMENSION(:), INTENT(IN), TARGET :: data2
PROCEDURE(flc_cmp_ptr) :: cmp
INTEGER(C_INT) :: fresult
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg3
TYPE(C_FUNPTR) :: farg5

CALL SWIGTM_fin_void_Sm__Sb__SB_(data1, farg1)
CALL SWIGTM_fin_void_Sm__Sb__SB_(data2, farg3)
farg5 = c_funloc(cmp)
fresult = swigc_includes__SWIG_7(farg1, farg3, farg5)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

SUBROUTINE swigf_shuffle__SWIG_1(g, DATA)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MersenneEngine4), INTENT(IN) :: g
INTEGER(C_INT32_T), DIMENSION(:), TARGET :: DATA
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg2

farg1 = g%swigdata
CALL SWIGTM_fin_int32_t_Sb__SB_(DATA, farg2)
CALL swigc_shuffle__SWIG_1(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_shuffle__SWIG_2(g, DATA)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MersenneEngine4), INTENT(IN) :: g
INTEGER(C_INT64_T), DIMENSION(:), TARGET :: DATA
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg2

farg1 = g%swigdata
CALL SWIGTM_fin_int64_t_Sb__SB_(DATA, farg2)
CALL swigc_shuffle__SWIG_2(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_shuffle__SWIG_3(g, DATA)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MersenneEngine4), INTENT(IN) :: g
REAL(C_DOUBLE), DIMENSION(:), TARGET :: DATA
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg2

farg1 = g%swigdata
CALL SWIGTM_fin_double_Sb__SB_(DATA, farg2)
CALL swigc_shuffle__SWIG_3(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_shuffle__SWIG_4(g, DATA)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(MersenneEngine4), INTENT(IN) :: g
TYPE(C_PTR), DIMENSION(:), TARGET :: DATA
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg2

farg1 = g%swigdata
CALL SWIGTM_fin_void_Sm__Sb__SB_(DATA, farg2)
CALL swigc_shuffle__SWIG_4(farg1, farg2)
END SUBROUTINE


END MODULE
