! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.2+fortran
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! Flibcpp project, https://github.com/swig-fortran/flibcpp
! Copyright (c) 2019-2020 Oak Ridge National Laboratory, UT-Battelle, LLC.
! Distributed under an MIT open source license: see LICENSE for details.

MODULE ModLib_FLC_String
 USE, INTRINSIC :: ISO_C_BINDING
 USE ModLib_FLC
 IMPLICIT NONE
 PRIVATE

 ! DECLARATION CONSTRUCTS

 INTEGER, PARAMETER :: swig_cmem_own_bit = 0
 INTEGER, PARAMETER :: swig_cmem_rvalue_bit = 1
 TYPE, BIND(C) :: SwigClassWrapper
  TYPE(C_PTR), PUBLIC :: cptr = C_NULL_PTR
  INTEGER(C_INT), PUBLIC :: cmemflags = 0
 END TYPE
 TYPE, BIND(C) :: SwigArrayWrapper
  TYPE(C_PTR), PUBLIC :: DATA = C_NULL_PTR
  INTEGER(C_SIZE_T), PUBLIC :: SIZE = 0
 END TYPE
 ! class std::string
 TYPE, PUBLIC :: string
  TYPE(SwigClassWrapper), PUBLIC :: swigdata
 CONTAINS
  PROCEDURE :: SIZE => swigf_string_size
  PROCEDURE :: empty => swigf_string_empty
  PROCEDURE :: front => swigf_string_front
  PROCEDURE :: back => swigf_string_back
  PROCEDURE, PRIVATE :: swigf_string_resize__SWIG_0
  PROCEDURE, PRIVATE :: swigf_string_resize__SWIG_1
  PROCEDURE :: ASSIGN => swigf_string_assign
  PROCEDURE :: push_back => swigf_string_push_back
  PROCEDURE :: pop_back => swigf_string_pop_back
  PROCEDURE :: clear => swigf_string_clear
  PROCEDURE, PRIVATE :: swigf_string_find__SWIG_0
  PROCEDURE, PRIVATE :: swigf_string_find__SWIG_1
  PROCEDURE :: append => swigf_string_append
  PROCEDURE :: compare => swigf_string_compare
  PROCEDURE :: set => swigf_string_set
  PROCEDURE :: get => swigf_string_get
  PROCEDURE :: view => swigf_string_view
  PROCEDURE :: str => swigf_string_str
  PROCEDURE :: release => swigf_string_release
  PROCEDURE, PRIVATE :: swigf_string_op_assign__
  GENERIC :: ASSIGNMENT(=) => swigf_string_op_assign__
  GENERIC :: resize => swigf_string_resize__SWIG_0, swigf_string_resize__SWIG_1
  GENERIC :: FIND => swigf_string_find__SWIG_0, swigf_string_find__SWIG_1
 END TYPE string
 PUBLIC :: stof
 PUBLIC :: stod
 INTERFACE stoi
  MODULE PROCEDURE swigf_stoi__SWIG_0, swigf_stoi__SWIG_1
 END INTERFACE
 PUBLIC :: stoi
 INTERFACE stoll
  MODULE PROCEDURE swigf_stoll__SWIG_0, swigf_stoll__SWIG_1
 END INTERFACE
 PUBLIC :: stoll
 INTERFACE stol
  MODULE PROCEDURE swigf_stol__SWIG_0, swigf_stol__SWIG_1
 END INTERFACE
 PUBLIC :: stol
 INTERFACE string
  MODULE PROCEDURE swigf_new_string__SWIG_0, swigf_new_string__SWIG_1, swigf_new_string__SWIG_2
 END INTERFACE

! WRAPPER DECLARATIONS
INTERFACE
FUNCTION swigc_new_string__SWIG_0() &
BIND(C, name="_wrap_new_string__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_string__SWIG_1(farg1, farg2) &
BIND(C, name="_wrap_new_string__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
INTEGER(C_LONG), INTENT(IN) :: farg1
CHARACTER(C_CHAR), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_new_string__SWIG_2(farg1) &
BIND(C, name="_wrap_new_string__SWIG_2") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_string_size(farg1) &
BIND(C, name="_wrap_string_size") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_string_empty(farg1) &
BIND(C, name="_wrap_string_empty") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_string_front(farg1) &
BIND(C, name="_wrap_string_front") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
CHARACTER(C_CHAR) :: fresult
END FUNCTION

FUNCTION swigc_string_back(farg1) &
BIND(C, name="_wrap_string_back") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
CHARACTER(C_CHAR) :: fresult
END FUNCTION

SUBROUTINE swigc_string_resize__SWIG_0(farg1, farg2) &
BIND(C, name="_wrap_string_resize__SWIG_0")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_string_resize__SWIG_1(farg1, farg2, farg3) &
BIND(C, name="_wrap_string_resize__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
CHARACTER(C_CHAR), INTENT(IN) :: farg3
END SUBROUTINE

SUBROUTINE swigc_string_assign(farg1, farg2) &
BIND(C, name="_wrap_string_assign")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
END SUBROUTINE

SUBROUTINE swigc_string_push_back(farg1, farg2) &
BIND(C, name="_wrap_string_push_back")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
CHARACTER(C_CHAR), INTENT(IN) :: farg2
END SUBROUTINE

SUBROUTINE swigc_string_pop_back(farg1) &
BIND(C, name="_wrap_string_pop_back")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

SUBROUTINE swigc_string_clear(farg1) &
BIND(C, name="_wrap_string_clear")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

FUNCTION swigc_string_find__SWIG_0(farg1, farg2, farg3) &
BIND(C, name="_wrap_string_find__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_LONG), INTENT(IN) :: farg3
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_string_find__SWIG_1(farg1, farg2) &
BIND(C, name="_wrap_string_find__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_LONG) :: fresult
END FUNCTION

SUBROUTINE swigc_string_append(farg1, farg2) &
BIND(C, name="_wrap_string_append")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
END SUBROUTINE

FUNCTION swigc_string_compare(farg1, farg2) &
BIND(C, name="_wrap_string_compare") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
INTEGER(C_INT) :: fresult
END FUNCTION

SUBROUTINE swigc_string_set(farg1, farg2, farg3) &
BIND(C, name="_wrap_string_set")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
CHARACTER(C_CHAR), INTENT(IN) :: farg3
END SUBROUTINE

FUNCTION swigc_string_get(farg1, farg2) &
BIND(C, name="_wrap_string_get") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG), INTENT(IN) :: farg2
CHARACTER(C_CHAR) :: fresult
END FUNCTION

FUNCTION swigc_string_view(farg1) &
BIND(C, name="_wrap_string_view") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: fresult
END FUNCTION

 SUBROUTINE SWIG_free(cptr) &
  BIND(C, name="free")
 USE, INTRINSIC :: ISO_C_BINDING
 TYPE(C_PTR), VALUE :: cptr
END SUBROUTINE
FUNCTION swigc_string_str(farg1) &
BIND(C, name="_wrap_string_str") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_delete_string(farg1) &
BIND(C, name="_wrap_delete_string")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
END SUBROUTINE

SUBROUTINE swigc_string_op_assign__(farg1, farg2) &
BIND(C, name="_wrap_string_op_assign__")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

FUNCTION swigc_stoi__SWIG_0(farg1, farg3) &
BIND(C, name="_wrap_stoi__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT), INTENT(IN) :: farg3
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_stoi__SWIG_1(farg1) &
BIND(C, name="_wrap_stoi__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_stol__SWIG_0(farg1, farg3) &
BIND(C, name="_wrap_stol__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT), INTENT(IN) :: farg3
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_stol__SWIG_1(farg1) &
BIND(C, name="_wrap_stol__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_stoll__SWIG_0(farg1, farg3) &
BIND(C, name="_wrap_stoll__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT), INTENT(IN) :: farg3
INTEGER(C_LONG_LONG) :: fresult
END FUNCTION

FUNCTION swigc_stoll__SWIG_1(farg1) &
BIND(C, name="_wrap_stoll__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_LONG_LONG) :: fresult
END FUNCTION

FUNCTION swigc_stof(farg1) &
BIND(C, name="_wrap_stof") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
REAL(C_FLOAT) :: fresult
END FUNCTION

FUNCTION swigc_stod(farg1) &
BIND(C, name="_wrap_stod") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
REAL(C_DOUBLE) :: fresult
END FUNCTION

END INTERFACE


CONTAINS
 ! MODULE SUBPROGRAMS
FUNCTION swigf_new_string__SWIG_0() &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(string) :: self
TYPE(SwigClassWrapper) :: fresult

fresult = swigc_new_string__SWIG_0()
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_new_string__SWIG_1(COUNT, ch) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(string) :: self
INTEGER, INTENT(IN) :: COUNT
CHARACTER(C_CHAR), INTENT(IN) :: ch
TYPE(SwigClassWrapper) :: fresult
INTEGER(C_LONG) :: farg1
CHARACTER(C_CHAR) :: farg2

farg1 = INT(COUNT, C_INT)
farg2 = ch
fresult = swigc_new_string__SWIG_1(farg1, farg2)
self%swigdata = fresult
END FUNCTION


SUBROUTINE SWIGTM_fin_char_Sm_(finp, iminp, temp)
  USE, INTRINSIC :: ISO_C_BINDING
  CHARACTER(LEN=*), INTENT(IN) :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  CHARACTER(KIND=C_CHAR), DIMENSION(:), TARGET, ALLOCATABLE, INTENT(OUT) :: temp
  INTEGER :: i

  ALLOCATE(CHARACTER(KIND=C_CHAR) :: temp(LEN(finp) + 1))
  DO i=1,LEN(finp)
    temp(i) = CHAR(ICHAR(finp(i:i)), KIND=C_CHAR)
  END DO
  i = LEN(finp) + 1
  temp(i) = C_NULL_CHAR ! C finp compatibility
  iminp%DATA = c_loc(temp)
  iminp%SIZE = LEN(finp, KIND=C_SIZE_T)
END SUBROUTINE

FUNCTION swigf_new_string__SWIG_2(s) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(string) :: self
CHARACTER(LEN=*), TARGET :: s
TYPE(SwigClassWrapper) :: fresult
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg1_temp
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_char_Sm_(s, farg1, farg1_temp)
fresult = swigc_new_string__SWIG_2(farg1)
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_string_size(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(string), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_string_size(farg1)
swig_result = INT(fresult)
END FUNCTION


SUBROUTINE SWIGTM_fout_bool(imout, fout)
  USE, INTRINSIC :: ISO_C_BINDING
  INTEGER(KIND=C_INT), INTENT(IN) :: imout
  LOGICAL, INTENT(OUT) :: fout
  fout = (imout /= 0)
END SUBROUTINE

FUNCTION swigf_string_empty(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
CLASS(string), INTENT(IN) :: self
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_string_empty(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_string_front(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CHARACTER(C_CHAR) :: swig_result
CLASS(string), INTENT(IN) :: self
CHARACTER(C_CHAR) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_string_front(farg1)
swig_result = fresult
END FUNCTION

FUNCTION swigf_string_back(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CHARACTER(C_CHAR) :: swig_result
CLASS(string), INTENT(IN) :: self
CHARACTER(C_CHAR) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_string_back(farg1)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_string_resize__SWIG_0(self, COUNT)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(string), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
CALL swigc_string_resize__SWIG_0(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_string_resize__SWIG_1(self, COUNT, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(string), INTENT(IN) :: self
INTEGER, INTENT(IN) :: COUNT
CHARACTER(C_CHAR), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
CHARACTER(C_CHAR) :: farg3

farg1 = self%swigdata
farg2 = INT(COUNT, C_INT)
farg3 = v
CALL swigc_string_resize__SWIG_1(farg1, farg2, farg3)
END SUBROUTINE

SUBROUTINE swigf_string_assign(self, s)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(string), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: s
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(s, farg2, farg2_temp)
CALL swigc_string_assign(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_string_push_back(self, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(string), INTENT(IN) :: self
CHARACTER(C_CHAR), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
CHARACTER(C_CHAR) :: farg2

farg1 = self%swigdata
farg2 = v
CALL swigc_string_push_back(farg1, farg2)
END SUBROUTINE

SUBROUTINE swigf_string_pop_back(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(string), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_string_pop_back(farg1)
END SUBROUTINE

SUBROUTINE swigf_string_clear(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(string), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_string_clear(farg1)
END SUBROUTINE

FUNCTION swigf_string_find__SWIG_0(self, s, pos) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(string), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: s
INTEGER, INTENT(IN) :: pos
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_LONG) :: farg3

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(s, farg2, farg2_temp)
farg3 = INT(pos, C_INT)
fresult = swigc_string_find__SWIG_0(farg1, farg2, farg3)
swig_result = INT(fresult)
END FUNCTION

FUNCTION swigf_string_find__SWIG_1(self, s) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(string), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: s
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(s, farg2, farg2_temp)
fresult = swigc_string_find__SWIG_1(farg1, farg2)
swig_result = INT(fresult)
END FUNCTION

SUBROUTINE swigf_string_append(self, s)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(string), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: s
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(s, farg2, farg2_temp)
CALL swigc_string_append(farg1, farg2)
END SUBROUTINE

FUNCTION swigf_string_compare(self, other) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT) :: swig_result
CLASS(string), INTENT(IN) :: self
CLASS(string), INTENT(IN) :: other
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
fresult = swigc_string_compare(farg1, farg2)
swig_result = fresult
END FUNCTION

SUBROUTINE swigf_string_set(self, INDEX, v)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(string), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
CHARACTER(C_CHAR), INTENT(IN) :: v
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2
CHARACTER(C_CHAR) :: farg3

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
farg3 = v
CALL swigc_string_set(farg1, farg2, farg3)
END SUBROUTINE

FUNCTION swigf_string_get(self, INDEX) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CHARACTER(C_CHAR) :: swig_result
CLASS(string), INTENT(IN) :: self
INTEGER, INTENT(IN) :: INDEX
CHARACTER(C_CHAR) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_LONG) :: farg2

farg1 = self%swigdata
farg2 = INT(INDEX, C_INT)
fresult = swigc_string_get(farg1, farg2)
swig_result = fresult
END FUNCTION

SUBROUTINE SWIGTM_fout_char_Sb__SB_(imout, fout)
  USE, INTRINSIC :: ISO_C_BINDING
  TYPE(SwigArrayWrapper), INTENT(IN) :: imout
  CHARACTER(C_CHAR), DIMENSION(:), POINTER, INTENT(OUT) :: fout

  IF (imout%SIZE > 0) THEN
    CALL c_f_pointer(imout%DATA, fout, [imout%SIZE])
  ELSE
    fout => NULL()
  END IF
END SUBROUTINE
FUNCTION swigf_string_view(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CHARACTER(C_CHAR), DIMENSION(:), POINTER :: swig_result
CLASS(string), INTENT(IN) :: self
TYPE(SwigArrayWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_string_view(farg1)
CALL SWIGTM_fout_char_Sb__SB_(fresult, swig_result)
END FUNCTION


SUBROUTINE SWIGTM_fout_char_Sm_(imout, fout)
  USE, INTRINSIC :: ISO_C_BINDING
  TYPE(SwigArrayWrapper), INTENT(IN) :: imout
  CHARACTER(LEN=:), ALLOCATABLE, INTENT(OUT) :: fout
  CHARACTER(KIND=C_CHAR), DIMENSION(:), POINTER :: chars
  INTEGER(KIND=C_SIZE_T) :: i
  CALL c_f_pointer(imout%DATA, chars, [imout%SIZE])
  ALLOCATE(CHARACTER(LEN=imout%SIZE) :: fout)
  DO i=1, imout%SIZE
    fout(i:i) = CHAR(ICHAR(chars(i)))
  END DO
END SUBROUTINE

FUNCTION swigf_string_str(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CHARACTER(LEN=:), ALLOCATABLE :: swig_result
CLASS(string), INTENT(IN) :: self
TYPE(SwigArrayWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_string_str(farg1)
CALL SWIGTM_fout_char_Sm_(fresult, swig_result)
CALL SWIG_free(fresult%DATA)
END FUNCTION

SUBROUTINE swigf_string_release(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(string), INTENT(INOUT) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
IF (BTEST(farg1%cmemflags, swig_cmem_own_bit)) THEN
CALL swigc_delete_string(farg1)
END IF
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE swigf_string_op_assign__(self, other)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(string), INTENT(INOUT) :: self
TYPE(string), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
CALL swigc_string_op_assign__(farg1, farg2)
self%swigdata = farg1
END SUBROUTINE

FUNCTION swigf_stoi__SWIG_0(s, base) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT) :: swig_result
CHARACTER(LEN=*), TARGET :: s
INTEGER(C_INT), INTENT(IN) :: base
INTEGER(C_INT) :: fresult
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg1_temp
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT) :: farg3

CALL SWIGTM_fin_char_Sm_(s, farg1, farg1_temp)
farg3 = base
fresult = swigc_stoi__SWIG_0(farg1, farg3)
swig_result = fresult
END FUNCTION

FUNCTION swigf_stoi__SWIG_1(s) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_INT) :: swig_result
CHARACTER(LEN=*), TARGET :: s
INTEGER(C_INT) :: fresult
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg1_temp
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_char_Sm_(s, farg1, farg1_temp)
fresult = swigc_stoi__SWIG_1(farg1)
swig_result = fresult
END FUNCTION

FUNCTION swigf_stol__SWIG_0(s, base) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_LONG) :: swig_result
CHARACTER(LEN=*), TARGET :: s
INTEGER(C_INT), INTENT(IN) :: base
INTEGER(C_LONG) :: fresult
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg1_temp
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT) :: farg3

CALL SWIGTM_fin_char_Sm_(s, farg1, farg1_temp)
farg3 = base
fresult = swigc_stol__SWIG_0(farg1, farg3)
swig_result = fresult
END FUNCTION

FUNCTION swigf_stol__SWIG_1(s) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_LONG) :: swig_result
CHARACTER(LEN=*), TARGET :: s
INTEGER(C_LONG) :: fresult
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg1_temp
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_char_Sm_(s, farg1, farg1_temp)
fresult = swigc_stol__SWIG_1(farg1)
swig_result = fresult
END FUNCTION

FUNCTION swigf_stoll__SWIG_0(s, base) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_LONG_LONG) :: swig_result
CHARACTER(LEN=*), TARGET :: s
INTEGER(C_INT), INTENT(IN) :: base
INTEGER(C_LONG_LONG) :: fresult
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg1_temp
TYPE(SwigArrayWrapper) :: farg1
INTEGER(C_INT) :: farg3

CALL SWIGTM_fin_char_Sm_(s, farg1, farg1_temp)
farg3 = base
fresult = swigc_stoll__SWIG_0(farg1, farg3)
swig_result = fresult
END FUNCTION

FUNCTION swigf_stoll__SWIG_1(s) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER(C_LONG_LONG) :: swig_result
CHARACTER(LEN=*), TARGET :: s
INTEGER(C_LONG_LONG) :: fresult
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg1_temp
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_char_Sm_(s, farg1, farg1_temp)
fresult = swigc_stoll__SWIG_1(farg1)
swig_result = fresult
END FUNCTION

FUNCTION stof(s) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_FLOAT) :: swig_result
CHARACTER(LEN=*), TARGET :: s
REAL(C_FLOAT) :: fresult
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg1_temp
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_char_Sm_(s, farg1, farg1_temp)
fresult = swigc_stof(farg1)
swig_result = fresult
END FUNCTION

FUNCTION stod(s) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
REAL(C_DOUBLE) :: swig_result
CHARACTER(LEN=*), TARGET :: s
REAL(C_DOUBLE) :: fresult
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg1_temp
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_char_Sm_(s, farg1, farg1_temp)
fresult = swigc_stod(farg1)
swig_result = fresult
END FUNCTION


END MODULE
