! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.2+fortran
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! Flibcpp project, https://github.com/swig-fortran/flibcpp
! Copyright (c) 2019-2020 Oak Ridge National Laboratory, UT-Battelle, LLC.
! Distributed under an MIT open source license: see LICENSE for details.

MODULE ModLib_FLC_Set
 USE, INTRINSIC :: ISO_C_BINDING
 USE ModLib_FLC
 USE ModLib_FLC_String
 IMPLICIT NONE
 PRIVATE

 ! DECLARATION CONSTRUCTS

 INTEGER, PARAMETER :: swig_cmem_own_bit = 0
 INTEGER, PARAMETER :: swig_cmem_rvalue_bit = 1
 TYPE, BIND(C) :: SwigClassWrapper
  TYPE(C_PTR), PUBLIC :: cptr = C_NULL_PTR
  INTEGER(C_INT), PUBLIC :: cmemflags = 0
 END TYPE
 TYPE, BIND(C) :: SwigArrayWrapper
  TYPE(C_PTR), PUBLIC :: DATA = C_NULL_PTR
  INTEGER(C_SIZE_T), PUBLIC :: SIZE = 0
 END TYPE
 ! class std::set< int >
 TYPE, PUBLIC :: SetInt
  TYPE(SwigClassWrapper), PUBLIC :: swigdata
 CONTAINS
  PROCEDURE :: empty => swigf_SetInt_empty
  PROCEDURE :: SIZE => swigf_SetInt_size
  PROCEDURE :: clear => swigf_SetInt_clear
  PROCEDURE :: erase => swigf_SetInt_erase
  PROCEDURE :: COUNT => swigf_SetInt_count
  PROCEDURE, PRIVATE :: swigf_SetInt_insert__SWIG_0
  PROCEDURE, PRIVATE :: swigf_SetInt_insert__SWIG_1
  PROCEDURE :: difference => swigf_SetInt_difference
  PROCEDURE :: intersection => swigf_SetInt_intersection
  PROCEDURE :: symmetric_difference => swigf_SetInt_symmetric_difference
  PROCEDURE :: UNION => swigf_SetInt_union
  PROCEDURE :: includes => swigf_SetInt_includes
  PROCEDURE :: release => swigf_SetInt_release
  PROCEDURE, PRIVATE :: swigf_SetInt_op_assign__
  GENERIC :: ASSIGNMENT(=) => swigf_SetInt_op_assign__
  GENERIC :: insert => swigf_SetInt_insert__SWIG_0, swigf_SetInt_insert__SWIG_1
 END TYPE SetInt
 ! class std::set< std::string >
 TYPE, PUBLIC :: SetString
  TYPE(SwigClassWrapper), PUBLIC :: swigdata
 CONTAINS
  PROCEDURE :: empty => swigf_SetString_empty
  PROCEDURE :: SIZE => swigf_SetString_size
  PROCEDURE :: clear => swigf_SetString_clear
  PROCEDURE :: erase => swigf_SetString_erase
  PROCEDURE :: COUNT => swigf_SetString_count
  PROCEDURE :: insert => swigf_SetString_insert
  PROCEDURE :: insert_ref => swigf_SetString_insert_ref
  PROCEDURE :: difference => swigf_SetString_difference
  PROCEDURE :: intersection => swigf_SetString_intersection
  PROCEDURE :: symmetric_difference => swigf_SetString_symmetric_difference
  PROCEDURE :: UNION => swigf_SetString_union
  PROCEDURE :: includes => swigf_SetString_includes
  PROCEDURE :: release => swigf_SetString_release
  PROCEDURE, PRIVATE :: swigf_SetString_op_assign__
  GENERIC :: ASSIGNMENT(=) => swigf_SetString_op_assign__
 END TYPE SetString
 INTERFACE SetInt
  MODULE PROCEDURE swigf_new_SetInt__SWIG_0, swigf_new_SetInt__SWIG_1
 END INTERFACE
 INTERFACE SetString
  MODULE PROCEDURE swigf_new_SetString
 END INTERFACE

! WRAPPER DECLARATIONS
INTERFACE
FUNCTION swigc_new_SetInt__SWIG_0() &
BIND(C, name="_wrap_new_SetInt__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_SetInt_empty(farg1) &
BIND(C, name="_wrap_SetInt_empty") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_SetInt_size(farg1) &
BIND(C, name="_wrap_SetInt_size") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

SUBROUTINE swigc_SetInt_clear(farg1) &
BIND(C, name="_wrap_SetInt_clear")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

FUNCTION swigc_SetInt_erase(farg1, farg2) &
BIND(C, name="_wrap_SetInt_erase") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT), INTENT(IN) :: farg2
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_SetInt_count(farg1, farg2) &
BIND(C, name="_wrap_SetInt_count") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT), INTENT(IN) :: farg2
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_SetInt_insert__SWIG_0(farg1, farg2) &
BIND(C, name="_wrap_SetInt_insert__SWIG_0") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT), INTENT(IN) :: farg2
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_new_SetInt__SWIG_1(farg1) &
BIND(C, name="_wrap_new_SetInt__SWIG_1") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigArrayWrapper) :: farg1
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

SUBROUTINE swigc_SetInt_insert__SWIG_1(farg1, farg2) &
BIND(C, name="_wrap_SetInt_insert__SWIG_1")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
END SUBROUTINE

FUNCTION swigc_SetInt_difference(farg1, farg2) &
BIND(C, name="_wrap_SetInt_difference") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_SetInt_intersection(farg1, farg2) &
BIND(C, name="_wrap_SetInt_intersection") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_SetInt_symmetric_difference(farg1, farg2) &
BIND(C, name="_wrap_SetInt_symmetric_difference") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_SetInt_union(farg1, farg2) &
BIND(C, name="_wrap_SetInt_union") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_SetInt_includes(farg1, farg2) &
BIND(C, name="_wrap_SetInt_includes") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
INTEGER(C_INT) :: fresult
END FUNCTION

SUBROUTINE swigc_delete_SetInt(farg1) &
BIND(C, name="_wrap_delete_SetInt")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
END SUBROUTINE

SUBROUTINE swigc_SetInt_op_assign__(farg1, farg2) &
BIND(C, name="_wrap_SetInt_op_assign__")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

FUNCTION swigc_new_SetString() &
BIND(C, name="_wrap_new_SetString") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_SetString_empty(farg1) &
BIND(C, name="_wrap_SetString_empty") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_INT) :: fresult
END FUNCTION

FUNCTION swigc_SetString_size(farg1) &
BIND(C, name="_wrap_SetString_size") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
INTEGER(C_LONG) :: fresult
END FUNCTION

SUBROUTINE swigc_SetString_clear(farg1) &
BIND(C, name="_wrap_SetString_clear")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
END SUBROUTINE

FUNCTION swigc_SetString_erase(farg1, farg2) &
BIND(C, name="_wrap_SetString_erase") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_SetString_count(farg1, farg2) &
BIND(C, name="_wrap_SetString_count") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_LONG) :: fresult
END FUNCTION

FUNCTION swigc_SetString_insert(farg1, farg2) &
BIND(C, name="_wrap_SetString_insert") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
IMPORT :: swigarraywrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigArrayWrapper) :: farg2
INTEGER(C_INT) :: fresult
END FUNCTION

SUBROUTINE swigc_SetString_insert_ref(farg1, farg2) &
BIND(C, name="_wrap_SetString_insert_ref")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

FUNCTION swigc_SetString_difference(farg1, farg2) &
BIND(C, name="_wrap_SetString_difference") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_SetString_intersection(farg1, farg2) &
BIND(C, name="_wrap_SetString_intersection") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_SetString_symmetric_difference(farg1, farg2) &
BIND(C, name="_wrap_SetString_symmetric_difference") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_SetString_union(farg1, farg2) &
BIND(C, name="_wrap_SetString_union") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
TYPE(SwigClassWrapper) :: fresult
END FUNCTION

FUNCTION swigc_SetString_includes(farg1, farg2) &
BIND(C, name="_wrap_SetString_includes") &
RESULT(fresult)
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(IN) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
INTEGER(C_INT) :: fresult
END FUNCTION

SUBROUTINE swigc_delete_SetString(farg1) &
BIND(C, name="_wrap_delete_SetString")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
END SUBROUTINE

SUBROUTINE swigc_SetString_op_assign__(farg1, farg2) &
BIND(C, name="_wrap_SetString_op_assign__")
USE, INTRINSIC :: ISO_C_BINDING
IMPORT :: swigclasswrapper
TYPE(SwigClassWrapper), INTENT(INOUT) :: farg1
TYPE(SwigClassWrapper), INTENT(IN) :: farg2
END SUBROUTINE

END INTERFACE


CONTAINS
 ! MODULE SUBPROGRAMS
FUNCTION swigf_new_SetInt__SWIG_0() &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(SetInt) :: self
TYPE(SwigClassWrapper) :: fresult

fresult = swigc_new_SetInt__SWIG_0()
self%swigdata = fresult
END FUNCTION


SUBROUTINE SWIGTM_fout_bool(imout, fout)
  USE, INTRINSIC :: ISO_C_BINDING
  INTEGER(KIND=C_INT), INTENT(IN) :: imout
  LOGICAL, INTENT(OUT) :: fout
  fout = (imout /= 0)
END SUBROUTINE

FUNCTION swigf_SetInt_empty(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
CLASS(SetInt), INTENT(IN) :: self
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_SetInt_empty(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_SetInt_size(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(SetInt), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_SetInt_size(farg1)
swig_result = INT(fresult)
END FUNCTION

SUBROUTINE swigf_SetInt_clear(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(SetInt), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_SetInt_clear(farg1)
END SUBROUTINE

SUBROUTINE swigf_SetInt_erase(self, x, swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(SetInt), INTENT(IN) :: self
INTEGER(C_INT), INTENT(IN) :: x
INTEGER, INTENT(OUT), OPTIONAL :: swig_result
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_INT) :: farg2

farg1 = self%swigdata
farg2 = x
fresult = swigc_SetInt_erase(farg1, farg2)
IF (PRESENT(swig_result)) THEN
swig_result = INT(fresult)
END IF

END SUBROUTINE

FUNCTION swigf_SetInt_count(self, x) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(SetInt), INTENT(IN) :: self
INTEGER(C_INT), INTENT(IN) :: x
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_INT) :: farg2

farg1 = self%swigdata
farg2 = x
fresult = swigc_SetInt_count(farg1, farg2)
swig_result = INT(fresult)
END FUNCTION

SUBROUTINE swigf_SetInt_insert__SWIG_0(self, x, swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(SetInt), INTENT(IN) :: self
INTEGER(C_INT), INTENT(IN) :: x
LOGICAL, INTENT(OUT), OPTIONAL :: swig_result
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1
INTEGER(C_INT) :: farg2

farg1 = self%swigdata
farg2 = x
fresult = swigc_SetInt_insert__SWIG_0(farg1, farg2)
IF (PRESENT(swig_result)) THEN
CALL SWIGTM_fout_bool(fresult, swig_result)
END IF

END SUBROUTINE

SUBROUTINE SWIGTM_fin_int_Sb__SB_(finp, iminp)
  USE, INTRINSIC :: ISO_C_BINDING
  INTEGER(C_INT), DIMENSION(:), INTENT(IN), TARGET :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  INTEGER(C_SIZE_T) :: sz
  INTEGER(C_INT), POINTER :: imtemp

  sz = SIZE(finp, KIND=C_SIZE_T)
  IF (sz > 0_c_size_t) THEN
    imtemp => finp(1)
    iminp%DATA = c_loc(imtemp)
  ELSE
    iminp%DATA = c_null_ptr
  END IF
  iminp%SIZE = sz
END SUBROUTINE
FUNCTION swigf_new_SetInt__SWIG_1(DATA) &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(SetInt) :: self
INTEGER(C_INT), DIMENSION(:), INTENT(IN), TARGET :: DATA
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigArrayWrapper) :: farg1

CALL SWIGTM_fin_int_Sb__SB_(DATA, farg1)
fresult = swigc_new_SetInt__SWIG_1(farg1)
self%swigdata = fresult
END FUNCTION

SUBROUTINE swigf_SetInt_insert__SWIG_1(self, DATA)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(SetInt), INTENT(IN) :: self
INTEGER(C_INT), DIMENSION(:), INTENT(IN), TARGET :: DATA
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_int_Sb__SB_(DATA, farg2)
CALL swigc_SetInt_insert__SWIG_1(farg1, farg2)
END SUBROUTINE

FUNCTION swigf_SetInt_difference(self, other) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(SetInt) :: swig_result
CLASS(SetInt), INTENT(IN) :: self
CLASS(SetInt), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
fresult = swigc_SetInt_difference(farg1, farg2)
swig_result%swigdata = fresult
END FUNCTION

FUNCTION swigf_SetInt_intersection(self, other) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(SetInt) :: swig_result
CLASS(SetInt), INTENT(IN) :: self
CLASS(SetInt), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
fresult = swigc_SetInt_intersection(farg1, farg2)
swig_result%swigdata = fresult
END FUNCTION

FUNCTION swigf_SetInt_symmetric_difference(self, other) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(SetInt) :: swig_result
CLASS(SetInt), INTENT(IN) :: self
CLASS(SetInt), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
fresult = swigc_SetInt_symmetric_difference(farg1, farg2)
swig_result%swigdata = fresult
END FUNCTION

FUNCTION swigf_SetInt_union(self, other) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(SetInt) :: swig_result
CLASS(SetInt), INTENT(IN) :: self
CLASS(SetInt), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
fresult = swigc_SetInt_union(farg1, farg2)
swig_result%swigdata = fresult
END FUNCTION

FUNCTION swigf_SetInt_includes(self, other) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
CLASS(SetInt), INTENT(IN) :: self
CLASS(SetInt), INTENT(IN) :: other
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
fresult = swigc_SetInt_includes(farg1, farg2)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

SUBROUTINE swigf_SetInt_release(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(SetInt), INTENT(INOUT) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
IF (BTEST(farg1%cmemflags, swig_cmem_own_bit)) THEN
CALL swigc_delete_SetInt(farg1)
END IF
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE swigf_SetInt_op_assign__(self, other)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(SetInt), INTENT(INOUT) :: self
TYPE(SetInt), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
CALL swigc_SetInt_op_assign__(farg1, farg2)
self%swigdata = farg1
END SUBROUTINE

FUNCTION swigf_new_SetString() &
RESULT(self)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(SetString) :: self
TYPE(SwigClassWrapper) :: fresult

fresult = swigc_new_SetString()
self%swigdata = fresult
END FUNCTION

FUNCTION swigf_SetString_empty(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
CLASS(SetString), INTENT(IN) :: self
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_SetString_empty(farg1)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

FUNCTION swigf_SetString_size(self) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(SetString), INTENT(IN) :: self
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
fresult = swigc_SetString_size(farg1)
swig_result = INT(fresult)
END FUNCTION

SUBROUTINE swigf_SetString_clear(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(SetString), INTENT(IN) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
CALL swigc_SetString_clear(farg1)
END SUBROUTINE


SUBROUTINE SWIGTM_fin_char_Sm_(finp, iminp, temp)
  USE, INTRINSIC :: ISO_C_BINDING
  CHARACTER(LEN=*), INTENT(IN) :: finp
  TYPE(SwigArrayWrapper), INTENT(OUT) :: iminp
  CHARACTER(KIND=C_CHAR), DIMENSION(:), TARGET, ALLOCATABLE, INTENT(OUT) :: temp
  INTEGER :: i

  ALLOCATE(CHARACTER(KIND=C_CHAR) :: temp(LEN(finp) + 1))
  DO i=1,LEN(finp)
    temp(i) = CHAR(ICHAR(finp(i:i)), KIND=C_CHAR)
  END DO
  i = LEN(finp) + 1
  temp(i) = C_NULL_CHAR ! C finp compatibility
  iminp%DATA = c_loc(temp)
  iminp%SIZE = LEN(finp, KIND=C_SIZE_T)
END SUBROUTINE

SUBROUTINE swigf_SetString_erase(self, x, swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(SetString), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: x
INTEGER, INTENT(OUT), OPTIONAL :: swig_result
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(x, farg2, farg2_temp)
fresult = swigc_SetString_erase(farg1, farg2)
IF (PRESENT(swig_result)) THEN
swig_result = INT(fresult)
END IF

END SUBROUTINE

FUNCTION swigf_SetString_count(self, x) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
INTEGER :: swig_result
CLASS(SetString), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: x
INTEGER(C_LONG) :: fresult
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(x, farg2, farg2_temp)
fresult = swigc_SetString_count(farg1, farg2)
swig_result = INT(fresult)
END FUNCTION

SUBROUTINE swigf_SetString_insert(self, x, swig_result)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(SetString), INTENT(IN) :: self
CHARACTER(LEN=*), TARGET :: x
LOGICAL, INTENT(OUT), OPTIONAL :: swig_result
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1
CHARACTER(KIND=C_CHAR), DIMENSION(:), ALLOCATABLE, TARGET :: farg2_temp
TYPE(SwigArrayWrapper) :: farg2

farg1 = self%swigdata
CALL SWIGTM_fin_char_Sm_(x, farg2, farg2_temp)
fresult = swigc_SetString_insert(farg1, farg2)
IF (PRESENT(swig_result)) THEN
CALL SWIGTM_fout_bool(fresult, swig_result)
END IF

END SUBROUTINE

SUBROUTINE swigf_SetString_insert_ref(self, str_class)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(SetString), INTENT(IN) :: self
CLASS(string), INTENT(IN) :: str_class
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = str_class%swigdata
CALL swigc_SetString_insert_ref(farg1, farg2)
END SUBROUTINE

FUNCTION swigf_SetString_difference(self, other) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(SetString) :: swig_result
CLASS(SetString), INTENT(IN) :: self
CLASS(SetString), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
fresult = swigc_SetString_difference(farg1, farg2)
swig_result%swigdata = fresult
END FUNCTION

FUNCTION swigf_SetString_intersection(self, other) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(SetString) :: swig_result
CLASS(SetString), INTENT(IN) :: self
CLASS(SetString), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
fresult = swigc_SetString_intersection(farg1, farg2)
swig_result%swigdata = fresult
END FUNCTION

FUNCTION swigf_SetString_symmetric_difference(self, other) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(SetString) :: swig_result
CLASS(SetString), INTENT(IN) :: self
CLASS(SetString), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
fresult = swigc_SetString_symmetric_difference(farg1, farg2)
swig_result%swigdata = fresult
END FUNCTION

FUNCTION swigf_SetString_union(self, other) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
TYPE(SetString) :: swig_result
CLASS(SetString), INTENT(IN) :: self
CLASS(SetString), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: fresult
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
fresult = swigc_SetString_union(farg1, farg2)
swig_result%swigdata = fresult
END FUNCTION

FUNCTION swigf_SetString_includes(self, other) &
RESULT(swig_result)
USE, INTRINSIC :: ISO_C_BINDING
LOGICAL :: swig_result
CLASS(SetString), INTENT(IN) :: self
CLASS(SetString), INTENT(IN) :: other
INTEGER(C_INT) :: fresult
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
fresult = swigc_SetString_includes(farg1, farg2)
CALL SWIGTM_fout_bool(fresult, swig_result)
END FUNCTION

SUBROUTINE swigf_SetString_release(self)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(SetString), INTENT(INOUT) :: self
TYPE(SwigClassWrapper) :: farg1

farg1 = self%swigdata
IF (BTEST(farg1%cmemflags, swig_cmem_own_bit)) THEN
CALL swigc_delete_SetString(farg1)
END IF
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
END SUBROUTINE

SUBROUTINE swigf_SetString_op_assign__(self, other)
USE, INTRINSIC :: ISO_C_BINDING
CLASS(SetString), INTENT(INOUT) :: self
TYPE(SetString), INTENT(IN) :: other
TYPE(SwigClassWrapper) :: farg1
TYPE(SwigClassWrapper) :: farg2

farg1 = self%swigdata
farg2 = other%swigdata
CALL swigc_SetString_op_assign__(farg1, farg2)
self%swigdata = farg1
END SUBROUTINE


END MODULE
