
 MODULE ModLib_FMZM_3
    USE ModLib_FMZM_1

    INTERFACE OPERATOR (/=)
       MODULE PROCEDURE FMLNE_IFM
       MODULE PROCEDURE FMLNE_IIM
       MODULE PROCEDURE FMLNE_IZM
       MODULE PROCEDURE FMLNE_RFM
       MODULE PROCEDURE FMLNE_RIM
       MODULE PROCEDURE FMLNE_RZM
       MODULE PROCEDURE FMLNE_DFM
       MODULE PROCEDURE FMLNE_DIM
       MODULE PROCEDURE FMLNE_DZM
       MODULE PROCEDURE FMLNE_ZFM
       MODULE PROCEDURE FMLNE_ZIM
       MODULE PROCEDURE FMLNE_ZZM
       MODULE PROCEDURE FMLNE_CFM
       MODULE PROCEDURE FMLNE_CIM
       MODULE PROCEDURE FMLNE_CZM
       MODULE PROCEDURE FMLNE_FMI
       MODULE PROCEDURE FMLNE_FMR
       MODULE PROCEDURE FMLNE_FMD
       MODULE PROCEDURE FMLNE_FMZ
       MODULE PROCEDURE FMLNE_FMC
       MODULE PROCEDURE FMLNE_FMFM
       MODULE PROCEDURE FMLNE_FMIM
       MODULE PROCEDURE FMLNE_FMZM
       MODULE PROCEDURE FMLNE_IMI
       MODULE PROCEDURE FMLNE_IMR
       MODULE PROCEDURE FMLNE_IMD
       MODULE PROCEDURE FMLNE_IMZ
       MODULE PROCEDURE FMLNE_IMC
       MODULE PROCEDURE FMLNE_IMFM
       MODULE PROCEDURE FMLNE_IMIM
       MODULE PROCEDURE FMLNE_IMZM
       MODULE PROCEDURE FMLNE_ZMI
       MODULE PROCEDURE FMLNE_ZMR
       MODULE PROCEDURE FMLNE_ZMD
       MODULE PROCEDURE FMLNE_ZMZ
       MODULE PROCEDURE FMLNE_ZMC
       MODULE PROCEDURE FMLNE_ZMFM
       MODULE PROCEDURE FMLNE_ZMIM
       MODULE PROCEDURE FMLNE_ZMZM
    END INTERFACE

    INTERFACE OPERATOR (>)
       MODULE PROCEDURE FMLGT_IFM
       MODULE PROCEDURE FMLGT_IIM
       MODULE PROCEDURE FMLGT_RFM
       MODULE PROCEDURE FMLGT_RIM
       MODULE PROCEDURE FMLGT_DFM
       MODULE PROCEDURE FMLGT_DIM
       MODULE PROCEDURE FMLGT_FMI
       MODULE PROCEDURE FMLGT_FMR
       MODULE PROCEDURE FMLGT_FMD
       MODULE PROCEDURE FMLGT_FMFM
       MODULE PROCEDURE FMLGT_FMIM
       MODULE PROCEDURE FMLGT_IMI
       MODULE PROCEDURE FMLGT_IMR
       MODULE PROCEDURE FMLGT_IMD
       MODULE PROCEDURE FMLGT_IMFM
       MODULE PROCEDURE FMLGT_IMIM
    END INTERFACE

    INTERFACE OPERATOR (>=)
       MODULE PROCEDURE FMLGE_IFM
       MODULE PROCEDURE FMLGE_IIM
       MODULE PROCEDURE FMLGE_RFM
       MODULE PROCEDURE FMLGE_RIM
       MODULE PROCEDURE FMLGE_DFM
       MODULE PROCEDURE FMLGE_DIM
       MODULE PROCEDURE FMLGE_FMI
       MODULE PROCEDURE FMLGE_FMR
       MODULE PROCEDURE FMLGE_FMD
       MODULE PROCEDURE FMLGE_FMFM
       MODULE PROCEDURE FMLGE_FMIM
       MODULE PROCEDURE FMLGE_IMI
       MODULE PROCEDURE FMLGE_IMR
       MODULE PROCEDURE FMLGE_IMD
       MODULE PROCEDURE FMLGE_IMFM
       MODULE PROCEDURE FMLGE_IMIM
    END INTERFACE

    INTERFACE OPERATOR (<)
       MODULE PROCEDURE FMLLT_IFM
       MODULE PROCEDURE FMLLT_IIM
       MODULE PROCEDURE FMLLT_RFM
       MODULE PROCEDURE FMLLT_RIM
       MODULE PROCEDURE FMLLT_DFM
       MODULE PROCEDURE FMLLT_DIM
       MODULE PROCEDURE FMLLT_FMI
       MODULE PROCEDURE FMLLT_FMR
       MODULE PROCEDURE FMLLT_FMD
       MODULE PROCEDURE FMLLT_FMFM
       MODULE PROCEDURE FMLLT_FMIM
       MODULE PROCEDURE FMLLT_IMI
       MODULE PROCEDURE FMLLT_IMR
       MODULE PROCEDURE FMLLT_IMD
       MODULE PROCEDURE FMLLT_IMFM
       MODULE PROCEDURE FMLLT_IMIM
    END INTERFACE

    INTERFACE OPERATOR (<=)
       MODULE PROCEDURE FMLLE_IFM
       MODULE PROCEDURE FMLLE_IIM
       MODULE PROCEDURE FMLLE_RFM
       MODULE PROCEDURE FMLLE_RIM
       MODULE PROCEDURE FMLLE_DFM
       MODULE PROCEDURE FMLLE_DIM
       MODULE PROCEDURE FMLLE_FMI
       MODULE PROCEDURE FMLLE_FMR
       MODULE PROCEDURE FMLLE_FMD
       MODULE PROCEDURE FMLLE_FMFM
       MODULE PROCEDURE FMLLE_FMIM
       MODULE PROCEDURE FMLLE_IMI
       MODULE PROCEDURE FMLLE_IMR
       MODULE PROCEDURE FMLLE_IMD
       MODULE PROCEDURE FMLLE_IMFM
       MODULE PROCEDURE FMLLE_IMIM
    END INTERFACE

 CONTAINS

!                                                                  /=

   FUNCTION FMLNE_IFM(IVAL,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMI2M(IVAL,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'NE',MA%MFM)
   END FUNCTION FMLNE_IFM

   FUNCTION FMLNE_IIM(IVAL,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL,MA
      TYPE(MULTI), SAVE :: MTLVIM
      CALL FM_UNDEF_INP(MA)
      CALL IMI2M(IVAL,MTLVIM)
      RETURN_VALUE = IMCOMP(MTLVIM,'NE',MA%MIM)
   END FUNCTION FMLNE_IIM

   FUNCTION FMLNE_IZM(IVAL,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (ZM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMI2M(IVAL,MTLVFM)
      CALL ZMREAL(MA%MZM,MULVFM)
      L1 = FMCOMP(MTLVFM,'NE',MULVFM)
      CALL FMI2M(0,MTLVFM)
      CALL ZMIMAG(MA%MZM,MULVFM)
      L2 = FMCOMP(MTLVFM,'NE',MULVFM)
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_IZM

   FUNCTION FMLNE_RFM(R,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      REAL :: R
      INTENT (IN) :: R,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(R,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'NE',MA%MFM)
   END FUNCTION FMLNE_RFM

   FUNCTION FMLNE_RIM(R,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      REAL :: R
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: R,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMSP2M(R,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'NE',MULVFM)
      NDIG = NDSAVE
   END FUNCTION FMLNE_RIM

   FUNCTION FMLNE_RZM(R,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (ZM) :: MA
      REAL :: R
      INTENT (IN) :: R,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(R,MTLVFM)
      CALL ZMREAL(MA%MZM,MULVFM)
      L1 = FMCOMP(MTLVFM,'NE',MULVFM)
      CALL FMI2M(0,MTLVFM)
      CALL ZMIMAG(MA%MZM,MULVFM)
      L2 = FMCOMP(MTLVFM,'NE',MULVFM)
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_RZM

   FUNCTION FMLNE_DFM(D,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      DOUBLE PRECISION :: D
      INTENT (IN) :: D,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(D,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'NE',MA%MFM)
   END FUNCTION FMLNE_DFM

   FUNCTION FMLNE_DIM(D,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      DOUBLE PRECISION :: D
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: D,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMDP2M(D,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'NE',MULVFM)
      NDIG = NDSAVE
   END FUNCTION FMLNE_DIM

   FUNCTION FMLNE_DZM(D,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (ZM) :: MA
      DOUBLE PRECISION :: D
      INTENT (IN) :: D,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(D,MTLVFM)
      CALL ZMREAL(MA%MZM,MULVFM)
      L1 = FMCOMP(MTLVFM,'NE',MULVFM)
      CALL FMI2M(0,MTLVFM)
      CALL ZMIMAG(MA%MZM,MULVFM)
      L2 = FMCOMP(MTLVFM,'NE',MULVFM)
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_DZM

   FUNCTION FMLNE_ZFM(Z,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      COMPLEX :: Z
      INTENT (IN) :: Z,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(REAL(Z),MTLVFM)
      L1 = FMCOMP(MTLVFM,'NE',MA%MFM)
      L2 = .FALSE.
      IF (AIMAG(Z) /= 0.0) L2 = .TRUE.
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_ZFM

   FUNCTION FMLNE_ZIM(Z,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      INTEGER :: KA,NDSAVE
      COMPLEX :: Z
      INTENT (IN) :: Z,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMSP2M(REAL(Z),MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      L1 = FMCOMP(MTLVFM,'NE',MULVFM)
      NDIG = NDSAVE
      L2 = .FALSE.
      IF (AIMAG(Z) /= 0.0) L2 = .TRUE.
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_ZIM

   FUNCTION FMLNE_ZZM(Z,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (ZM) :: MA
      COMPLEX :: Z
      INTENT (IN) :: Z,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM,MTLVZM(2)
      CALL FM_UNDEF_INP(MA)
      CALL ZMZ2M(Z,MTLVZM)
      CALL ZMREAL(MTLVZM,MTLVFM)
      CALL ZMREAL(MA%MZM,MULVFM)
      L1 = FMCOMP(MTLVFM,'NE',MULVFM)
      CALL ZMIMAG(MTLVZM,MTLVFM)
      CALL ZMIMAG(MA%MZM,MULVFM)
      L2 = FMCOMP(MTLVFM,'NE',MULVFM)
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_ZZM

   FUNCTION FMLNE_CFM(C,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      COMPLEX (KIND(0.0D0)) :: C
      INTENT (IN) :: C,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(REAL(C,KIND(0.0D0)),MTLVFM)
      L1 = FMCOMP(MTLVFM,'NE',MA%MFM)
      L2 = .FALSE.
      IF (AIMAG(C) /= 0.0) L2 = .TRUE.
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_CFM

   FUNCTION FMLNE_CIM(C,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      COMPLEX (KIND(0.0D0)) :: C
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: C,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMDP2M(REAL(C,KIND(0.0D0)),MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      L1 = FMCOMP(MTLVFM,'NE',MULVFM)
      NDIG = NDSAVE
      L2 = .FALSE.
      IF (AIMAG(C) /= 0.0) L2 = .TRUE.
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_CIM

   FUNCTION FMLNE_CZM(C,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (ZM) :: MA
      COMPLEX (KIND(0.0D0)) :: C
      INTENT (IN) :: C,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(REAL(C,KIND(0.0D0)),MTLVFM)
      CALL ZMREAL(MA%MZM,MULVFM)
      L1 = FMCOMP(MTLVFM,'NE',MULVFM)
      CALL FMDP2M(AIMAG(C),MTLVFM)
      CALL ZMIMAG(MA%MZM,MULVFM)
      L2 = FMCOMP(MTLVFM,'NE',MULVFM)
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_CZM

   FUNCTION FMLNE_FMI(MA,IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: MA,IVAL
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMI2M(IVAL,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'NE',MTLVFM)
   END FUNCTION FMLNE_FMI

   FUNCTION FMLNE_FMR(MA,R)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      REAL :: R
      INTENT (IN) :: MA,R
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(R,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'NE',MTLVFM)
   END FUNCTION FMLNE_FMR

   FUNCTION FMLNE_FMD(MA,D)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      DOUBLE PRECISION :: D
      INTENT (IN) :: MA,D
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(D,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'NE',MTLVFM)
   END FUNCTION FMLNE_FMD

   FUNCTION FMLNE_FMZ(MA,Z)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      COMPLEX :: Z
      INTENT (IN) :: MA,Z
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(REAL(Z),MTLVFM)
      L1 = FMCOMP(MA%MFM,'NE',MTLVFM)
      L2 = .FALSE.
      IF (AIMAG(Z) /= 0.0) L2 = .TRUE.
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_FMZ

   FUNCTION FMLNE_FMC(MA,C)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      COMPLEX (KIND(0.0D0)) :: C
      INTENT (IN) :: MA,C
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(REAL(C,KIND(0.0D0)),MTLVFM)
      L1 = FMCOMP(MA%MFM,'NE',MTLVFM)
      L2 = .FALSE.
      IF (AIMAG(C) /= 0.0) L2 = .TRUE.
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_FMC

   FUNCTION FMLNE_FMFM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = FMCOMP(MA%MFM,'NE',MB%MFM)
   END FUNCTION FMLNE_FMFM

   FUNCTION FMLNE_FMIM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      TYPE (IM) :: MB
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMINT(MA%MFM,MTLVFM)
      IF (FMCOMP(MA%MFM,'EQ',MTLVFM)) THEN
          CALL IMI2FM(MB%MIM,MTLVFM)
          RETURN_VALUE = FMCOMP(MA%MFM,'NE',MTLVFM)
      ELSE
          RETURN_VALUE = .TRUE.
      ENDIF
   END FUNCTION FMLNE_FMIM

   FUNCTION FMLNE_FMZM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      TYPE (ZM) :: MB
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL ZMREAL(MB%MZM,MTLVFM)
      L1 = FMCOMP(MA%MFM,'NE',MTLVFM)
      L2 = .FALSE.
      IF (MB%MZM(2)%MP(3) /= 0) L2 = .TRUE.
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_FMZM

   FUNCTION FMLNE_IMI(MA,IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: MA,IVAL
      TYPE(MULTI), SAVE :: MTLVIM
      CALL FM_UNDEF_INP(MA)
      CALL IMI2M(IVAL,MTLVIM)
      RETURN_VALUE = IMCOMP(MA%MIM,'NE',MTLVIM)
   END FUNCTION FMLNE_IMI

   FUNCTION FMLNE_IMR(MA,R)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      INTEGER :: KA,NDSAVE
      REAL :: R
      INTENT (IN) :: MA,R
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMSP2M(R,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MULVFM,'NE',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLNE_IMR

   FUNCTION FMLNE_IMD(MA,D)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      DOUBLE PRECISION :: D
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,D
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMDP2M(D,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MULVFM,'NE',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLNE_IMD

   FUNCTION FMLNE_IMZ(MA,Z)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      INTEGER :: KA,NDSAVE
      COMPLEX :: Z
      INTENT (IN) :: MA,Z
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMSP2M(REAL(Z),MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      L1 = FMCOMP(MULVFM,'NE',MTLVFM)
      NDIG = NDSAVE
      L2 = .FALSE.
      IF (AIMAG(Z) /= 0.0) L2 = .TRUE.
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_IMZ

   FUNCTION FMLNE_IMC(MA,C)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      COMPLEX (KIND(0.0D0)) :: C
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,C
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMDP2M(REAL(C,KIND(0.0D0)),MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      L1 = FMCOMP(MULVFM,'NE',MTLVFM)
      NDIG = NDSAVE
      L2 = .FALSE.
      IF (AIMAG(C) /= 0.0) L2 = .TRUE.
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_IMC

   FUNCTION FMLNE_IMFM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      TYPE (FM) :: MB
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMINT(MB%MFM,MTLVFM)
      IF (FMCOMP(MB%MFM,'EQ',MTLVFM)) THEN
          CALL IMI2FM(MA%MIM,MTLVFM)
          RETURN_VALUE = FMCOMP(MB%MFM,'NE',MTLVFM)
      ELSE
          RETURN_VALUE = .TRUE.
      ENDIF
   END FUNCTION FMLNE_IMFM

   FUNCTION FMLNE_IMIM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA,MB
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = IMCOMP(MA%MIM,'NE',MB%MIM)
   END FUNCTION FMLNE_IMIM

   FUNCTION FMLNE_IMZM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      TYPE (ZM) :: MB
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL ZMREAL(MB%MZM,MTLVFM)
      CALL FMINT(MTLVFM,MULVFM)
      IF (FMCOMP(MULVFM,'EQ',MTLVFM).AND.MB%MZM(2)%MP(3) == 0) THEN
          CALL IMI2FM(MA%MIM,MULVFM)
          RETURN_VALUE = FMCOMP(MULVFM,'NE',MTLVFM)
      ELSE
          RETURN_VALUE = .TRUE.
      ENDIF
   END FUNCTION FMLNE_IMZM

   FUNCTION FMLNE_ZMI(MA,IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (ZM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: MA,IVAL
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      CALL ZMREAL(MA%MZM,MTLVFM)
      CALL FMINT(MTLVFM,MULVFM)
      IF (FMCOMP(MULVFM,'EQ',MTLVFM).AND.MA%MZM(2)%MP(3) == 0) THEN
          CALL FMI2M(IVAL,MULVFM)
          RETURN_VALUE = FMCOMP(MTLVFM,'NE',MULVFM)
      ELSE
          RETURN_VALUE = .TRUE.
      ENDIF
   END FUNCTION FMLNE_ZMI

   FUNCTION FMLNE_ZMR(MA,R)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (ZM) :: MA
      REAL :: R
      INTENT (IN) :: MA,R
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(R,MTLVFM)
      CALL ZMREAL(MA%MZM,MULVFM)
      L1 = FMCOMP(MTLVFM,'NE',MULVFM)
      CALL FMI2M(0,MTLVFM)
      CALL ZMIMAG(MA%MZM,MULVFM)
      L2 = FMCOMP(MTLVFM,'NE',MULVFM)
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_ZMR

   FUNCTION FMLNE_ZMD(MA,D)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (ZM) :: MA
      DOUBLE PRECISION :: D
      INTENT (IN) :: MA,D
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(D,MTLVFM)
      CALL ZMREAL(MA%MZM,MULVFM)
      L1 = FMCOMP(MTLVFM,'NE',MULVFM)
      CALL FMI2M(0,MTLVFM)
      CALL ZMIMAG(MA%MZM,MULVFM)
      L2 = FMCOMP(MTLVFM,'NE',MULVFM)
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_ZMD

   FUNCTION FMLNE_ZMZ(MA,Z)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (ZM) :: MA
      COMPLEX :: Z
      INTENT (IN) :: MA,Z
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM,MTLVZM(2)
      CALL FM_UNDEF_INP(MA)
      CALL ZMZ2M(Z,MTLVZM)
      CALL ZMREAL(MTLVZM,MTLVFM)
      CALL ZMREAL(MA%MZM,MULVFM)
      L1 = FMCOMP(MTLVFM,'NE',MULVFM)
      CALL ZMIMAG(MTLVZM,MTLVFM)
      CALL ZMIMAG(MA%MZM,MULVFM)
      L2 = FMCOMP(MTLVFM,'NE',MULVFM)
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_ZMZ

   FUNCTION FMLNE_ZMC(MA,C)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (ZM) :: MA
      COMPLEX (KIND(0.0D0)) :: C
      INTENT (IN) :: MA,C
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(REAL(C,KIND(0.0D0)),MTLVFM)
      CALL ZMREAL(MA%MZM,MULVFM)
      L1 = FMCOMP(MTLVFM,'NE',MULVFM)
      CALL FMDP2M(AIMAG(C),MTLVFM)
      CALL ZMIMAG(MA%MZM,MULVFM)
      L2 = FMCOMP(MTLVFM,'NE',MULVFM)
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_ZMC

   FUNCTION FMLNE_ZMFM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MB
      TYPE (ZM) :: MA
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL ZMREAL(MA%MZM,MTLVFM)
      L1 = FMCOMP(MB%MFM,'NE',MTLVFM)
      L2 = .FALSE.
      IF (MA%MZM(2)%MP(3) /= 0) L2 = .TRUE.
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_ZMFM

   FUNCTION FMLNE_ZMIM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MB
      TYPE (ZM) :: MA
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL ZMREAL(MA%MZM,MTLVFM)
      CALL FMINT(MTLVFM,MULVFM)
      IF (FMCOMP(MULVFM,'EQ',MTLVFM).AND.MA%MZM(2)%MP(3) == 0) THEN
          CALL IMI2FM(MB%MIM,MULVFM)
          RETURN_VALUE = FMCOMP(MULVFM,'NE',MTLVFM)
      ELSE
          RETURN_VALUE = .TRUE.
      ENDIF
   END FUNCTION FMLNE_ZMIM

   FUNCTION FMLNE_ZMZM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE,L1,L2
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL ZMREAL(MA%MZM,MTLVFM)
      CALL ZMREAL(MB%MZM,MULVFM)
      L1 = FMCOMP(MTLVFM,'NE',MULVFM)
      CALL ZMIMAG(MA%MZM,MTLVFM)
      CALL ZMIMAG(MB%MZM,MULVFM)
      L2 = FMCOMP(MTLVFM,'NE',MULVFM)
      RETURN_VALUE = L1.OR.L2
   END FUNCTION FMLNE_ZMZM

!                                                                   >

   FUNCTION FMLGT_IFM(IVAL,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMI2M(IVAL,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'GT',MA%MFM)
   END FUNCTION FMLGT_IFM

   FUNCTION FMLGT_IIM(IVAL,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL,MA
      TYPE(MULTI), SAVE :: MTLVIM
      CALL FM_UNDEF_INP(MA)
      CALL IMI2M(IVAL,MTLVIM)
      RETURN_VALUE = IMCOMP(MTLVIM,'GT',MA%MIM)
   END FUNCTION FMLGT_IIM

   FUNCTION FMLGT_RFM(R,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      REAL :: R
      INTENT (IN) :: R,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(R,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'GT',MA%MFM)
   END FUNCTION FMLGT_RFM

   FUNCTION FMLGT_RIM(R,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      INTEGER :: KA,NDSAVE
      REAL :: R
      INTENT (IN) :: R,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMSP2M(R,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'GT',MULVFM)
      NDIG = NDSAVE
   END FUNCTION FMLGT_RIM

   FUNCTION FMLGT_DFM(D,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      DOUBLE PRECISION :: D
      INTENT (IN) :: D,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(D,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'GT',MA%MFM)
   END FUNCTION FMLGT_DFM

   FUNCTION FMLGT_DIM(D,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      DOUBLE PRECISION :: D
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: D,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMDP2M(D,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'GT',MULVFM)
      NDIG = NDSAVE
   END FUNCTION FMLGT_DIM

   FUNCTION FMLGT_FMI(MA,IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: MA,IVAL
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMI2M(IVAL,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'GT',MTLVFM)
   END FUNCTION FMLGT_FMI

   FUNCTION FMLGT_FMR(MA,R)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      REAL :: R
      INTENT (IN) :: MA,R
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(R,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'GT',MTLVFM)
   END FUNCTION FMLGT_FMR

   FUNCTION FMLGT_FMD(MA,D)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      DOUBLE PRECISION :: D
      INTENT (IN) :: MA,D
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(D,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'GT',MTLVFM)
   END FUNCTION FMLGT_FMD

   FUNCTION FMLGT_FMFM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = FMCOMP(MA%MFM,'GT',MB%MFM)
   END FUNCTION FMLGT_FMFM

   FUNCTION FMLGT_FMIM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      TYPE (IM) :: MB
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      NDSAVE = NDIG
      KA = MB%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL IMI2FM(MB%MIM,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'GT',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLGT_FMIM

   FUNCTION FMLGT_IMI(MA,IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: MA,IVAL
      TYPE(MULTI), SAVE :: MTLVIM
      CALL FM_UNDEF_INP(MA)
      CALL IMI2M(IVAL,MTLVIM)
      RETURN_VALUE = IMCOMP(MA%MIM,'GT',MTLVIM)
   END FUNCTION FMLGT_IMI

   FUNCTION FMLGT_IMR(MA,R)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      INTEGER :: KA,NDSAVE
      REAL :: R
      INTENT (IN) :: MA,R
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMSP2M(R,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MULVFM,'GT',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLGT_IMR

   FUNCTION FMLGT_IMD(MA,D)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      DOUBLE PRECISION :: D
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,D
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMDP2M(D,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MULVFM,'GT',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLGT_IMD

   FUNCTION FMLGT_IMFM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      TYPE (FM) :: MB
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL IMI2FM(MA%MIM,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'GT',MB%MFM)
      NDIG = NDSAVE
   END FUNCTION FMLGT_IMFM

   FUNCTION FMLGT_IMIM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA,MB
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = IMCOMP(MA%MIM,'GT',MB%MIM)
   END FUNCTION FMLGT_IMIM

!                                                                  >=

   FUNCTION FMLGE_IFM(IVAL,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMI2M(IVAL,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'GE',MA%MFM)
   END FUNCTION FMLGE_IFM

   FUNCTION FMLGE_IIM(IVAL,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL,MA
      TYPE(MULTI), SAVE :: MTLVIM
      CALL FM_UNDEF_INP(MA)
      CALL IMI2M(IVAL,MTLVIM)
      RETURN_VALUE = IMCOMP(MTLVIM,'GE',MA%MIM)
   END FUNCTION FMLGE_IIM

   FUNCTION FMLGE_RFM(R,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      REAL :: R
      INTENT (IN) :: R,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(R,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'GE',MA%MFM)
   END FUNCTION FMLGE_RFM

   FUNCTION FMLGE_RIM(R,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      INTEGER :: KA,NDSAVE
      REAL :: R
      INTENT (IN) :: R,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMSP2M(R,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'GE',MULVFM)
      NDIG = NDSAVE
   END FUNCTION FMLGE_RIM

   FUNCTION FMLGE_DFM(D,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      DOUBLE PRECISION :: D
      INTENT (IN) :: D,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(D,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'GE',MA%MFM)
   END FUNCTION FMLGE_DFM

   FUNCTION FMLGE_DIM(D,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      DOUBLE PRECISION :: D
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: D,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMDP2M(D,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'GE',MULVFM)
      NDIG = NDSAVE
   END FUNCTION FMLGE_DIM

   FUNCTION FMLGE_FMI(MA,IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: MA,IVAL
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMI2M(IVAL,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'GE',MTLVFM)
   END FUNCTION FMLGE_FMI

   FUNCTION FMLGE_FMR(MA,R)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      REAL :: R
      INTENT (IN) :: MA,R
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(R,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'GE',MTLVFM)
   END FUNCTION FMLGE_FMR

   FUNCTION FMLGE_FMD(MA,D)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      DOUBLE PRECISION :: D
      INTENT (IN) :: MA,D
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(D,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'GE',MTLVFM)
   END FUNCTION FMLGE_FMD

   FUNCTION FMLGE_FMFM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = FMCOMP(MA%MFM,'GE',MB%MFM)
   END FUNCTION FMLGE_FMFM

   FUNCTION FMLGE_FMIM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      TYPE (IM) :: MB
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      NDSAVE = NDIG
      KA = MB%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL IMI2FM(MB%MIM,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'GE',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLGE_FMIM

   FUNCTION FMLGE_IMI(MA,IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: MA,IVAL
      TYPE(MULTI), SAVE :: MTLVIM
      CALL FM_UNDEF_INP(MA)
      CALL IMI2M(IVAL,MTLVIM)
      RETURN_VALUE = IMCOMP(MA%MIM,'GE',MTLVIM)
   END FUNCTION FMLGE_IMI

   FUNCTION FMLGE_IMR(MA,R)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      INTEGER :: KA,NDSAVE
      REAL :: R
      INTENT (IN) :: MA,R
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMSP2M(R,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MULVFM,'GE',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLGE_IMR

   FUNCTION FMLGE_IMD(MA,D)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      DOUBLE PRECISION :: D
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,D
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMDP2M(D,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MULVFM,'GE',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLGE_IMD

   FUNCTION FMLGE_IMFM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      TYPE (FM) :: MB
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL IMI2FM(MA%MIM,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'GE',MB%MFM)
      NDIG = NDSAVE
   END FUNCTION FMLGE_IMFM

   FUNCTION FMLGE_IMIM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA,MB
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = IMCOMP(MA%MIM,'GE',MB%MIM)
   END FUNCTION FMLGE_IMIM

!                                                                   <

   FUNCTION FMLLT_IFM(IVAL,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMI2M(IVAL,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'LT',MA%MFM)
   END FUNCTION FMLLT_IFM

   FUNCTION FMLLT_IIM(IVAL,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL,MA
      TYPE(MULTI), SAVE :: MTLVIM
      CALL FM_UNDEF_INP(MA)
      CALL IMI2M(IVAL,MTLVIM)
      RETURN_VALUE = IMCOMP(MTLVIM,'LT',MA%MIM)
   END FUNCTION FMLLT_IIM

   FUNCTION FMLLT_RFM(R,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      REAL :: R
      INTENT (IN) :: R,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(R,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'LT',MA%MFM)
   END FUNCTION FMLLT_RFM

   FUNCTION FMLLT_RIM(R,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      INTEGER :: KA,NDSAVE
      REAL :: R
      INTENT (IN) :: R,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMSP2M(R,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'LT',MULVFM)
      NDIG = NDSAVE
   END FUNCTION FMLLT_RIM

   FUNCTION FMLLT_DFM(D,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      DOUBLE PRECISION :: D
      INTENT (IN) :: D,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(D,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'LT',MA%MFM)
   END FUNCTION FMLLT_DFM

   FUNCTION FMLLT_DIM(D,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      DOUBLE PRECISION :: D
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: D,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMDP2M(D,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'LT',MULVFM)
      NDIG = NDSAVE
   END FUNCTION FMLLT_DIM

   FUNCTION FMLLT_FMI(MA,IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: MA,IVAL
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMI2M(IVAL,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'LT',MTLVFM)
   END FUNCTION FMLLT_FMI

   FUNCTION FMLLT_FMR(MA,R)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      REAL :: R
      INTENT (IN) :: MA,R
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(R,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'LT',MTLVFM)
   END FUNCTION FMLLT_FMR

   FUNCTION FMLLT_FMD(MA,D)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      DOUBLE PRECISION :: D
      INTENT (IN) :: MA,D
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(D,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'LT',MTLVFM)
   END FUNCTION FMLLT_FMD

   FUNCTION FMLLT_FMFM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = FMCOMP(MA%MFM,'LT',MB%MFM)
   END FUNCTION FMLLT_FMFM

   FUNCTION FMLLT_FMIM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      TYPE (IM) :: MB
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      NDSAVE = NDIG
      KA = MB%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL IMI2FM(MB%MIM,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'LT',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLLT_FMIM

   FUNCTION FMLLT_IMI(MA,IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: MA,IVAL
      TYPE(MULTI), SAVE :: MTLVIM
      CALL FM_UNDEF_INP(MA)
      CALL IMI2M(IVAL,MTLVIM)
      RETURN_VALUE = IMCOMP(MA%MIM,'LT',MTLVIM)
   END FUNCTION FMLLT_IMI

   FUNCTION FMLLT_IMR(MA,R)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      INTEGER :: KA,NDSAVE
      REAL :: R
      INTENT (IN) :: MA,R
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMSP2M(R,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MULVFM,'LT',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLLT_IMR

   FUNCTION FMLLT_IMD(MA,D)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      DOUBLE PRECISION :: D
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,D
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMDP2M(D,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MULVFM,'LT',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLLT_IMD

   FUNCTION FMLLT_IMFM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      TYPE (FM) :: MB
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL IMI2FM(MA%MIM,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'LT',MB%MFM)
      NDIG = NDSAVE
   END FUNCTION FMLLT_IMFM

   FUNCTION FMLLT_IMIM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA,MB
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = IMCOMP(MA%MIM,'LT',MB%MIM)
   END FUNCTION FMLLT_IMIM

!                                                                  <=

   FUNCTION FMLLE_IFM(IVAL,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMI2M(IVAL,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'LE',MA%MFM)
   END FUNCTION FMLLE_IFM

   FUNCTION FMLLE_IIM(IVAL,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL,MA
      TYPE(MULTI), SAVE :: MTLVIM
      CALL FM_UNDEF_INP(MA)
      CALL IMI2M(IVAL,MTLVIM)
      RETURN_VALUE = IMCOMP(MTLVIM,'LE',MA%MIM)
   END FUNCTION FMLLE_IIM

   FUNCTION FMLLE_RFM(R,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      REAL :: R
      INTENT (IN) :: R,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(R,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'LE',MA%MFM)
   END FUNCTION FMLLE_RFM

   FUNCTION FMLLE_RIM(R,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      INTEGER :: KA,NDSAVE
      REAL :: R
      INTENT (IN) :: R,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMSP2M(R,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'LE',MULVFM)
      NDIG = NDSAVE
   END FUNCTION FMLLE_RIM

   FUNCTION FMLLE_DFM(D,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      DOUBLE PRECISION :: D
      INTENT (IN) :: D,MA
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(D,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'LE',MA%MFM)
   END FUNCTION FMLLE_DFM

   FUNCTION FMLLE_DIM(D,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      DOUBLE PRECISION :: D
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: D,MA
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMDP2M(D,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'LE',MULVFM)
      NDIG = NDSAVE
   END FUNCTION FMLLE_DIM

   FUNCTION FMLLE_FMI(MA,IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: MA,IVAL
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMI2M(IVAL,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'LE',MTLVFM)
   END FUNCTION FMLLE_FMI

   FUNCTION FMLLE_FMR(MA,R)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      REAL :: R
      INTENT (IN) :: MA,R
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMSP2M(R,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'LE',MTLVFM)
   END FUNCTION FMLLE_FMR

   FUNCTION FMLLE_FMD(MA,D)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      DOUBLE PRECISION :: D
      INTENT (IN) :: MA,D
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMDP2M(D,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'LE',MTLVFM)
   END FUNCTION FMLLE_FMD

   FUNCTION FMLLE_FMFM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = FMCOMP(MA%MFM,'LE',MB%MFM)
   END FUNCTION FMLLE_FMFM

   FUNCTION FMLLE_FMIM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA
      TYPE (IM) :: MB
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      NDSAVE = NDIG
      KA = MB%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL IMI2FM(MB%MIM,MTLVFM)
      RETURN_VALUE = FMCOMP(MA%MFM,'LE',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLLE_FMIM

   FUNCTION FMLLE_IMI(MA,IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: MA,IVAL
      TYPE(MULTI), SAVE :: MTLVIM
      CALL FM_UNDEF_INP(MA)
      CALL IMI2M(IVAL,MTLVIM)
      RETURN_VALUE = IMCOMP(MA%MIM,'LE',MTLVIM)
   END FUNCTION FMLLE_IMI

   FUNCTION FMLLE_IMR(MA,R)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      INTEGER :: KA,NDSAVE
      REAL :: R
      INTENT (IN) :: MA,R
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMSP2M(R,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MULVFM,'LE',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLLE_IMR

   FUNCTION FMLLE_IMD(MA,D)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      DOUBLE PRECISION :: D
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,D
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL FMDP2M(D,MTLVFM)
      CALL IMI2FM(MA%MIM,MULVFM)
      RETURN_VALUE = FMCOMP(MULVFM,'LE',MTLVFM)
      NDIG = NDSAVE
   END FUNCTION FMLLE_IMD

   FUNCTION FMLLE_IMFM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (IM) :: MA
      TYPE (FM) :: MB
      INTEGER :: KA,NDSAVE
      INTENT (IN) :: MA,MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      NDSAVE = NDIG
      KA = MA%MIM%MP(2)
      NDIG = MAX(KA+NGRD52,NDIG)
      CALL IMI2FM(MA%MIM,MTLVFM)
      RETURN_VALUE = FMCOMP(MTLVFM,'LE',MB%MFM)
      NDIG = NDSAVE
   END FUNCTION FMLLE_IMFM

   FUNCTION FMLLE_IMIM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA,MB
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = IMCOMP(MA%MIM,'LE',MB%MIM)
   END FUNCTION FMLLE_IMIM

 END MODULE ModLib_FMZM_3
