
 MODULE ModLib_FMZM_10
   USE ModLib_FMZM_1

   CONTAINS

! Interface routines for calling with the FM, IM, and ZM derived types.

   SUBROUTINE FM_ABS(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMABS(MA%MFM,MB%MFM)
   END SUBROUTINE FM_ABS

   SUBROUTINE FM_ACOS(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMACOS(MA%MFM,MB%MFM)
   END SUBROUTINE FM_ACOS

   SUBROUTINE FM_ACOSH(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMACOSH(MA%MFM,MB%MFM)
   END SUBROUTINE FM_ACOSH

   SUBROUTINE FM_ADD(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMADD(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_ADD

   SUBROUTINE FM_ADD_R1(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MB
      INTENT (INOUT) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMADD_R1(MA%MFM,MB%MFM)
   END SUBROUTINE FM_ADD_R1

   SUBROUTINE FM_ADD_R2(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMADD_R2(MA%MFM,MB%MFM)
   END SUBROUTINE FM_ADD_R2

   SUBROUTINE FM_ADDI(MA,IVAL)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL FMADDI(MA%MFM,IVAL)
   END SUBROUTINE FM_ADDI

   SUBROUTINE FM_ASIN(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMASIN(MA%MFM,MB%MFM)
   END SUBROUTINE FM_ASIN

   SUBROUTINE FM_ASINH(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMASINH(MA%MFM,MB%MFM)
   END SUBROUTINE FM_ASINH

   SUBROUTINE FM_ATAN(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMATAN(MA%MFM,MB%MFM)
   END SUBROUTINE FM_ATAN

   SUBROUTINE FM_ATANH(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMATANH(MA%MFM,MB%MFM)
   END SUBROUTINE FM_ATANH

   SUBROUTINE FM_ATN2(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMATN2(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_ATN2

   SUBROUTINE FM_BIG(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      CALL FMBIG(MA%MFM)
   END SUBROUTINE FM_BIG

   SUBROUTINE FM_CEILING(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMINT(MA%MFM,MTLVFM)
      CALL FMSUB(MA%MFM,MTLVFM,MULVFM)
      IF (MULVFM%MP(3) == 0) THEN
          CALL FMEQ(MA%MFM,MB%MFM)
      ELSE IF (MA%MFM%MP(1) > 0) THEN
          CALL FMADDI(MTLVFM,1)
          CALL FMEQ(MTLVFM,MB%MFM)
      ELSE
          CALL FMEQ(MTLVFM,MB%MFM)
      ENDIF
   END SUBROUTINE FM_CEILING

   SUBROUTINE FM_CHANGEBASE(MA,MB,NEW_MBASE,NEW_NDIG)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTEGER :: NEW_MBASE,NEW_NDIG
      INTENT (IN) :: MA,NEW_MBASE,NEW_NDIG
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMCHANGEBASE(MA%MFM,MB%MFM,NEW_MBASE,NEW_NDIG)
   END SUBROUTINE FM_CHANGEBASE

   SUBROUTINE FM_CHSH(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB,MC
      CALL FM_UNDEF_INP(MA)
      CALL FMCHSH(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_CHSH

   FUNCTION FM_COMP(MA,LREL,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA,MB
      CHARACTER(*) :: LREL
      INTENT (IN) :: LREL
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = FMCOMP(MA%MFM,LREL,MB%MFM)
   END FUNCTION FM_COMP

   SUBROUTINE FM_COS(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMCOS(MA%MFM,MB%MFM)
   END SUBROUTINE FM_COS

   SUBROUTINE FM_COSH(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMCOSH(MA%MFM,MB%MFM)
   END SUBROUTINE FM_COSH

   SUBROUTINE FM_CSSN(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB,MC
      CALL FM_UNDEF_INP(MA)
      CALL FMCSSN(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_CSSN

   SUBROUTINE FM_DIM(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMDIM(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_DIM

   SUBROUTINE FM_DIV(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMDIV(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_DIV

   SUBROUTINE FM_DIV_R1(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MB
      INTENT (INOUT) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMDIV_R1(MA%MFM,MB%MFM)
   END SUBROUTINE FM_DIV_R1

   SUBROUTINE FM_DIV_R2(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMDIV_R2(MA%MFM,MB%MFM)
   END SUBROUTINE FM_DIV_R2

   SUBROUTINE FM_DIVI(MA,IVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL FMDIVI(MA%MFM,IVAL,MB%MFM)
   END SUBROUTINE FM_DIVI

   SUBROUTINE FM_DIVI_R1(MA,IVAL)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL FMDIVI_R1(MA%MFM,IVAL)
   END SUBROUTINE FM_DIVI_R1

   SUBROUTINE FM_DP2M(X,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      DOUBLE PRECISION :: X
      INTENT (IN) :: X
      CALL FMDP2M(X,MA%MFM)
   END SUBROUTINE FM_DP2M

   SUBROUTINE FM_DPM(X,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      DOUBLE PRECISION :: X
      INTENT (IN) :: X
      CALL FMDPM(X,MA%MFM)
   END SUBROUTINE FM_DPM

   SUBROUTINE FM_EPSILON(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FMI2M(1,MTLVFM)
      CALL FMULP(MTLVFM,MB%MFM)
      IF (ALLOCATED(MA%MFM%MP)) THEN
          IF (SIZE(MA%MFM%MP) <= 2) CALL FMMPYI(MB%MFM,1,MTLVFM)
      ENDIF
   END SUBROUTINE FM_EPSILON

   SUBROUTINE FM_EQU(MA,MB,NA,NB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: KA,KB,NA,NB,NDSAVE
      INTENT (IN) :: NA,NB
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      KA = NA
      KB = NB
      NDSAVE = NDIG
      NDIG = KA
      CALL FMEQU(MA%MFM,MB%MFM,KA,KB)
      NDIG = NDSAVE
   END SUBROUTINE FM_EQU

   SUBROUTINE FM_EQU_R1(MA,NA,NB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: KA,KB,NA,NB,NDSAVE
      INTENT (IN) :: NA,NB
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      CALL FM_UNDEF_INP(MA)
      KA = NA
      KB = NB
      NDSAVE = NDIG
      NDIG = KA
      CALL FMEQU_R1(MA%MFM,KA,KB)
      NDIG = NDSAVE
   END SUBROUTINE FM_EQU_R1

   SUBROUTINE FM_EXP(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMEXP(MA%MFM,MB%MFM)
   END SUBROUTINE FM_EXP

   SUBROUTINE FM_FLAG(K)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: K
      INTENT (INOUT) :: K
      CALL FMFLAG(K)
   END SUBROUTINE FM_FLAG

   SUBROUTINE FM_FORM(FORM,MA,STRING)
      USE ModLib_FMVALS
      IMPLICIT NONE
      CHARACTER(*) :: FORM,STRING
      INTENT (IN) :: FORM
      INTENT (INOUT) :: STRING
      TYPE (FM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMFORM(FORM,MA%MFM,STRING)
   END SUBROUTINE FM_FORM

   SUBROUTINE FM_FLOOR(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      TYPE(MULTI), SAVE :: MTLVFM,MULVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMINT(MA%MFM,MTLVFM)
      CALL FMSUB(MA%MFM,MTLVFM,MULVFM)
      IF (MULVFM%MP(3) == 0) THEN
          CALL FMEQ(MA%MFM,MB%MFM)
      ELSE IF (MA%MFM%MP(1) < 0) THEN
          CALL FMADDI(MTLVFM,-1)
          CALL FMEQ(MTLVFM,MB%MFM)
      ELSE
          CALL FMEQ(MTLVFM,MB%MFM)
      ENDIF
   END SUBROUTINE FM_FLOOR

   SUBROUTINE FM_FPRT(FORM,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      CHARACTER(*) :: FORM
      INTENT (IN) :: FORM
      TYPE (FM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMFPRT(FORM,MA%MFM)
   END SUBROUTINE FM_FPRT

   SUBROUTINE FM_FRACTION(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMEQ(MA%MFM,MTLVFM)
      MTLVFM%MP(2) = 0
      CALL FMEQ(MTLVFM,MB%MFM)
   END SUBROUTINE FM_FRACTION

   SUBROUTINE FM_HYPOT(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMHYPOT(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_HYPOT

   SUBROUTINE FM_I2M(IVAL,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FMI2M(IVAL,MA%MFM)
   END SUBROUTINE FM_I2M

   SUBROUTINE FM_INP(LINE,MA,LA,LB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: LA,LB
      INTENT (IN) :: LA,LB
      CHARACTER :: LINE(LB)
      INTENT (IN) :: LINE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      CALL FMINP(LINE,MA%MFM,LA,LB)
   END SUBROUTINE FM_INP

   SUBROUTINE FM_INT(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMINT(MA%MFM,MB%MFM)
   END SUBROUTINE FM_INT

   SUBROUTINE FM_IPWR(MA,IVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL FMIPWR(MA%MFM,IVAL,MB%MFM)
   END SUBROUTINE FM_IPWR

   SUBROUTINE FM_LG10(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMLG10(MA%MFM,MB%MFM)
   END SUBROUTINE FM_LG10

   SUBROUTINE FM_LN(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMLN(MA%MFM,MB%MFM)
   END SUBROUTINE FM_LN

   SUBROUTINE FM_LNI(IVAL,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FMLNI(IVAL,MA%MFM)
   END SUBROUTINE FM_LNI

   SUBROUTINE FM_M2DP(MA,X)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (IN) :: MA
      DOUBLE PRECISION :: X
      INTENT (INOUT) :: X
      CALL FM_UNDEF_INP(MA)
      CALL FMM2DP(MA%MFM,X)
   END SUBROUTINE FM_M2DP

   SUBROUTINE FM_M2I(MA,IVAL)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (IN) :: MA
      INTEGER :: IVAL
      INTENT (INOUT) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL FMM2I(MA%MFM,IVAL)
   END SUBROUTINE FM_M2I

   SUBROUTINE FM_M2SP(MA,X)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (IN) :: MA
      REAL :: X
      INTENT (INOUT) :: X
      CALL FM_UNDEF_INP(MA)
      CALL FMM2SP(MA%MFM,X)
   END SUBROUTINE FM_M2SP

   SUBROUTINE FM_MAX(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMMAX(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_MAX

   SUBROUTINE FM_MIN(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMMIN(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_MIN

   SUBROUTINE FM_MOD(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMMOD(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_MOD

   SUBROUTINE FM_MODULO(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMMOD(MA%MFM,MB%MFM,MTLVFM)
      IF (MTLVFM%MP(3) /= 0) THEN
          IF ((MA%MFM%MP(3) > 0 .AND. MA%MFM%MP(1) > 0 .AND.  &
               MB%MFM%MP(3) > 0 .AND. MB%MFM%MP(1) < 0) .OR.  &
              (MA%MFM%MP(3) > 0 .AND. MA%MFM%MP(1) < 0 .AND.  &
               MB%MFM%MP(3) > 0 .AND. MB%MFM%MP(1) > 0)) THEN
              CALL FMADD_R1(MTLVFM,MB%MFM)
          ENDIF
      ENDIF
      CALL FMEQ(MTLVFM,MC%MFM)
   END SUBROUTINE FM_MODULO

   SUBROUTINE FM_MPY(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMMPY(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_MPY

   SUBROUTINE FM_MPY_R1(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MB
      INTENT (INOUT) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMMPY_R1(MA%MFM,MB%MFM)
   END SUBROUTINE FM_MPY_R1

   SUBROUTINE FM_MPY_R2(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMMPY_R2(MA%MFM,MB%MFM)
   END SUBROUTINE FM_MPY_R2

   SUBROUTINE FM_MPYI(MA,IVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL FMMPYI(MA%MFM,IVAL,MB%MFM)
   END SUBROUTINE FM_MPYI

   SUBROUTINE FM_MPYI_R1(MA,IVAL)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL FMMPYI_R1(MA%MFM,IVAL)
   END SUBROUTINE FM_MPYI_R1

   SUBROUTINE FM_NEAREST(MA,MB,MC)
      USE ModLib_FMVALS
      USE ModLib_FMZM_8
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_EQ(FMNEAREST_FM(MA,MB),MC)
   END SUBROUTINE FM_NEAREST

   SUBROUTINE FM_NINT(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMNINT(MA%MFM,MB%MFM)
   END SUBROUTINE FM_NINT

   SUBROUTINE FM_OUT(MA,LINE,LB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: LB
      INTENT (IN) :: LB
      CHARACTER :: LINE(LB)
      INTENT (INOUT) :: LINE
      TYPE (FM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMOUT(MA%MFM,LINE,LB)
   END SUBROUTINE FM_OUT

   SUBROUTINE FM_PI(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      CALL FMPI(MA%MFM)
   END SUBROUTINE FM_PI

   SUBROUTINE FM_PRNT(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMPRNT(MA%MFM)
   END SUBROUTINE FM_PRNT

   SUBROUTINE FM_PWR(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMPWR(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_PWR

   SUBROUTINE FM_READ(KREAD,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: KREAD
      TYPE (FM) :: MA
      INTENT (IN) :: KREAD
      INTENT (INOUT) :: MA
      CALL FMREAD(KREAD,MA%MFM)
   END SUBROUTINE FM_READ

   SUBROUTINE FM_RPWR(MA,IVAL,JVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: IVAL,JVAL
      INTENT (IN) :: IVAL,JVAL
      CALL FM_UNDEF_INP(MA)
      CALL FMRPWR(MA%MFM,IVAL,JVAL,MB%MFM)
   END SUBROUTINE FM_RPWR

   SUBROUTINE FM_RRSPACING(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMABS(MA%MFM,MTLVFM)
      MTLVFM%MP(2) = NDIG
      CALL FMEQ(MTLVFM,MB%MFM)
   END SUBROUTINE FM_RRSPACING

   SUBROUTINE FM_SET(NPREC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: NPREC
      INTENT (IN) :: NPREC
      CALL FMSET(NPREC)
   END SUBROUTINE FM_SET

   SUBROUTINE FM_SETVAR(STRING)
      USE ModLib_FMVALS
      IMPLICIT NONE
      CHARACTER(*) :: STRING
      INTENT (IN) :: STRING
      CALL FMSETVAR(STRING)
   END SUBROUTINE FM_SETVAR

   SUBROUTINE FM_SIGN(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMSIGN(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_SIGN

   SUBROUTINE FM_SIN(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMSIN(MA%MFM,MB%MFM)
   END SUBROUTINE FM_SIN

   SUBROUTINE FM_SINH(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMSINH(MA%MFM,MB%MFM)
   END SUBROUTINE FM_SINH

   SUBROUTINE FM_SP2M(X,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      REAL :: X
      INTENT (IN) :: X
      CALL FMSP2M(X,MA%MFM)
   END SUBROUTINE FM_SP2M

   SUBROUTINE FM_SPACING(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMABS(MA%MFM,MTLVFM)
      CALL FMULP(MTLVFM,MB%MFM)
   END SUBROUTINE FM_SPACING

   SUBROUTINE FM_SQR(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMSQR(MA%MFM,MB%MFM)
   END SUBROUTINE FM_SQR

   SUBROUTINE FM_SQR_R1(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMSQR_R1(MA%MFM)
   END SUBROUTINE FM_SQR_R1

   SUBROUTINE FM_SQRT(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMSQRT(MA%MFM,MB%MFM)
   END SUBROUTINE FM_SQRT

   SUBROUTINE FM_SQRT_R1(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMSQRT_R1(MA%MFM)
   END SUBROUTINE FM_SQRT_R1

   SUBROUTINE FM_ST2M(STRING,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      CHARACTER(*) :: STRING
      INTENT (IN) :: STRING
      CALL FMST2M(STRING,MA%MFM)
   END SUBROUTINE FM_ST2M

   SUBROUTINE FM_SUB(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMSUB(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_SUB

   SUBROUTINE FM_SUB_R1(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MB
      INTENT (INOUT) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMSUB_R1(MA%MFM,MB%MFM)
   END SUBROUTINE FM_SUB_R1

   SUBROUTINE FM_SUB_R2(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMSUB_R2(MA%MFM,MB%MFM)
   END SUBROUTINE FM_SUB_R2

   SUBROUTINE FM_TAN(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMTAN(MA%MFM,MB%MFM)
   END SUBROUTINE FM_TAN

   SUBROUTINE FM_TANH(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMTANH(MA%MFM,MB%MFM)
   END SUBROUTINE FM_TANH

   SUBROUTINE FM_TINY(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      CALL FMTINY(MA%MFM)
   END SUBROUTINE FM_TINY

   SUBROUTINE FM_ULP(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMULP(MA%MFM,MB%MFM)
   END SUBROUTINE FM_ULP

   SUBROUTINE FM_VARS
      USE ModLib_FMVALS
      IMPLICIT NONE
      CALL FMVARS
   END SUBROUTINE FM_VARS

   SUBROUTINE FM_WRIT(KWRITE,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: KWRITE
      INTENT (IN) :: KWRITE
      TYPE (FM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMWRIT(KWRITE,MA%MFM)
   END SUBROUTINE FM_WRIT

   SUBROUTINE IM_ABS(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL IMABS(MA%MIM,MB%MIM)
   END SUBROUTINE IM_ABS

   SUBROUTINE IM_ADD(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMADD(MA%MIM,MB%MIM,MC%MIM)
   END SUBROUTINE IM_ADD

   SUBROUTINE IM_BIG(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA
      INTENT (INOUT) :: MA
      CALL IMBIG(MA%MIM)
   END SUBROUTINE IM_BIG

   SUBROUTINE IM_COMB(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL IMCOMB(MA%MIM,MB%MIM,MC%MIM)
   END SUBROUTINE IM_COMB

   FUNCTION IM_COMP(MA,LREL,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      TYPE (IM) :: MA,MB
      INTENT (IN) :: MA,MB
      CHARACTER(*) :: LREL
      INTENT (IN) :: LREL
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = IMCOMP(MA%MIM,LREL,MB%MIM)
   END FUNCTION IM_COMP

   SUBROUTINE IM_DIM(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMDIM(MA%MIM,MB%MIM,MC%MIM)
   END SUBROUTINE IM_DIM

   SUBROUTINE IM_DIV(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMDIV(MA%MIM,MB%MIM,MC%MIM)
   END SUBROUTINE IM_DIV

   SUBROUTINE IM_DIVI(MA,IVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL IMDIVI(MA%MIM,IVAL,MB%MIM)
   END SUBROUTINE IM_DIVI

   SUBROUTINE IM_DIVR(MA,MB,MC,MD)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC,MD
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC,MD
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMDIVR(MA%MIM,MB%MIM,MC%MIM,MD%MIM)
   END SUBROUTINE IM_DIVR

   SUBROUTINE IM_DVIR(MA,IVAL,MB,IREM)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: IVAL,IREM
      INTENT (IN) :: IVAL
      INTENT (INOUT) :: IREM
      CALL FM_UNDEF_INP(MA)
      CALL IMDVIR(MA%MIM,IVAL,MB%MIM,IREM)
   END SUBROUTINE IM_DVIR

   SUBROUTINE IM_FACT(IVAL,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      INTENT (INOUT) :: MA
      CALL IMFACT(IVAL,MA%MIM)
   END SUBROUTINE IM_FACT

   SUBROUTINE IM_FM2I(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (IN) :: MA
      TYPE (IM) :: MB
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL IMFM2I(MA%MFM,MB%MIM)
   END SUBROUTINE IM_FM2I

   SUBROUTINE IM_FORM(FORM,MA,STRING)
      USE ModLib_FMVALS
      IMPLICIT NONE
      CHARACTER(*) :: FORM,STRING
      INTENT (IN) :: FORM,MA
      TYPE (IM) :: MA
      INTENT (INOUT) :: STRING
      CALL FM_UNDEF_INP(MA)
      CALL IMFORM(FORM,MA%MIM,STRING)
   END SUBROUTINE IM_FORM

   SUBROUTINE IM_FPRT(FORM,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      CHARACTER(*) :: FORM
      INTENT (IN) :: FORM
      TYPE (IM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL IMFPRT(FORM,MA%MIM)
   END SUBROUTINE IM_FPRT

   SUBROUTINE IM_GCD(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMGCD(MA%MIM,MB%MIM,MC%MIM)
   END SUBROUTINE IM_GCD

   SUBROUTINE IM_I2FM(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA
      INTENT (IN) :: MA
      TYPE (FM) :: MB
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL IMI2FM(MA%MIM,MB%MFM)
   END SUBROUTINE IM_I2FM

   SUBROUTINE IM_I2M(IVAL,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA
      INTENT (INOUT) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL IMI2M(IVAL,MA%MIM)
   END SUBROUTINE IM_I2M

   SUBROUTINE IM_INP(LINE,MA,LA,LB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: LA,LB
      INTENT (IN) :: LA,LB
      CHARACTER :: LINE(LB)
      INTENT (IN) :: LINE
      TYPE (IM) :: MA
      INTENT (INOUT) :: MA
      CALL IMINP(LINE,MA%MIM,LA,LB)
   END SUBROUTINE IM_INP

   SUBROUTINE IM_M2DP(MA,X)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA
      INTENT (IN) :: MA
      DOUBLE PRECISION :: X
      INTENT (INOUT) :: X
      CALL FM_UNDEF_INP(MA)
      CALL IMM2DP(MA%MIM,X)
   END SUBROUTINE IM_M2DP

   SUBROUTINE IM_M2I(MA,IVAL)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA
      INTENT (IN) :: MA
      INTEGER :: IVAL
      INTENT (INOUT) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL IMM2I(MA%MIM,IVAL)
   END SUBROUTINE IM_M2I

   SUBROUTINE IM_MAX(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMMAX(MA%MIM,MB%MIM,MC%MIM)
   END SUBROUTINE IM_MAX

   SUBROUTINE IM_MIN(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMMIN(MA%MIM,MB%MIM,MC%MIM)
   END SUBROUTINE IM_MIN

   SUBROUTINE IM_MOD(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMMOD(MA%MIM,MB%MIM,MC%MIM)
   END SUBROUTINE IM_MOD

   SUBROUTINE IM_MPY(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMMPY(MA%MIM,MB%MIM,MC%MIM)
   END SUBROUTINE IM_MPY

   SUBROUTINE IM_MPYI(MA,IVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL IMMPYI(MA%MIM,IVAL,MB%MIM)
   END SUBROUTINE IM_MPYI

   SUBROUTINE IM_MPYM(MA,MB,MC,MD)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC,MD
      INTENT (IN) :: MA,MB,MC
      INTENT (INOUT) :: MD
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FM_UNDEF_INP(MC)
      CALL IMMPYM(MA%MIM,MB%MIM,MC%MIM,MD%MIM)
   END SUBROUTINE IM_MPYM

   SUBROUTINE IM_OUT(MA,LINE,LB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: LB
      INTENT (IN) :: LB
      CHARACTER :: LINE(LB)
      INTENT (INOUT) :: LINE
      TYPE (IM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL IMOUT(MA%MIM,LINE,LB)
   END SUBROUTINE IM_OUT

   SUBROUTINE IM_PMOD(MA,MB,MC,MD)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC,MD
      INTENT (IN) :: MA,MB,MC
      INTENT (INOUT) :: MD
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FM_UNDEF_INP(MC)
      CALL IMPMOD(MA%MIM,MB%MIM,MC%MIM,MD%MIM)
   END SUBROUTINE IM_PMOD

   SUBROUTINE IM_PRNT(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL IMPRNT(MA%MIM)
   END SUBROUTINE IM_PRNT

   SUBROUTINE IM_PWR(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMPWR(MA%MIM,MB%MIM,MC%MIM)
   END SUBROUTINE IM_PWR

   SUBROUTINE IM_READ(KREAD,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: KREAD
      INTENT (IN) :: KREAD
      TYPE (IM) :: MA
      INTENT (INOUT) :: MA
      CALL IMREAD(KREAD,MA%MIM)
   END SUBROUTINE IM_READ

   SUBROUTINE IM_SIGN(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMSIGN(MA%MIM,MB%MIM,MC%MIM)
   END SUBROUTINE IM_SIGN

   SUBROUTINE IM_SQR(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL IMSQR(MA%MIM,MB%MIM)
   END SUBROUTINE IM_SQR

   SUBROUTINE IM_ST2M(STRING,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA
      INTENT (INOUT) :: MA
      CHARACTER(*) :: STRING
      INTENT (IN) :: STRING
      CALL IMST2M(STRING,MA%MIM)
   END SUBROUTINE IM_ST2M

   SUBROUTINE IM_SUB(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMSUB(MA%MIM,MB%MIM,MC%MIM)
   END SUBROUTINE IM_SUB

   SUBROUTINE IM_WRIT(KWRITE,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: KWRITE
      INTENT (IN) :: KWRITE
      TYPE (IM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL IMWRIT(KWRITE,MA%MIM)
   END SUBROUTINE IM_WRIT

   SUBROUTINE ZM_ABS(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA
      INTENT (IN) :: MA
      TYPE (FM) :: MB
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMABS(MA%MZM,MB%MFM)
   END SUBROUTINE ZM_ABS

   SUBROUTINE ZM_ACOS(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMACOS(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_ACOS

   SUBROUTINE ZM_ACOSH(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMACOSH(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_ACOSH

   SUBROUTINE ZM_ADD(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL ZMADD(MA%MZM,MB%MZM,MC%MZM)
   END SUBROUTINE ZM_ADD

   SUBROUTINE ZM_ADDI(MA,IVAL)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA
      INTENT (INOUT) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL ZMADDI(MA%MZM,IVAL)
   END SUBROUTINE ZM_ADDI

   SUBROUTINE ZM_ARG(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA
      INTENT (IN) :: MA
      TYPE (FM) :: MB
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMARG(MA%MZM,MB%MFM)
   END SUBROUTINE ZM_ARG

   SUBROUTINE ZM_ASIN(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMASIN(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_ASIN

   SUBROUTINE ZM_ASINH(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMASINH(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_ASINH

   SUBROUTINE ZM_ATAN(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMATAN(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_ATAN

   SUBROUTINE ZM_ATANH(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMATANH(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_ATANH

   SUBROUTINE ZM_CHSH(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB,MC
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB,MC
      CALL FM_UNDEF_INP(MA)
      CALL ZMCHSH(MA%MZM,MB%MZM,MC%MZM)
   END SUBROUTINE ZM_CHSH

   SUBROUTINE ZM_CMPX(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA,MB
      TYPE (ZM) :: MC
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL ZMCMPX(MA%MFM,MB%MFM,MC%MZM)
   END SUBROUTINE ZM_CMPX

   SUBROUTINE ZM_CONJ(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMCONJ(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_CONJ

   SUBROUTINE ZM_COS(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMCOS(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_COS

   SUBROUTINE ZM_COSH(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMCOSH(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_COSH

   SUBROUTINE ZM_CSSN(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB,MC
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB,MC
      CALL FM_UNDEF_INP(MA)
      CALL ZMCSSN(MA%MZM,MB%MZM,MC%MZM)
   END SUBROUTINE ZM_CSSN

   SUBROUTINE ZM_DIV(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL ZMDIV(MA%MZM,MB%MZM,MC%MZM)
   END SUBROUTINE ZM_DIV

   SUBROUTINE ZM_DIVI(MA,IVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL ZMDIVI(MA%MZM,IVAL,MB%MZM)
   END SUBROUTINE ZM_DIVI

   SUBROUTINE ZM_EQU(MA,MB,NA,NB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: NA,NB
      INTENT (IN) :: NA,NB
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMEQU(MA%MZM,MB%MZM,NA,NB)
   END SUBROUTINE ZM_EQU

   SUBROUTINE ZM_EXP(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMEXP(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_EXP

   SUBROUTINE ZM_FORM(FORM1,FORM2,MA,STRING)
      USE ModLib_FMVALS
      IMPLICIT NONE
      CHARACTER(*) :: FORM1,FORM2,STRING
      INTENT (IN) :: FORM1,FORM2
      INTENT (INOUT) :: STRING
      TYPE (ZM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMFORM(FORM1,FORM2,MA%MZM,STRING)
   END SUBROUTINE ZM_FORM

   SUBROUTINE ZM_FPRT(FORM1,FORM2,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      CHARACTER(*) :: FORM1,FORM2
      INTENT (IN) :: FORM1,FORM2
      TYPE (ZM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMFPRT(FORM1,FORM2,MA%MZM)
   END SUBROUTINE ZM_FPRT

   SUBROUTINE ZM_I2M(IVAL,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA
      INTENT (INOUT) :: MA
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL ZMI2M(IVAL,MA%MZM)
   END SUBROUTINE ZM_I2M

   SUBROUTINE ZM_2I2M(IVAL1,IVAL2,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA
      INTENT (INOUT) :: MA
      INTEGER :: IVAL1,IVAL2
      INTENT (IN) :: IVAL1,IVAL2
      CALL ZM2I2M(IVAL1,IVAL2,MA%MZM)
   END SUBROUTINE ZM_2I2M

   SUBROUTINE ZM_IMAG(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA
      INTENT (IN) :: MA
      TYPE (FM) :: MB
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMIMAG(MA%MZM,MB%MFM)
   END SUBROUTINE ZM_IMAG

   SUBROUTINE ZM_INP(LINE,MA,LA,LB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: LA,LB
      INTENT (IN) :: LA,LB
      CHARACTER :: LINE(LB)
      INTENT (IN) :: LINE
      TYPE (ZM) :: MA
      INTENT (INOUT) :: MA
      CALL ZMINP(LINE,MA%MZM,LA,LB)
   END SUBROUTINE ZM_INP

   SUBROUTINE ZM_INT(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMINT(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_INT

   SUBROUTINE ZM_IPWR(MA,IVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL ZMIPWR(MA%MZM,IVAL,MB%MZM)
   END SUBROUTINE ZM_IPWR

   SUBROUTINE ZM_LG10(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMLG10(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_LG10

   SUBROUTINE ZM_LN(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMLN(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_LN

   SUBROUTINE ZM_M2I(MA,IVAL)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA
      INTENT (IN) :: MA
      INTEGER :: IVAL
      INTENT (INOUT) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL ZMM2I(MA%MZM,IVAL)
   END SUBROUTINE ZM_M2I

   SUBROUTINE ZM_M2Z(MA,ZVAL)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA
      INTENT (IN) :: MA
      COMPLEX :: ZVAL
      INTENT (INOUT) :: ZVAL
      CALL FM_UNDEF_INP(MA)
      CALL ZMM2Z(MA%MZM,ZVAL)
   END SUBROUTINE ZM_M2Z

   SUBROUTINE ZM_MPY(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL ZMMPY(MA%MZM,MB%MZM,MC%MZM)
   END SUBROUTINE ZM_MPY

   SUBROUTINE ZM_MPYI(MA,IVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL ZMMPYI(MA%MZM,IVAL,MB%MZM)
   END SUBROUTINE ZM_MPYI

   SUBROUTINE ZM_NINT(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMNINT(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_NINT

   SUBROUTINE ZM_OUT(MA,LINE,LB,LAST1,LAST2)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: LB,LAST1,LAST2
      INTENT (IN) :: LB
      CHARACTER :: LINE(LB)
      INTENT (INOUT) :: LINE,LAST1,LAST2
      TYPE (ZM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMOUT(MA%MZM,LINE,LB,LAST1,LAST2)
   END SUBROUTINE ZM_OUT

   SUBROUTINE ZM_PRNT(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMPRNT(MA%MZM)
   END SUBROUTINE ZM_PRNT

   SUBROUTINE ZM_PWR(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL ZMPWR(MA%MZM,MB%MZM,MC%MZM)
   END SUBROUTINE ZM_PWR

   SUBROUTINE ZM_READ(KREAD,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: KREAD
      INTENT (IN) :: KREAD
      TYPE (ZM) :: MA
      INTENT (INOUT) :: MA
      CALL ZMREAD(KREAD,MA%MZM)
   END SUBROUTINE ZM_READ

   SUBROUTINE ZM_REAL(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA
      INTENT (IN) :: MA
      TYPE (FM) :: MB
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMREAL(MA%MZM,MB%MFM)
   END SUBROUTINE ZM_REAL

   SUBROUTINE ZM_RPWR(MA,IVAL,JVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: IVAL,JVAL
      INTENT (IN) :: IVAL,JVAL
      CALL FM_UNDEF_INP(MA)
      CALL ZMRPWR(MA%MZM,IVAL,JVAL,MB%MZM)
   END SUBROUTINE ZM_RPWR

   SUBROUTINE ZM_SET(NPREC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: NPREC
      INTENT (IN) :: NPREC
      CALL ZMSET(NPREC)
   END SUBROUTINE ZM_SET

   SUBROUTINE ZM_SIN(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMSIN(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_SIN

   SUBROUTINE ZM_SINH(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMSINH(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_SINH

   SUBROUTINE ZM_SQR(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMSQR(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_SQR

   SUBROUTINE ZM_SQRT(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMSQRT(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_SQRT

   SUBROUTINE ZM_ST2M(STRING,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA
      INTENT (INOUT) :: MA
      CHARACTER(*) :: STRING
      INTENT (IN) :: STRING
      CALL ZMST2M(STRING,MA%MZM)
   END SUBROUTINE ZM_ST2M

   SUBROUTINE ZM_SUB(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL ZMSUB(MA%MZM,MB%MZM,MC%MZM)
   END SUBROUTINE ZM_SUB

   SUBROUTINE ZM_TAN(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMTAN(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_TAN

   SUBROUTINE ZM_TANH(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMTANH(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_TANH

   SUBROUTINE ZM_WRIT(KWRITE,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: KWRITE
      INTENT (IN) :: KWRITE
      TYPE (ZM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMWRIT(KWRITE,MA%MZM)
   END SUBROUTINE ZM_WRIT

   SUBROUTINE ZM_Z2M(ZVAL,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA
      INTENT (INOUT) :: MA
      COMPLEX :: ZVAL
      INTENT (IN) :: ZVAL
      CALL ZMZ2M(ZVAL,MA%MZM)
   END SUBROUTINE ZM_Z2M

   SUBROUTINE ZM_ERF(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMERF(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_ERF

   SUBROUTINE ZM_ERFC(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMERFC(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_ERFC

   SUBROUTINE ZM_ERFC_SC(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMERFC_SC(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_ERFC_SC

   SUBROUTINE ZM_LNGM(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMLNGM(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_LNGM

   SUBROUTINE ZM_GAM(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMGAM(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_GAM

   SUBROUTINE ZM_FACT(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZMFACT(MA%MZM,MB%MZM)
   END SUBROUTINE ZM_FACT

   SUBROUTINE FM_ATAN2(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FM_ATN2(MA,MB,MC)
   END SUBROUTINE FM_ATAN2

   SUBROUTINE FM_COSH_SINH(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB,MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_CHSH(MA,MB,MC)
   END SUBROUTINE FM_COSH_SINH

   FUNCTION FM_COMPARE(MA,LREL,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: FMCOMP
      CHARACTER(*) :: LREL
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA,LREL,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = FMCOMP(MA%MFM,LREL,MB%MFM)
   END FUNCTION FM_COMPARE

   SUBROUTINE FM_COS_SIN(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB,MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_CSSN(MA,MB,MC)
   END SUBROUTINE FM_COS_SIN

   SUBROUTINE FM_EULER(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      CALL FM_EULR(MA)
   END SUBROUTINE FM_EULER

   SUBROUTINE FM_FPRINT(FORM,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      CHARACTER(*) :: FORM
      TYPE (FM) :: MA
      INTENT (IN) :: FORM,MA
      CALL FM_UNDEF_INP(MA)
      CALL FM_FPRT(FORM,MA)
   END SUBROUTINE FM_FPRINT

   SUBROUTINE FM_IPOWER(MA,IVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTEGER :: IVAL
      INTENT (IN) :: MA,IVAL
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_IPWR(MA,IVAL,MB)
   END SUBROUTINE FM_IPOWER

   SUBROUTINE FM_LOG10(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_LG10(MA,MB)
   END SUBROUTINE FM_LOG10

   SUBROUTINE FM_PRINT(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FM_PRNT(MA)
   END SUBROUTINE FM_PRINT

   SUBROUTINE FM_POWER(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FM_PWR(MA,MB,MC)
   END SUBROUTINE FM_POWER

   SUBROUTINE FM_RATIONAL_POWER(MA,IVAL,JVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTEGER :: IVAL,JVAL
      INTENT (IN) :: MA,IVAL,JVAL
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_RPWR(MA,IVAL,JVAL,MB)
   END SUBROUTINE FM_RATIONAL_POWER

   SUBROUTINE FM_WRITE(KWRITE,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: KWRITE
      TYPE (FM) :: MA
      INTENT (IN) :: KWRITE,MA
      CALL FM_UNDEF_INP(MA)
      CALL FM_WRIT(KWRITE,MA)
   END SUBROUTINE FM_WRITE

   FUNCTION IM_COMPARE(MA,LREL,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      LOGICAL :: RETURN_VALUE
      LOGICAL, EXTERNAL :: IMCOMP
      CHARACTER(*) :: LREL
      TYPE (IM) :: MA,MB
      INTENT (IN) :: MA,LREL,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      RETURN_VALUE = IMCOMP(MA%MIM,LREL,MB%MIM)
   END FUNCTION IM_COMPARE

   SUBROUTINE IM_FPRINT(FORM,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      CHARACTER(*) :: FORM
      TYPE (IM) :: MA
      INTENT (IN) :: FORM,MA
      CALL FM_UNDEF_INP(MA)
      CALL IM_FPRT(FORM,MA)
   END SUBROUTINE IM_FPRINT

   SUBROUTINE IM_MPY_MOD(MA,MB,MC,MD)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC,MD
      INTENT (IN) :: MA,MB,MC
      INTENT (INOUT) :: MD
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FM_UNDEF_INP(MC)
      CALL IM_MPYM(MA,MB,MC,MD)
   END SUBROUTINE IM_MPY_MOD

   SUBROUTINE IM_POWER_MOD(MA,MB,MC,MD)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC,MD
      INTENT (IN) :: MA,MB,MC
      INTENT (INOUT) :: MD
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FM_UNDEF_INP(MC)
      CALL IM_PMOD(MA,MB,MC,MD)
   END SUBROUTINE IM_POWER_MOD

   SUBROUTINE IM_PRINT(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL IM_PRNT(MA)
   END SUBROUTINE IM_PRINT

   SUBROUTINE IM_POWER(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IM_PWR(MA,MB,MC)
   END SUBROUTINE IM_POWER

   SUBROUTINE IM_WRITE(KWRITE,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: KWRITE
      INTENT (IN) :: KWRITE
      TYPE (IM) :: MA
      INTENT (INOUT) :: MA
      CALL IMWRITE(KWRITE,MA%MIM)
   END SUBROUTINE IM_WRITE

   SUBROUTINE ZM_COSH_SINH(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB,MC
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB,MC
      CALL FM_UNDEF_INP(MA)
      CALL ZM_CHSH(MA,MB,MC)
   END SUBROUTINE ZM_COSH_SINH

   SUBROUTINE ZM_COMPLEX(MAFM,MBFM,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MAFM,MBFM
      TYPE (ZM) :: MC
      INTENT (IN) :: MAFM,MBFM
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MAFM)
      CALL FM_UNDEF_INP(MBFM)
      CALL ZM_CMPX(MAFM,MBFM,MC)
   END SUBROUTINE ZM_COMPLEX

   SUBROUTINE ZM_CONJUGATE(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZM_CONJ(MA,MB)
   END SUBROUTINE ZM_CONJUGATE

   SUBROUTINE ZM_COS_SIN(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB,MC
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB,MC
      CALL FM_UNDEF_INP(MA)
      CALL ZM_CSSN(MA,MB,MC)
   END SUBROUTINE ZM_COS_SIN

   SUBROUTINE ZM_FPRINT(FORM1,FORM2,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      CHARACTER(*) :: FORM1,FORM2
      TYPE (ZM) :: MA
      INTENT (IN) :: FORM1,FORM2,MA
      CALL FM_UNDEF_INP(MA)
      CALL ZM_FPRT(FORM1,FORM2,MA)
   END SUBROUTINE ZM_FPRINT

   SUBROUTINE ZM_IPOWER(MA,IVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTEGER :: IVAL
      INTENT (IN) :: MA,IVAL
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZM_IPWR(MA,IVAL,MB)
   END SUBROUTINE ZM_IPOWER

   SUBROUTINE ZM_LOG10(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZM_LG10(MA,MB)
   END SUBROUTINE ZM_LOG10

   SUBROUTINE ZM_PRINT(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZM_PRNT(MA)
   END SUBROUTINE ZM_PRINT

   SUBROUTINE ZM_POWER(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL ZM_PWR(MA,MB,MC)
   END SUBROUTINE ZM_POWER

   SUBROUTINE ZM_RATIONAL_POWER(MA,IVAL,JVAL,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,MB
      INTEGER :: IVAL,JVAL
      INTENT (IN) :: MA,IVAL,JVAL
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL ZM_RPWR(MA,IVAL,JVAL,MB)
   END SUBROUTINE ZM_RATIONAL_POWER

   SUBROUTINE ZM_WRITE(KWRITE,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: KWRITE
      TYPE (ZM) :: MA
      INTENT (IN) :: KWRITE,MA
      CALL FM_UNDEF_INP(MA)
      CALL ZM_WRIT(KWRITE,MA)
   END SUBROUTINE ZM_WRITE

   SUBROUTINE FM_BERNOULLI(N,MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      INTEGER :: N
      INTENT (IN) :: N
      CALL FMBERNOULLI(N,MA%MFM)
   END SUBROUTINE FM_BERNOULLI

   SUBROUTINE FM_BERN(N,MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: N
      INTENT (IN) :: N
      CALL FM_UNDEF_INP(MA)
      CALL FMBERN(N,MA%MFM,MB%MFM)
   END SUBROUTINE FM_BERN

   SUBROUTINE FM_BETA(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMBETA(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_BETA

   SUBROUTINE FM_COMB(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMCOMB(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_COMB

   SUBROUTINE FM_EULR(MA)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA
      INTENT (INOUT) :: MA
      CALL FMEULR(MA%MFM)
   END SUBROUTINE FM_EULR

   SUBROUTINE FM_FACT(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMFACT(MA%MFM,MB%MFM)
   END SUBROUTINE FM_FACT

   SUBROUTINE FM_GAM(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMGAM(MA%MFM,MB%MFM)
   END SUBROUTINE FM_GAM

   SUBROUTINE FM_IBTA(MA,MB,MC,MD)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC,MD
      INTENT (IN) :: MA,MB,MC
      INTENT (INOUT) :: MD
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FM_UNDEF_INP(MC)
      CALL FMIBTA(MA%MFM,MB%MFM,MC%MFM,MD%MFM)
   END SUBROUTINE FM_IBTA

   SUBROUTINE FM_IGM1(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMIGM1(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_IGM1

   SUBROUTINE FM_IGM2(MA,MB,MC)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,MC
      INTENT (IN) :: MA,MB
      INTENT (INOUT) :: MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMIGM2(MA%MFM,MB%MFM,MC%MFM)
   END SUBROUTINE FM_IGM2

   SUBROUTINE FM_LNGM(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMLNGM(MA%MFM,MB%MFM)
   END SUBROUTINE FM_LNGM

   SUBROUTINE FM_PGAM(N,MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: N
      INTENT (IN) :: N
      CALL FM_UNDEF_INP(MA)
      CALL FMPGAM(N,MA%MFM,MB%MFM)
   END SUBROUTINE FM_PGAM

   SUBROUTINE FM_POCH(MA,N,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: N
      INTENT (IN) :: N
      CALL FM_UNDEF_INP(MA)
      CALL FMPOCH(MA%MFM,N,MB%MFM)
   END SUBROUTINE FM_POCH

   SUBROUTINE FM_PSI(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMPSI(MA%MFM,MB%MFM)
   END SUBROUTINE FM_PSI

   SUBROUTINE FM_BESJ(N,MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: N
      INTENT (IN) :: N
      CALL FM_UNDEF_INP(MA)
      CALL FMBESJ(N,MA%MFM,MB%MFM)
   END SUBROUTINE FM_BESJ

   SUBROUTINE FM_BESY(N,MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: N
      INTENT (IN) :: N
      CALL FM_UNDEF_INP(MA)
      CALL FMBESY(N,MA%MFM,MB%MFM)
   END SUBROUTINE FM_BESY

   SUBROUTINE FM_CHI(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMCHI(MA%MFM,MB%MFM)
   END SUBROUTINE FM_CHI

   SUBROUTINE FM_CI(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMCI(MA%MFM,MB%MFM)
   END SUBROUTINE FM_CI

   SUBROUTINE FM_EI(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMEI(MA%MFM,MB%MFM)
   END SUBROUTINE FM_EI

   SUBROUTINE FM_EN(N,MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      INTEGER :: N
      INTENT (IN) :: N
      CALL FM_UNDEF_INP(MA)
      CALL FMEN(N,MA%MFM,MB%MFM)
   END SUBROUTINE FM_EN

   SUBROUTINE FM_C(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMC(MA%MFM,MB%MFM)
   END SUBROUTINE FM_C

   SUBROUTINE FM_S(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMS(MA%MFM,MB%MFM)
   END SUBROUTINE FM_S

   SUBROUTINE FM_ERF(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMERF(MA%MFM,MB%MFM)
   END SUBROUTINE FM_ERF

   SUBROUTINE FM_ERFC(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMERFC(MA%MFM,MB%MFM)
   END SUBROUTINE FM_ERFC

   SUBROUTINE FM_ERFC_SCALED(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMERFCS(MA%MFM,MB%MFM)
   END SUBROUTINE FM_ERFC_SCALED

   SUBROUTINE FM_LERC(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMLERC(MA%MFM,MB%MFM)
   END SUBROUTINE FM_LERC

   SUBROUTINE FM_LI(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMLI(MA%MFM,MB%MFM)
   END SUBROUTINE FM_LI

   SUBROUTINE FM_SHI(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMSHI(MA%MFM,MB%MFM)
   END SUBROUTINE FM_SHI

   SUBROUTINE FM_SI(MA,MB)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB
      INTENT (IN) :: MA
      INTENT (INOUT) :: MB
      CALL FM_UNDEF_INP(MA)
      CALL FMSI(MA%MFM,MB%MFM)
   END SUBROUTINE FM_SI

 END MODULE ModLib_FMZM_10
