
 MODULE ModLib_FMZM_9
    USE ModLib_FMZM_1

   INTERFACE SIN
      MODULE PROCEDURE FMSIN_FM
      MODULE PROCEDURE FMSIN_ZM
      MODULE PROCEDURE FMSIN_FM1
      MODULE PROCEDURE FMSIN_ZM1
      MODULE PROCEDURE FMSIN_FM2
      MODULE PROCEDURE FMSIN_ZM2
   END INTERFACE

   INTERFACE SINH
      MODULE PROCEDURE FMSINH_FM
      MODULE PROCEDURE FMSINH_ZM
      MODULE PROCEDURE FMSINH_FM1
      MODULE PROCEDURE FMSINH_ZM1
      MODULE PROCEDURE FMSINH_FM2
      MODULE PROCEDURE FMSINH_ZM2
   END INTERFACE

   INTERFACE SPACING
      MODULE PROCEDURE FMSPACING_FM
   END INTERFACE

   INTERFACE SQRT
      MODULE PROCEDURE FMSQRT_FM
      MODULE PROCEDURE FMSQRT_ZM
      MODULE PROCEDURE FMSQRT_FM1
      MODULE PROCEDURE FMSQRT_ZM1
      MODULE PROCEDURE FMSQRT_FM2
      MODULE PROCEDURE FMSQRT_ZM2
   END INTERFACE

   INTERFACE SUM
      MODULE PROCEDURE FMSUM1_FM
      MODULE PROCEDURE FMSUM2_FM
      MODULE PROCEDURE FMSUM1_IM
      MODULE PROCEDURE FMSUM2_IM
      MODULE PROCEDURE FMSUM1_ZM
      MODULE PROCEDURE FMSUM2_ZM
   END INTERFACE

   INTERFACE TAN
      MODULE PROCEDURE FMTAN_FM
      MODULE PROCEDURE FMTAN_ZM
      MODULE PROCEDURE FMTAN_FM1
      MODULE PROCEDURE FMTAN_ZM1
      MODULE PROCEDURE FMTAN_FM2
      MODULE PROCEDURE FMTAN_ZM2
   END INTERFACE

   INTERFACE TANH
      MODULE PROCEDURE FMTANH_FM
      MODULE PROCEDURE FMTANH_ZM
      MODULE PROCEDURE FMTANH_FM1
      MODULE PROCEDURE FMTANH_ZM1
      MODULE PROCEDURE FMTANH_FM2
      MODULE PROCEDURE FMTANH_ZM2
   END INTERFACE

   INTERFACE TINY
      MODULE PROCEDURE FMTINY_FM
      MODULE PROCEDURE FMTINY_IM
      MODULE PROCEDURE FMTINY_ZM
   END INTERFACE

   INTERFACE TRANSPOSE
      MODULE PROCEDURE FMTRANSPOSE_FM
      MODULE PROCEDURE FMTRANSPOSE_IM
      MODULE PROCEDURE FMTRANSPOSE_ZM
   END INTERFACE

   INTERFACE FM_FORMAT
      MODULE PROCEDURE FMFORMAT_FM
   END INTERFACE

   INTERFACE IM_FORMAT
      MODULE PROCEDURE IMFORMAT_IM
   END INTERFACE

   INTERFACE ZM_FORMAT
      MODULE PROCEDURE ZMFORMAT_ZM
   END INTERFACE

   INTERFACE GCD
      MODULE PROCEDURE GCD_IM
   END INTERFACE

   INTERFACE MULTIPLY_MOD
      MODULE PROCEDURE MULTIPLYMOD_IM
   END INTERFACE

   INTERFACE POWER_MOD
      MODULE PROCEDURE POWERMOD_IM
   END INTERFACE

   INTERFACE BERNOULLI
      MODULE PROCEDURE FMBERNOULLI_FM
   END INTERFACE

   INTERFACE BETA
      MODULE PROCEDURE FMBETA_FM
   END INTERFACE

   INTERFACE BINOMIAL
      MODULE PROCEDURE FMBINOMIAL_FM
      MODULE PROCEDURE FMBINOMIAL_IM
      MODULE PROCEDURE FMBINOMIAL_I
   END INTERFACE

   INTERFACE FACTORIAL
      MODULE PROCEDURE FMFACTORIAL_FM
      MODULE PROCEDURE FMFACTORIAL_FM1
      MODULE PROCEDURE FMFACTORIAL_FM2
      MODULE PROCEDURE FMFACTORIAL_IM
      MODULE PROCEDURE FMFACTORIAL_IM1
      MODULE PROCEDURE FMFACTORIAL_IM2
      MODULE PROCEDURE FMFACTORIAL_ZM
      MODULE PROCEDURE FMFACTORIAL_ZM1
      MODULE PROCEDURE FMFACTORIAL_ZM2
      MODULE PROCEDURE FMFACTORIAL_I
      MODULE PROCEDURE FMFACTORIAL_I1
      MODULE PROCEDURE FMFACTORIAL_I2
   END INTERFACE

   INTERFACE GAMMA
      MODULE PROCEDURE FMGAMMA_FM
      MODULE PROCEDURE FMGAMMA_FM1
      MODULE PROCEDURE FMGAMMA_FM2
      MODULE PROCEDURE FMGAMMA_ZM
      MODULE PROCEDURE FMGAMMA_ZM1
      MODULE PROCEDURE FMGAMMA_ZM2
   END INTERFACE

   INTERFACE INCOMPLETE_BETA
      MODULE PROCEDURE FMINCOMPLETE_BETA_FM
   END INTERFACE

   INTERFACE INCOMPLETE_GAMMA1
      MODULE PROCEDURE FMINCOMPLETE_GAMMA1_FM
   END INTERFACE

   INTERFACE INCOMPLETE_GAMMA2
      MODULE PROCEDURE FMINCOMPLETE_GAMMA2_FM
   END INTERFACE

   INTERFACE LOG_GAMMA
      MODULE PROCEDURE FMLOG_GAMMA_FM
      MODULE PROCEDURE FMLOG_GAMMA_FM1
      MODULE PROCEDURE FMLOG_GAMMA_FM2
      MODULE PROCEDURE FMLOG_GAMMA_ZM
      MODULE PROCEDURE FMLOG_GAMMA_ZM1
      MODULE PROCEDURE FMLOG_GAMMA_ZM2
   END INTERFACE

   INTERFACE POLYGAMMA
      MODULE PROCEDURE FMPOLYGAMMA_FM
   END INTERFACE

   INTERFACE POCHHAMMER
      MODULE PROCEDURE FMPOCHHAMMER_FM
   END INTERFACE

   INTERFACE PSI
      MODULE PROCEDURE FMPSI_FM
      MODULE PROCEDURE FMPSI_FM1
      MODULE PROCEDURE FMPSI_FM2
   END INTERFACE

   INTERFACE BESSEL_J
      MODULE PROCEDURE FMBESSEL_J_FM
   END INTERFACE

   INTERFACE BESSEL_J0
      MODULE PROCEDURE FMBESSEL_J0_FM
   END INTERFACE

   INTERFACE BESSEL_J1
      MODULE PROCEDURE FMBESSEL_J1_FM
   END INTERFACE

   INTERFACE BESSEL_JN
      MODULE PROCEDURE FMBESSEL_JN_FM
      MODULE PROCEDURE FMBESSEL_JN2_FM
   END INTERFACE

   INTERFACE BESSEL_Y
      MODULE PROCEDURE FMBESSEL_Y_FM
   END INTERFACE

   INTERFACE BESSEL_Y0
      MODULE PROCEDURE FMBESSEL_Y0_FM
   END INTERFACE

   INTERFACE BESSEL_Y1
      MODULE PROCEDURE FMBESSEL_Y1_FM
   END INTERFACE

   INTERFACE BESSEL_YN
      MODULE PROCEDURE FMBESSEL_YN_FM
      MODULE PROCEDURE FMBESSEL_YN2_FM
   END INTERFACE

   INTERFACE COS_INTEGRAL
      MODULE PROCEDURE FMCOS_INTEGRAL_FM
      MODULE PROCEDURE FMCOS_INTEGRAL_FM1
      MODULE PROCEDURE FMCOS_INTEGRAL_FM2
   END INTERFACE

   INTERFACE COSH_INTEGRAL
      MODULE PROCEDURE FMCOSH_INTEGRAL_FM
      MODULE PROCEDURE FMCOSH_INTEGRAL_FM1
      MODULE PROCEDURE FMCOSH_INTEGRAL_FM2
   END INTERFACE

   INTERFACE EXP_INTEGRAL_EI
      MODULE PROCEDURE FMEXP_INTEGRAL_EI_FM
      MODULE PROCEDURE FMEXP_INTEGRAL_EI_FM1
      MODULE PROCEDURE FMEXP_INTEGRAL_EI_FM2
   END INTERFACE

   INTERFACE EXP_INTEGRAL_EN
      MODULE PROCEDURE FMEXP_INTEGRAL_EN_FM
   END INTERFACE

   INTERFACE FRESNEL_C
      MODULE PROCEDURE FMFRESNEL_C_FM
      MODULE PROCEDURE FMFRESNEL_C_FM1
      MODULE PROCEDURE FMFRESNEL_C_FM2
   END INTERFACE

   INTERFACE FRESNEL_S
      MODULE PROCEDURE FMFRESNEL_S_FM
      MODULE PROCEDURE FMFRESNEL_S_FM1
      MODULE PROCEDURE FMFRESNEL_S_FM2
   END INTERFACE

   INTERFACE ERF
      MODULE PROCEDURE FMERF_FM
      MODULE PROCEDURE FMERF_FM1
      MODULE PROCEDURE FMERF_FM2
      MODULE PROCEDURE FMERF_ZM
      MODULE PROCEDURE FMERF_ZM1
      MODULE PROCEDURE FMERF_ZM2
   END INTERFACE

   INTERFACE ERFC
      MODULE PROCEDURE FMERFC_FM
      MODULE PROCEDURE FMERFC_FM1
      MODULE PROCEDURE FMERFC_FM2
      MODULE PROCEDURE FMERFC_ZM
      MODULE PROCEDURE FMERFC_ZM1
      MODULE PROCEDURE FMERFC_ZM2
   END INTERFACE

   INTERFACE ERFC_SCALED
      MODULE PROCEDURE FMERFC_SCALED_FM
      MODULE PROCEDURE FMERFC_SCALED_FM1
      MODULE PROCEDURE FMERFC_SCALED_FM2
      MODULE PROCEDURE FMERFC_SCALED_ZM
      MODULE PROCEDURE FMERFC_SCALED_ZM1
      MODULE PROCEDURE FMERFC_SCALED_ZM2
   END INTERFACE

   INTERFACE LOG_ERFC
      MODULE PROCEDURE FMLOG_ERFC_FM
      MODULE PROCEDURE FMLOG_ERFC_FM1
      MODULE PROCEDURE FMLOG_ERFC_FM2
   END INTERFACE

   INTERFACE LOG_INTEGRAL
      MODULE PROCEDURE FMLOG_INTEGRAL_FM
      MODULE PROCEDURE FMLOG_INTEGRAL_FM1
      MODULE PROCEDURE FMLOG_INTEGRAL_FM2
   END INTERFACE

   INTERFACE SIN_INTEGRAL
      MODULE PROCEDURE FMSIN_INTEGRAL_FM
      MODULE PROCEDURE FMSIN_INTEGRAL_FM1
      MODULE PROCEDURE FMSIN_INTEGRAL_FM2
   END INTERFACE

   INTERFACE SINH_INTEGRAL
      MODULE PROCEDURE FMSINH_INTEGRAL_FM
      MODULE PROCEDURE FMSINH_INTEGRAL_FM1
      MODULE PROCEDURE FMSINH_INTEGRAL_FM2
   END INTERFACE

 CONTAINS

!                                                                 SIN

   FUNCTION FMSIN_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMSIN(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMSIN_FM

   FUNCTION FMSIN_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMSIN(MA%MZM,RETURN_VALUE%MZM)
   END FUNCTION FMSIN_ZM

   FUNCTION FMSIN_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMSIN(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMSIN_FM1

   FUNCTION FMSIN_ZM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL ZMSIN(MA(J)%MZM,RETURN_VALUE(J)%MZM)
      ENDDO
   END FUNCTION FMSIN_ZM1

   FUNCTION FMSIN_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMSIN(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMSIN_FM2

   FUNCTION FMSIN_ZM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:,:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL ZMSIN(MA(J,K)%MZM,RETURN_VALUE(J,K)%MZM)
         ENDDO
      ENDDO
   END FUNCTION FMSIN_ZM2

!                                                                SINH

   FUNCTION FMSINH_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMSINH(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMSINH_FM

   FUNCTION FMSINH_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMSINH(MA%MZM,RETURN_VALUE%MZM)
   END FUNCTION FMSINH_ZM

   FUNCTION FMSINH_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMSINH(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMSINH_FM1

   FUNCTION FMSINH_ZM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL ZMSINH(MA(J)%MZM,RETURN_VALUE(J)%MZM)
      ENDDO
   END FUNCTION FMSINH_ZM1

   FUNCTION FMSINH_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMSINH(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMSINH_FM2

   FUNCTION FMSINH_ZM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:,:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL ZMSINH(MA(J,K)%MZM,RETURN_VALUE(J,K)%MZM)
         ENDDO
      ENDDO
   END FUNCTION FMSINH_ZM2

!                                                             SPACING

   FUNCTION FMSPACING_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      INTEGER :: KWRNSV
      TYPE(MULTI), SAVE :: MTLVFM
      CALL FM_UNDEF_INP(MA)
      CALL FMABS(MA%MFM,MTLVFM)
      IF (MTLVFM%MP(3) /= 0) THEN
          KWRNSV = KWARN
          KWARN = 0
          CALL FMULP(MTLVFM,RETURN_VALUE%MFM)
          KWARN = KWRNSV
          IF (MTLVFM%MP(2) <= -MXEXP) THEN
              CALL FMTINY(RETURN_VALUE%MFM)
          ENDIF
      ELSE
          CALL FMTINY(RETURN_VALUE%MFM)
      ENDIF
   END FUNCTION FMSPACING_FM

!                                                                SQRT

   FUNCTION FMSQRT_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMSQRT(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMSQRT_FM

   FUNCTION FMSQRT_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMSQRT(MA%MZM,RETURN_VALUE%MZM)
   END FUNCTION FMSQRT_ZM

   FUNCTION FMSQRT_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMSQRT(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMSQRT_FM1

   FUNCTION FMSQRT_ZM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL ZMSQRT(MA(J)%MZM,RETURN_VALUE(J)%MZM)
      ENDDO
   END FUNCTION FMSQRT_ZM1

   FUNCTION FMSQRT_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMSQRT(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMSQRT_FM2

   FUNCTION FMSQRT_ZM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:,:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL ZMSQRT(MA(J,K)%MZM,RETURN_VALUE(J,K)%MZM)
         ENDDO
      ENDDO
   END FUNCTION FMSQRT_ZM2

!                                                                 SUM

   FUNCTION FMSUM1_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA(:),RETURN_VALUE
      INTEGER :: J,JA,MXSAVE,ND2,NDSAVE
      INTENT (IN) :: MA
      TYPE(MULTI), SAVE :: MULVFM,M3LVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      J = MAX(NGRD52,2)
      ND2 = MAX(2*NDIG+J,2)
      NDIG = ND2
      MXSAVE = MXEXP
      MXEXP = MXEXP2
      CALL FMI2M(0,M3LVFM)
      DO J = 1, SIZE(MA)
         JA = LBOUND(MA,DIM=1) + J - 1
         CALL FMEQU(MA(JA)%MFM,MULVFM,NDSAVE,NDIG)
         CALL FMADD_R1(M3LVFM,MULVFM)
      ENDDO
      MXEXP = MXSAVE
      CALL FMEQU(M3LVFM,RETURN_VALUE%MFM,NDIG,NDSAVE)
      NDIG = NDSAVE
   END FUNCTION FMSUM1_FM

   FUNCTION FMSUM2_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA(:,:),RETURN_VALUE
      INTEGER :: J,K,JA,JB,MXSAVE,ND2,NDSAVE
      INTENT (IN) :: MA
      TYPE(MULTI), SAVE :: MULVFM,M3LVFM
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      J = MAX(NGRD52,2)
      ND2 = MAX(2*NDIG+J,2)
      NDIG = ND2
      MXSAVE = MXEXP
      MXEXP = MXEXP2
      CALL FMI2M(0,M3LVFM)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            JA = LBOUND(MA,DIM=1) + J - 1
            JB = LBOUND(MA,DIM=2) + K - 1
            CALL FMEQU(MA(JA,JB)%MFM,MULVFM,NDSAVE,NDIG)
            CALL FMADD_R1(M3LVFM,MULVFM)
         ENDDO
      ENDDO
      MXEXP = MXSAVE
      CALL FMEQU(M3LVFM,RETURN_VALUE%MFM,NDIG,NDSAVE)
      NDIG = NDSAVE
   END FUNCTION FMSUM2_FM

   FUNCTION FMSUM1_IM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA(:),RETURN_VALUE
      INTEGER :: J,JA
      INTENT (IN) :: MA
      TYPE(MULTI), SAVE :: MTLVIM,M3LVIM
      CALL FM_UNDEF_INP(MA)
      CALL IMI2M(0,M3LVIM)
      DO J = 1, SIZE(MA)
         JA = LBOUND(MA,DIM=1) + J - 1
         CALL IMADD(MA(JA)%MIM,M3LVIM,MTLVIM)
         CALL IMEQ(MTLVIM,M3LVIM)
      ENDDO
      CALL IMEQ(M3LVIM,RETURN_VALUE%MIM)
   END FUNCTION FMSUM1_IM

   FUNCTION FMSUM2_IM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA(:,:),RETURN_VALUE
      INTEGER :: J,K,JA,JB
      INTENT (IN) :: MA
      TYPE(MULTI), SAVE :: MTLVIM,M3LVIM
      CALL FM_UNDEF_INP(MA)
      CALL IMI2M(0,M3LVIM)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            JA = LBOUND(MA,DIM=1) + J - 1
            JB = LBOUND(MA,DIM=2) + K - 1
            CALL IMADD(MA(JA,JB)%MIM,M3LVIM,MTLVIM)
            CALL IMEQ(MTLVIM,M3LVIM)
         ENDDO
      ENDDO
      CALL IMEQ(M3LVIM,RETURN_VALUE%MIM)
   END FUNCTION FMSUM2_IM

   FUNCTION FMSUM1_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA(:),RETURN_VALUE
      INTEGER :: J,JA,MXSAVE,ND2,NDSAVE
      INTENT (IN) :: MA
      TYPE(MULTI), SAVE :: MTLVZM(2),MULVZM(2),M3LVZM(2)
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      J = MAX(NGRD52,2)
      ND2 = MAX(2*NDIG+J,2)
      NDIG = ND2
      MXSAVE = MXEXP
      MXEXP = MXEXP2
      CALL ZMI2M(0,M3LVZM)
      DO J = 1, SIZE(MA)
         JA = LBOUND(MA,DIM=1) + J - 1
         CALL ZMEQU(MA(JA)%MZM,MULVZM,NDSAVE,NDIG)
         CALL ZMADD(MULVZM,M3LVZM,MTLVZM)
         CALL ZMEQ(MTLVZM,M3LVZM)
      ENDDO
      MXEXP = MXSAVE
      CALL ZMEQU(M3LVZM,RETURN_VALUE%MZM,NDIG,NDSAVE)
      NDIG = NDSAVE
   END FUNCTION FMSUM1_ZM

   FUNCTION FMSUM2_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA(:,:),RETURN_VALUE
      INTEGER :: J,K,JA,JB,MXSAVE,ND2,NDSAVE
      INTENT (IN) :: MA
      TYPE(MULTI), SAVE :: MTLVZM(2),MULVZM(2),M3LVZM(2)
      CALL FM_UNDEF_INP(MA)
      NDSAVE = NDIG
      J = MAX(NGRD52,2)
      ND2 = MAX(2*NDIG+J,2)
      NDIG = ND2
      MXSAVE = MXEXP
      MXEXP = MXEXP2
      CALL ZMI2M(0,M3LVZM)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            JA = LBOUND(MA,DIM=1) + J - 1
            JB = LBOUND(MA,DIM=2) + K - 1
            CALL ZMEQU(MA(JA,JB)%MZM,MULVZM,NDSAVE,NDIG)
            CALL ZMADD(MULVZM,M3LVZM,MTLVZM)
            CALL ZMEQ(MTLVZM,M3LVZM)
         ENDDO
      ENDDO
      MXEXP = MXSAVE
      CALL ZMEQU(M3LVZM,RETURN_VALUE%MZM,NDIG,NDSAVE)
      NDIG = NDSAVE
   END FUNCTION FMSUM2_ZM

!                                                                 TAN

   FUNCTION FMTAN_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMTAN(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMTAN_FM

   FUNCTION FMTAN_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMTAN(MA%MZM,RETURN_VALUE%MZM)
   END FUNCTION FMTAN_ZM

   FUNCTION FMTAN_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMTAN(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMTAN_FM1

   FUNCTION FMTAN_ZM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL ZMTAN(MA(J)%MZM,RETURN_VALUE(J)%MZM)
      ENDDO
   END FUNCTION FMTAN_ZM1

   FUNCTION FMTAN_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMTAN(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMTAN_FM2

   FUNCTION FMTAN_ZM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:,:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL ZMTAN(MA(J,K)%MZM,RETURN_VALUE(J,K)%MZM)
         ENDDO
      ENDDO
   END FUNCTION FMTAN_ZM2

!                                                                TANH

   FUNCTION FMTANH_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMTANH(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMTANH_FM

   FUNCTION FMTANH_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMTANH(MA%MZM,RETURN_VALUE%MZM)
   END FUNCTION FMTANH_ZM

   FUNCTION FMTANH_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMTANH(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMTANH_FM1

   FUNCTION FMTANH_ZM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL ZMTANH(MA(J)%MZM,RETURN_VALUE(J)%MZM)
      ENDDO
   END FUNCTION FMTANH_ZM1

   FUNCTION FMTANH_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMTANH(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMTANH_FM2

   FUNCTION FMTANH_ZM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:,:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL ZMTANH(MA(J,K)%MZM,RETURN_VALUE(J,K)%MZM)
         ENDDO
      ENDDO
   END FUNCTION FMTANH_ZM2

!                                                                TINY

   FUNCTION FMTINY_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FMTINY(RETURN_VALUE%MFM)
      IF (ALLOCATED(MA%MFM%MP)) THEN
          IF (SIZE(MA%MFM%MP) <= 2) CALL FMMPYI_R1(RETURN_VALUE%MFM,1)
      ENDIF
   END FUNCTION FMTINY_FM

   FUNCTION FMTINY_IM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      TYPE(MULTI), SAVE :: MTLVIM
      CALL IMI2M(1,RETURN_VALUE%MIM)
      IF (ALLOCATED(MA%MIM%MP)) THEN
          IF (SIZE(MA%MIM%MP) <= 2) CALL IMMPYI(RETURN_VALUE%MIM,1,MTLVIM)
      ENDIF
   END FUNCTION FMTINY_IM

   FUNCTION FMTINY_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      TYPE(MULTI), SAVE :: MTLVFM,MTLVZM(2)
      CALL FMTINY(MTLVFM)
      CALL ZMCMPX(MTLVFM,MTLVFM,RETURN_VALUE%MZM)
      IF (ALLOCATED(MA%MZM(1)%MP)) THEN
          IF (SIZE(MA%MZM(1)%MP) <= 2) CALL ZMMPYI(RETURN_VALUE%MZM,1,MTLVZM)
      ENDIF
   END FUNCTION FMTINY_ZM

!                                                           TRANSPOSE

   FUNCTION FMTRANSPOSE_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA(:,:)
      TYPE (FM), DIMENSION(SIZE(MA,DIM=2),SIZE(MA,DIM=1)) :: RETURN_VALUE
      INTEGER :: I,J
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO I = 1, SIZE(MA,DIM=1)
         DO J = 1, SIZE(MA,DIM=2)
            CALL FMEQ(MA(I,J)%MFM,RETURN_VALUE(J,I)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMTRANSPOSE_FM

   FUNCTION FMTRANSPOSE_IM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA(:,:)
      TYPE (IM), DIMENSION(SIZE(MA,DIM=2),SIZE(MA,DIM=1)) :: RETURN_VALUE
      INTEGER :: I,J
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO I = 1, SIZE(MA,DIM=1)
         DO J = 1, SIZE(MA,DIM=2)
            CALL IMEQ(MA(I,J)%MIM,RETURN_VALUE(J,I)%MIM)
         ENDDO
      ENDDO
   END FUNCTION FMTRANSPOSE_IM

   FUNCTION FMTRANSPOSE_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA(:,:)
      TYPE (ZM), DIMENSION(SIZE(MA,DIM=2),SIZE(MA,DIM=1)) :: RETURN_VALUE
      INTEGER :: I,J
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO I = 1, SIZE(MA,DIM=1)
         DO J = 1, SIZE(MA,DIM=2)
            CALL ZMEQ(MA(I,J)%MZM,RETURN_VALUE(J,I)%MZM)
         ENDDO
      ENDDO
   END FUNCTION FMTRANSPOSE_ZM

!                                                           FM_FORMAT

   FUNCTION FMFORMAT_FM(FMT,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      CHARACTER(*) :: FMT
      TYPE (FM) :: MA
      CHARACTER(200) :: RETURN_VALUE
      INTENT (IN) :: FMT,MA
      CALL FM_UNDEF_INP(MA)
      CALL FMFORM(FMT,MA%MFM,RETURN_VALUE)
   END FUNCTION FMFORMAT_FM

!                                                           IM_FORMAT

   FUNCTION IMFORMAT_IM(FMT,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      CHARACTER(*) :: FMT
      CHARACTER(200) :: RETURN_VALUE
      TYPE (IM) :: MA
      INTENT (IN) :: FMT,MA
      CALL FM_UNDEF_INP(MA)
      CALL IMFORM(FMT,MA%MIM,RETURN_VALUE)
   END FUNCTION IMFORMAT_IM

!                                                           ZM_FORMAT

   FUNCTION ZMFORMAT_ZM(FMTR,FMTI,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      CHARACTER(*) :: FMTR,FMTI
      CHARACTER(200) :: RETURN_VALUE
      TYPE (ZM) :: MA
      INTENT (IN) :: FMTR,FMTI,MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMFORM(FMTR,FMTI,MA%MZM,RETURN_VALUE)
   END FUNCTION ZMFORMAT_ZM

!                                                                 GCD

   FUNCTION GCD_IM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,RETURN_VALUE
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMGCD(MA%MIM,MB%MIM,RETURN_VALUE%MIM)
   END FUNCTION GCD_IM

!                                                        MULTIPLY_MOD

   FUNCTION MULTIPLYMOD_IM(MA,MB,MC)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC,RETURN_VALUE
      INTENT (IN) :: MA,MB,MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FM_UNDEF_INP(MC)
      CALL IMMPYM(MA%MIM,MB%MIM,MC%MIM,RETURN_VALUE%MIM)
   END FUNCTION MULTIPLYMOD_IM

!                                                           POWER_MOD

   FUNCTION POWERMOD_IM(MA,MB,MC)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,MC,RETURN_VALUE
      INTENT (IN) :: MA,MB,MC
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FM_UNDEF_INP(MC)
      CALL IMPMOD(MA%MIM,MB%MIM,MC%MIM,RETURN_VALUE%MIM)
   END FUNCTION POWERMOD_IM

!                                                           BERNOULLI

   FUNCTION FMBERNOULLI_FM(N)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: RETURN_VALUE
      INTEGER :: N
      INTENT (IN) :: N
      CALL FMBERNOULLI(N,RETURN_VALUE%MFM)
   END FUNCTION FMBERNOULLI_FM

!                                                                BETA

   FUNCTION FMBETA_FM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,RETURN_VALUE
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMBETA(MA%MFM,MB%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMBETA_FM

!                                                            BINOMIAL

   FUNCTION FMBINOMIAL_FM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,RETURN_VALUE
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMCOMB(MA%MFM,MB%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMBINOMIAL_FM

   FUNCTION FMBINOMIAL_IM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,MB,RETURN_VALUE
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL IMCOMB(MA%MIM,MB%MIM,RETURN_VALUE%MIM)
   END FUNCTION FMBINOMIAL_IM

   FUNCTION FMBINOMIAL_I(N,K)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: N,K
      TYPE (IM) :: RETURN_VALUE
      INTENT (IN) :: N,K
      CALL IMCOMBI(N,K,RETURN_VALUE%MIM)
   END FUNCTION FMBINOMIAL_I

!                                                           FACTORIAL

   FUNCTION FMFACTORIAL_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMFACT(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMFACTORIAL_FM

   FUNCTION FMFACTORIAL_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMFACT(MA%MZM,RETURN_VALUE%MZM)
   END FUNCTION FMFACTORIAL_ZM

   FUNCTION FMFACTORIAL_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMFACT(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMFACTORIAL_FM1

   FUNCTION FMFACTORIAL_ZM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL ZMFACT(MA(J)%MZM,RETURN_VALUE(J)%MZM)
      ENDDO
   END FUNCTION FMFACTORIAL_ZM1

   FUNCTION FMFACTORIAL_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMFACT(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMFACTORIAL_FM2

   FUNCTION FMFACTORIAL_ZM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:,:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL ZMFACT(MA(J,K)%MZM,RETURN_VALUE(J,K)%MZM)
         ENDDO
      ENDDO
   END FUNCTION FMFACTORIAL_ZM2

   FUNCTION FMFACTORIAL_IM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      INTEGER :: IVAL
      CALL FM_UNDEF_INP(MA)
      CALL IMM2I(MA%MIM,IVAL)
      IF (KFLAG == 0) THEN
          CALL IMFACT(IVAL,RETURN_VALUE%MIM)
      ELSE
          CALL IMST2M(' UNKNOWN ',RETURN_VALUE%MIM)
          KFLAG = 0
      ENDIF
   END FUNCTION FMFACTORIAL_IM

   FUNCTION FMFACTORIAL_IM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM), DIMENSION(:) :: MA
      TYPE (IM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: IVAL,J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL IMM2I(MA(J)%MIM,IVAL)
         IF (KFLAG == 0) THEN
             CALL IMFACT(IVAL,RETURN_VALUE(J)%MIM)
         ELSE
             CALL IMST2M(' UNKNOWN ',RETURN_VALUE(J)%MIM)
             KFLAG = 0
         ENDIF
      ENDDO
   END FUNCTION FMFACTORIAL_IM1

   FUNCTION FMFACTORIAL_IM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM), DIMENSION(:,:) :: MA
      TYPE (IM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: IVAL,J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL IMM2I(MA(J,K)%MIM,IVAL)
            IF (KFLAG == 0) THEN
                CALL IMFACT(IVAL,RETURN_VALUE(J,K)%MIM)
            ELSE
                CALL IMST2M(' UNKNOWN ',RETURN_VALUE(J,K)%MIM)
                KFLAG = 0
            ENDIF
         ENDDO
      ENDDO
   END FUNCTION FMFACTORIAL_IM2

   FUNCTION FMFACTORIAL_I(IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (IM) :: RETURN_VALUE
      INTEGER :: IVAL
      INTENT (IN) :: IVAL
      CALL IMFACT(IVAL,RETURN_VALUE%MIM)
   END FUNCTION FMFACTORIAL_I

   FUNCTION FMFACTORIAL_I1(IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER, DIMENSION(:) :: IVAL
      TYPE (IM), DIMENSION(SIZE(IVAL)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: IVAL
      N = SIZE(IVAL)
      DO J = 1, N
         CALL IMFACT(IVAL(J),RETURN_VALUE(J)%MIM)
      ENDDO
   END FUNCTION FMFACTORIAL_I1

   FUNCTION FMFACTORIAL_I2(IVAL)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER, DIMENSION(:,:) :: IVAL
      TYPE (IM), DIMENSION(SIZE(IVAL,DIM=1),SIZE(IVAL,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: IVAL
      DO J = 1, SIZE(IVAL,DIM=1)
         DO K = 1, SIZE(IVAL,DIM=2)
            CALL IMFACT(IVAL(J,K),RETURN_VALUE(J,K)%MIM)
         ENDDO
      ENDDO
   END FUNCTION FMFACTORIAL_I2

!                                                               GAMMA

   FUNCTION FMGAMMA_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMGAM(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMGAMMA_FM

   FUNCTION FMGAMMA_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMGAM(MA%MZM,RETURN_VALUE%MZM)
   END FUNCTION FMGAMMA_ZM

   FUNCTION FMGAMMA_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMGAM(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMGAMMA_FM1

   FUNCTION FMGAMMA_ZM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL ZMGAM(MA(J)%MZM,RETURN_VALUE(J)%MZM)
      ENDDO
   END FUNCTION FMGAMMA_ZM1

   FUNCTION FMGAMMA_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMGAM(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMGAMMA_FM2

   FUNCTION FMGAMMA_ZM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:,:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL ZMGAM(MA(J,K)%MZM,RETURN_VALUE(J,K)%MZM)
         ENDDO
      ENDDO
   END FUNCTION FMGAMMA_ZM2

!                                                     INCOMPLETE_BETA

   FUNCTION FMINCOMPLETE_BETA_FM(MX,MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MX,MA,MB,RETURN_VALUE
      INTENT (IN) :: MX,MA,MB
      CALL FM_UNDEF_INP(MX)
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMIBTA(MX%MFM,MA%MFM,MB%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMINCOMPLETE_BETA_FM

!                                                   INCOMPLETE_GAMMA1

   FUNCTION FMINCOMPLETE_GAMMA1_FM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,RETURN_VALUE
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMIGM1(MA%MFM,MB%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMINCOMPLETE_GAMMA1_FM

!                                                   INCOMPLETE_GAMMA2

   FUNCTION FMINCOMPLETE_GAMMA2_FM(MA,MB)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,MB,RETURN_VALUE
      INTENT (IN) :: MA,MB
      CALL FM_UNDEF_INP(MA)
      CALL FM_UNDEF_INP(MB)
      CALL FMIGM2(MA%MFM,MB%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMINCOMPLETE_GAMMA2_FM

!                                                           LOG_GAMMA

   FUNCTION FMLOG_GAMMA_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMLNGM(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMLOG_GAMMA_FM

   FUNCTION FMLOG_GAMMA_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMLNGM(MA%MZM,RETURN_VALUE%MZM)
   END FUNCTION FMLOG_GAMMA_ZM

   FUNCTION FMLOG_GAMMA_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMLNGM(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMLOG_GAMMA_FM1

   FUNCTION FMLOG_GAMMA_ZM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL ZMLNGM(MA(J)%MZM,RETURN_VALUE(J)%MZM)
      ENDDO
   END FUNCTION FMLOG_GAMMA_ZM1

   FUNCTION FMLOG_GAMMA_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMLNGM(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMLOG_GAMMA_FM2

   FUNCTION FMLOG_GAMMA_ZM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:,:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL ZMLNGM(MA(J,K)%MZM,RETURN_VALUE(J,K)%MZM)
         ENDDO
      ENDDO
   END FUNCTION FMLOG_GAMMA_ZM2

!                                                           POLYGAMMA

   FUNCTION FMPOLYGAMMA_FM(N,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTEGER :: N
      INTENT (IN) :: N,MA
      CALL FM_UNDEF_INP(MA)
      CALL FMPGAM(N,MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMPOLYGAMMA_FM

!                                                          POCHHAMMER

   FUNCTION FMPOCHHAMMER_FM(MA,N)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTEGER :: N
      INTENT (IN) :: N,MA
      CALL FM_UNDEF_INP(MA)
      CALL FMPOCH(MA%MFM,N,RETURN_VALUE%MFM)
   END FUNCTION FMPOCHHAMMER_FM

!                                                                 PSI

   FUNCTION FMPSI_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMPSI(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMPSI_FM

   FUNCTION FMPSI_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMPSI(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMPSI_FM1

   FUNCTION FMPSI_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMPSI(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMPSI_FM2

!                                                            BESSEL_J

   FUNCTION FMBESSEL_J_FM(N,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTEGER :: N
      INTENT (IN) :: N,MA
      CALL FM_UNDEF_INP(MA)
      CALL FMBESJ(N,MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMBESSEL_J_FM

!                                                            BESSEL_J0

   FUNCTION FMBESSEL_J0_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMBESJ(0,MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMBESSEL_J0_FM

!                                                            BESSEL_J1

   FUNCTION FMBESSEL_J1_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMBESJ(1,MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMBESSEL_J1_FM

!                                                            BESSEL_JN

   FUNCTION FMBESSEL_JN_FM(N,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTEGER :: N
      INTENT (IN) :: N,MA
      CALL FM_UNDEF_INP(MA)
      CALL FMBESJ(N,MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMBESSEL_JN_FM

!                                                            BESSEL_JN2

   FUNCTION FMBESSEL_JN2_FM(N1,N2,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: N1,N2,J
      TYPE (FM) :: MA,RETURN_VALUE(ABS(N2-N1)+1)
      TYPE(MULTI), ALLOCATABLE :: A(:)
      INTENT (IN) :: N1,N2,MA
      CALL FM_UNDEF_INP(MA)
      ALLOCATE(A(ABS(N2-N1)+1))
      CALL FMBESJ2(N1,N2,MA%MFM,A)
      DO J = 1, ABS(N2-N1)+1
         CALL FMEQ(A(J),RETURN_VALUE(J)%MFM)
      ENDDO
      DEALLOCATE(A)
   END FUNCTION FMBESSEL_JN2_FM

!                                                            BESSEL_Y

   FUNCTION FMBESSEL_Y_FM(N,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTEGER :: N
      INTENT (IN) :: N,MA
      CALL FM_UNDEF_INP(MA)
      CALL FMBESY(N,MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMBESSEL_Y_FM

!                                                            BESSEL_Y0

   FUNCTION FMBESSEL_Y0_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMBESY(0,MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMBESSEL_Y0_FM

!                                                            BESSEL_Y1

   FUNCTION FMBESSEL_Y1_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMBESY(1,MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMBESSEL_Y1_FM

!                                                            BESSEL_YN

   FUNCTION FMBESSEL_YN_FM(N,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTEGER :: N
      INTENT (IN) :: N,MA
      CALL FM_UNDEF_INP(MA)
      CALL FMBESY(N,MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMBESSEL_YN_FM

!                                                            BESSEL_YN2

   FUNCTION FMBESSEL_YN2_FM(N1,N2,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      INTEGER :: N1,N2,J
      TYPE (FM) :: MA,RETURN_VALUE(ABS(N2-N1)+1)
      TYPE(MULTI), ALLOCATABLE :: A(:)
      INTENT (IN) :: N1,N2,MA
      CALL FM_UNDEF_INP(MA)
      ALLOCATE(A(ABS(N2-N1)+1))
      CALL FMBESY2(N1,N2,MA%MFM,A)
      DO J = 1, ABS(N2-N1)+1
         CALL FMEQ(A(J),RETURN_VALUE(J)%MFM)
      ENDDO
      DEALLOCATE(A)
   END FUNCTION FMBESSEL_YN2_FM

!                                                        COS_INTEGRAL

   FUNCTION FMCOS_INTEGRAL_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMCI(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMCOS_INTEGRAL_FM

   FUNCTION FMCOS_INTEGRAL_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMCI(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMCOS_INTEGRAL_FM1

   FUNCTION FMCOS_INTEGRAL_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMCI(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMCOS_INTEGRAL_FM2

!                                                       COSH_INTEGRAL

   FUNCTION FMCOSH_INTEGRAL_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMCHI(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMCOSH_INTEGRAL_FM

   FUNCTION FMCOSH_INTEGRAL_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMCHI(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMCOSH_INTEGRAL_FM1

   FUNCTION FMCOSH_INTEGRAL_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMCHI(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMCOSH_INTEGRAL_FM2

!                                                     EXP_INTEGRAL_EI

   FUNCTION FMEXP_INTEGRAL_EI_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMEI(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMEXP_INTEGRAL_EI_FM

   FUNCTION FMEXP_INTEGRAL_EI_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMEI(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMEXP_INTEGRAL_EI_FM1

   FUNCTION FMEXP_INTEGRAL_EI_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMEI(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMEXP_INTEGRAL_EI_FM2

!                                                     EXP_INTEGRAL_EN

   FUNCTION FMEXP_INTEGRAL_EN_FM(N,MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTEGER :: N
      INTENT (IN) :: N,MA
      CALL FM_UNDEF_INP(MA)
      CALL FMEN(N,MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMEXP_INTEGRAL_EN_FM

!                                                           FRESNEL_C

   FUNCTION FMFRESNEL_C_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMC(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMFRESNEL_C_FM

   FUNCTION FMFRESNEL_C_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMC(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMFRESNEL_C_FM1

   FUNCTION FMFRESNEL_C_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMC(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMFRESNEL_C_FM2

!                                                           FRESNEL_S

   FUNCTION FMFRESNEL_S_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMS(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMFRESNEL_S_FM

   FUNCTION FMFRESNEL_S_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMS(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMFRESNEL_S_FM1

   FUNCTION FMFRESNEL_S_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMS(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMFRESNEL_S_FM2

!                                                                 ERF

   FUNCTION FMERF_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMERF(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMERF_FM

   FUNCTION FMERF_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMERF(MA%MZM,RETURN_VALUE%MZM)
   END FUNCTION FMERF_ZM

   FUNCTION FMERF_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMERF(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMERF_FM1

   FUNCTION FMERF_ZM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL ZMERF(MA(J)%MZM,RETURN_VALUE(J)%MZM)
      ENDDO
   END FUNCTION FMERF_ZM1

   FUNCTION FMERF_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMERF(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMERF_FM2

   FUNCTION FMERF_ZM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:,:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL ZMERF(MA(J,K)%MZM,RETURN_VALUE(J,K)%MZM)
         ENDDO
      ENDDO
   END FUNCTION FMERF_ZM2

!                                                                ERFC

   FUNCTION FMERFC_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMERFC(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMERFC_FM

   FUNCTION FMERFC_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMERFC(MA%MZM,RETURN_VALUE%MZM)
   END FUNCTION FMERFC_ZM

   FUNCTION FMERFC_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMERFC(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMERFC_FM1

   FUNCTION FMERFC_ZM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL ZMERFC(MA(J)%MZM,RETURN_VALUE(J)%MZM)
      ENDDO
   END FUNCTION FMERFC_ZM1

   FUNCTION FMERFC_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMERFC(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMERFC_FM2

   FUNCTION FMERFC_ZM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:,:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL ZMERFC(MA(J,K)%MZM,RETURN_VALUE(J,K)%MZM)
         ENDDO
      ENDDO
   END FUNCTION FMERFC_ZM2

!                                                                ERFC_SCALED

   FUNCTION FMERFC_SCALED_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMERFCS(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMERFC_SCALED_FM

   FUNCTION FMERFC_SCALED_ZM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL ZMERFC_SC(MA%MZM,RETURN_VALUE%MZM)
   END FUNCTION FMERFC_SCALED_ZM

   FUNCTION FMERFC_SCALED_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMERFCS(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMERFC_SCALED_FM1

   FUNCTION FMERFC_SCALED_ZM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL ZMERFC_SC(MA(J)%MZM,RETURN_VALUE(J)%MZM)
      ENDDO
   END FUNCTION FMERFC_SCALED_ZM1

   FUNCTION FMERFC_SCALED_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMERFCS(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMERFC_SCALED_FM2

   FUNCTION FMERFC_SCALED_ZM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (ZM), DIMENSION(:,:) :: MA
      TYPE (ZM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL ZMERFC_SC(MA(J,K)%MZM,RETURN_VALUE(J,K)%MZM)
         ENDDO
      ENDDO
   END FUNCTION FMERFC_SCALED_ZM2

!                                                            LOG_ERFC

   FUNCTION FMLOG_ERFC_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMLERC(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMLOG_ERFC_FM

   FUNCTION FMLOG_ERFC_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMLERC(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMLOG_ERFC_FM1

   FUNCTION FMLOG_ERFC_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMLERC(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMLOG_ERFC_FM2

!                                                        LOG_INTEGRAL

   FUNCTION FMLOG_INTEGRAL_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMLI(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMLOG_INTEGRAL_FM

   FUNCTION FMLOG_INTEGRAL_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMLI(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMLOG_INTEGRAL_FM1

   FUNCTION FMLOG_INTEGRAL_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMLI(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMLOG_INTEGRAL_FM2

!                                                        SIN_INTEGRAL

   FUNCTION FMSIN_INTEGRAL_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMSI(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMSIN_INTEGRAL_FM

   FUNCTION FMSIN_INTEGRAL_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMSI(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMSIN_INTEGRAL_FM1

   FUNCTION FMSIN_INTEGRAL_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMSI(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMSIN_INTEGRAL_FM2

!                                                       SINH_INTEGRAL

   FUNCTION FMSINH_INTEGRAL_FM(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM) :: MA,RETURN_VALUE
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      CALL FMSHI(MA%MFM,RETURN_VALUE%MFM)
   END FUNCTION FMSINH_INTEGRAL_FM

   FUNCTION FMSINH_INTEGRAL_FM1(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA)) :: RETURN_VALUE
      INTEGER :: J,N
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      N = SIZE(MA)
      DO J = 1, N
         CALL FMSHI(MA(J)%MFM,RETURN_VALUE(J)%MFM)
      ENDDO
   END FUNCTION FMSINH_INTEGRAL_FM1

   FUNCTION FMSINH_INTEGRAL_FM2(MA)     RESULT (RETURN_VALUE)
      USE ModLib_FMVALS
      IMPLICIT NONE
      TYPE (FM), DIMENSION(:,:) :: MA
      TYPE (FM), DIMENSION(SIZE(MA,DIM=1),SIZE(MA,DIM=2)) :: RETURN_VALUE
      INTEGER :: J,K
      INTENT (IN) :: MA
      CALL FM_UNDEF_INP(MA)
      DO J = 1, SIZE(MA,DIM=1)
         DO K = 1, SIZE(MA,DIM=2)
            CALL FMSHI(MA(J,K)%MFM,RETURN_VALUE(J,K)%MFM)
         ENDDO
      ENDDO
   END FUNCTION FMSINH_INTEGRAL_FM2

 END MODULE ModLib_FMZM_9
