MODULE ModLib_FENIA

! Module ModLib_FENIA contains data and the interfaces of the F.EN.I.A. library.

!*******************************************************************************
! Evangelos Bertakis, F.EN.I.A. Project, 2009                                  *
!*******************************************************************************

! List of interfaces:

! 1. acosh (function)
! 2. asinh (function)
! 3. fact (function)
! 4. LinkedListReal (subroutine)
! 5. LinkedListCharacter (subroutine)
! 6. LinkedListInteger (subroutine)
! 7. FileManager (function)
! 8. StringReal (function)
! 9. StringInteger (function)
! 10. LinearIntExp (function)
! 11. SVG_ColorMap (function)
! 12. SVG_Finalize (subroutine)
! 13. SVG_Initialize (subroutine)
! 14. SVG_Ellipse (subroutine)
! 15. SVG_Rect (subroutine)
! 16. EQP_StringFilter (subroutine)
! 17. EQP_Calculator (function)
! 18. ArrayExpandReal (subroutine)
! 19. ArrayExpandInteger (subroutine)
! 20. NumberReal (function)
! 21. EQP_EquationParser (function)
! 22. HeapsortInteger (subroutine)
! 23. HeapsortCharacterLength (subroutine)
! 24. SVG_Square (subroutine)
! 25. SVG_Line (subroutine)
! 26. SVG_Circle (subroutine)
! 27. SVG_Polyline (subroutine)
! 28. SVG_GroupStart (subroutine)
! 29. SVG_GroupEnd (subroutine)
! 30. SVG_Polygon (subroutine)
! 31. SVG_Text (subroutine)
! 32. SVG_ActionButton (subroutine)
! 33. SVG_Vanish (subroutine)
! 34. SVG_GroupSelect (subroutine)
! 35. SVG_BezierQuadratic (subroutine)
! 36. SVG_GridStructured (subroutine)
! 37. SVG_ColorBar (subroutine)
! 38. SVG_Resurrect (subroutine)
! 39. SVG_Triangle (subroutine)
! 40. SVG_Cross (subroutine)
! 41. SVG_Vector (subroutine)
! 42. FormatReal (function)
! 43. SVG_VectorFieldStructuredg (subroutine)
! 44. SVG_GridPixel (subroutine)
! 45. SVG_VectorFieldPixel (subroutine)
! 46. EQP_InequalityParser (function)
! 47. ArrayExpandCharacter (subroutine)
! 48. CrossPoint (subroutine)
! 49. SVG_TernaryPlot (subroutine)
! 50. HTML_Initialize (subroutine)
! 51. HTML_Finalize (subroutine)
! 52. HTML_Table (subroutine)
! 53. SVG_Link (subroutine)
! 54. SVG_LinkButton (subroutine)
! 55. HTML_Heading (subroutine)
! 56. HTML_Paragraph (subroutine)
! 57. HTML_Link (subroutine)
! 58. SVG_CartesianPlot (subroutine)
! 59. AxesSetup (subroutine)
! 60. SVG_CartesianPlotDefault (subroutine)
! 61. VTK_Initialize (subroutine)
! 62. VTK_Finalize (subroutine)
! 63. VTK_Sphere (subroutine)
! 64. VTK_Path (subroutine)
! 65. VTK_Surface (subroutine)
! 66. VTK_VectorField (subroutine)
! 67. VTK_MultiLine (subroutine)

! ------------------------------------------------------------------------------
    IMPLICIT NONE

! Determine whether to pause on warnings or not:
LOGICAL,PARAMETER,PUBLIC:: WARNINGS_PAUSE=.FALSE.

! Default string length:
INTEGER,PARAMETER,PUBLIC:: DEFAULT_STRING_LENGTH=80

! Determine the precision for the calculations:
!integer,parameter,public:: srk=selected_real_kind(p=6,r=37) ! single
INTEGER,PARAMETER,PUBLIC:: SRK=SELECTED_REAL_KIND(P=15,R=307) ! double

! Define the dimensions of the SVG viewBox:
REAL(SRK),PUBLIC:: VIEWBOX_WIDTH=1200.0_SRK ! px
REAL(SRK),PUBLIC:: VIEWBOX_HEIGHT=800.0_SRK ! px

! Mathematical constants (with precision to spare):
REAL(SRK),PARAMETER,PUBLIC:: PI=3.141592653589793238462643383279502884197_SRK

INTERFACE

    ! 3. FACT (function)
    MODULE FUNCTION FACT(X)
    REAL(SRK),INTENT(IN):: X
    REAL(SRK):: FACT
    END FUNCTION FACT

    ! BezierQuadraticControl (function)
    MODULE FUNCTION BezierQuadraticControl(A,B,C)
    REAL(SRK),INTENT(IN):: A(2),B(2),C(2)
    REAL(SRK):: BezierQuadraticControl(2)
    END FUNCTION

    ! 4. LinkedListReal (subroutine)
    MODULE SUBROUTINE LinkedListReal(NUMERICAL_VALUE,LIST_POINTER)
    REAL(SRK),OPTIONAL,INTENT(IN):: NUMERICAL_VALUE
    REAL(SRK),POINTER,OPTIONAL:: LIST_POINTER(:)
    END SUBROUTINE LinkedListReal

    ! 5. LinkedListCharacter (subroutine)
    MODULE SUBROUTINE LinkedListCharacter(CHARACTER_VALUE,LIST_POINTER)
    CHARACTER,OPTIONAL,INTENT(IN):: CHARACTER_VALUE*(*)
    CHARACTER,POINTER,OPTIONAL:: LIST_POINTER(:)*(*)
    END SUBROUTINE LinkedListCharacter

    ! 6. LinkedListInteger (subroutine)
    MODULE SUBROUTINE LinkedListInteger(NUMERICAL_VALUE,LIST_POINTER)
    INTEGER,OPTIONAL,INTENT(IN):: NUMERICAL_VALUE
    INTEGER,POINTER,OPTIONAL:: LIST_POINTER(:)
    END SUBROUTINE LinkedListInteger

    ! 7. FileManager (function)
    MODULE FUNCTION FileManager(FILENAME,CONNECTED)
    CHARACTER,INTENT(IN):: FILENAME*(*)
    LOGICAL,OPTIONAL,INTENT(OUT):: CONNECTED
    INTEGER:: FileManager
    END FUNCTION FileManager

    ! 8. StringReal (function)
    MODULE FUNCTION StringReal(NUMERICAL_VALUE)
    REAL(SRK),INTENT(IN):: NUMERICAL_VALUE
    CHARACTER:: StringReal*(DEFAULT_STRING_LENGTH)
    END FUNCTION StringReal

    ! 9. StringInteger (function)
    MODULE FUNCTION StringInteger(NUMERICAL_VALUE)
    INTEGER,INTENT(IN):: NUMERICAL_VALUE
    CHARACTER:: StringInteger*(DEFAULT_STRING_LENGTH)
    END FUNCTION StringInteger

    ! 10. LinearIntExp (function)
    MODULE FUNCTION LinearIntExp(X1,X2,Y1,Y2,X_GIVEN)
    REAL(SRK),INTENT(IN):: X1,X2,Y1,Y2,X_GIVEN
    REAL(SRK):: LinearIntExp
    END FUNCTION LinearIntExp

    ! 11. SVG_ColorMap (function)
    MODULE FUNCTION SVG_ColorMap(NUMERICAL_VALUE,MINIMUM,MAXIMUM,GRAYSCALE)
    REAL(SRK),INTENT(IN):: NUMERICAL_VALUE,MINIMUM,MAXIMUM
    LOGICAL,OPTIONAL,INTENT(IN):: GRAYSCALE
    INTEGER:: SVG_ColorMap(3)
    END FUNCTION SVG_ColorMap

    ! 12. SVG_Finalize (subroutine)
    MODULE SUBROUTINE SVG_Finalize(OUTPUT_FILE)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    END SUBROUTINE SVG_Finalize

    ! 13. SVG_Initialize (subroutine)
    MODULE SUBROUTINE SVG_Initialize(OUTPUT_FILE)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    END SUBROUTINE SVG_Initialize

    ! 14. SVG_Ellipse (subroutine)
    MODULE SUBROUTINE SVG_Ellipse(OUTPUT_FILE,X,Y,RADIUS_X,RADIUS_Y, &
        & STROKE_WIDTH,FILL_OPACITY,STROKE_RGB,FILL_RGB, &
        & ROTATE,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X,Y,RADIUS_X,RADIUS_Y,STROKE_WIDTH,FILL_OPACITY
    INTEGER,INTENT(IN):: STROKE_RGB(3),FILL_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: ROTATE(3),SCALAR_VALUE(:)
    END SUBROUTINE SVG_Ellipse

    ! 15. SVG_Rect (subroutine)
    MODULE SUBROUTINE SVG_Rect(OUTPUT_FILE,X,Y,WIDTH,HEIGHT, &
        & STROKE_WIDTH,FILL_OPACITY,STROKE_RGB,FILL_RGB, &
        & ROTATE,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X,Y,WIDTH,HEIGHT,STROKE_WIDTH,FILL_OPACITY
    INTEGER,INTENT(IN):: STROKE_RGB(3),FILL_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: ROTATE(3),SCALAR_VALUE(:)
    END SUBROUTINE SVG_Rect

    ! 16. EQP_StringFilter (subroutine)
    MODULE SUBROUTINE EQP_STRINGFILTER(STRING,WORDS,LOCATIONS_POINTER,INVENTORY_POINTER)
    CHARACTER,INTENT(IN):: WORDS(:)*(*)
    CHARACTER,INTENT(INOUT):: STRING*(*)
    CHARACTER,POINTER:: INVENTORY_POINTER(:)*(*)
    INTEGER,POINTER:: LOCATIONS_POINTER(:)
    END SUBROUTINE EQP_STRINGFILTER

    ! 17. EQP_Calculator (function)
    MODULE FUNCTION EQP_Calculator(NUMBER_POSITION,NUMBER_VALUE, &
        FUNCTION_POSITION,FUNCTION_TYPE,OPERATOR_POSITION,OPERATOR_TYPE)
    REAL(SRK):: EQP_Calculator
    REAL(SRK),POINTER:: NUMBER_VALUE(:)
    INTEGER,POINTER:: NUMBER_POSITION(:)
    INTEGER,POINTER:: FUNCTION_POSITION(:),OPERATOR_POSITION(:)
    CHARACTER,POINTER:: FUNCTION_TYPE(:)*(*),OPERATOR_TYPE(:)*(*)
    END FUNCTION EQP_Calculator

    ! 18. ArrayExpandReal (subroutine)
    MODULE SUBROUTINE ArrayExpandReal(ARRAY_POINTER,SCALAR_VALUE)
    REAL(SRK),INTENT(IN):: SCALAR_VALUE
    REAL(SRK),POINTER:: ARRAY_POINTER(:)
    END SUBROUTINE ArrayExpandReal

    ! 19. ArrayExpandInteger (subroutine)
    MODULE SUBROUTINE ArrayExpandInteger(ARRAY_POINTER,SCALAR_VALUE)
    INTEGER,INTENT(IN):: SCALAR_VALUE
    INTEGER,POINTER:: ARRAY_POINTER(:)
    END SUBROUTINE ArrayExpandInteger

    ! 20. NumberReal (function)
    MODULE FUNCTION NumberReal(STRING)
    CHARACTER,INTENT(IN):: STRING*(*)
    REAL(SRK):: NumberReal
    END FUNCTION NumberReal

    ! 21. EQP_EquationParser (function)
    MODULE FUNCTION EQP_EquationParser(EQUATION,VARIABLE_NAMES,VARIABLE_VALUES)
    CHARACTER,INTENT(IN):: EQUATION*(*)
    CHARACTER,POINTER:: VARIABLE_NAMES(:)*(*)
    REAL(SRK),POINTER:: VARIABLE_VALUES(:)
    REAL(SRK):: EQP_EquationParser
    END FUNCTION EQP_EquationParser

    ! 22. HeapsortInteger (subroutine)
    MODULE SUBROUTINE HeapsortInteger(ARRAY,SORTED_INDEX)
    INTEGER,INTENT(INOUT):: ARRAY(:)
    INTEGER,OPTIONAL,INTENT(OUT):: SORTED_INDEX(:)
    END SUBROUTINE HeapsortInteger

    ! 23. HeapsortCharacterLength (subroutine)
    MODULE SUBROUTINE HeapsortCharacterLength(CHARACTER_ARRAY)
    CHARACTER,INTENT(INOUT):: CHARACTER_ARRAY(:)*(*)
    END SUBROUTINE HeapsortCharacterLength

    ! 24. SVG_Square (subroutine)
    MODULE SUBROUTINE SVG_Square(OUTPUT_FILE,X,Y,SIDE, &
        & STROKE_WIDTH,FILL_OPACITY,STROKE_RGB,FILL_RGB, &
        & ROTATE,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X,Y,SIDE,STROKE_WIDTH,FILL_OPACITY
    INTEGER,INTENT(IN):: STROKE_RGB(3),FILL_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: ROTATE(3),SCALAR_VALUE(:)
    END SUBROUTINE SVG_Square

    ! 25. SVG_Line (subroutine)
    MODULE SUBROUTINE SVG_Line(OUTPUT_FILE,X,Y,STROKE_WIDTH,STROKE_RGB, &
        & ROTATE,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X(2),Y(2),STROKE_WIDTH
    INTEGER,INTENT(IN):: STROKE_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: ROTATE(3),SCALAR_VALUE(:)
    END SUBROUTINE SVG_Line

    ! 26. SVG_Circle (subroutine)
    MODULE SUBROUTINE SVG_Circle(OUTPUT_FILE,X,Y,RADIUS, &
        & STROKE_WIDTH,FILL_OPACITY,STROKE_RGB,FILL_RGB, &
        & ROTATE,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X,Y,RADIUS,STROKE_WIDTH,FILL_OPACITY
    INTEGER,INTENT(IN):: STROKE_RGB(3),FILL_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: ROTATE(3),SCALAR_VALUE(:)
    END SUBROUTINE SVG_Circle

    ! 27. SVG_Polyline (subroutine)
    MODULE SUBROUTINE SVG_Polyline(OUTPUT_FILE,X,Y, &
        & STROKE_WIDTH,FILL_OPACITY,STROKE_RGB,FILL_RGB, &
        & ROTATE,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X(:),Y(:),STROKE_WIDTH,FILL_OPACITY
    INTEGER,INTENT(IN):: STROKE_RGB(3),FILL_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: ROTATE(3),SCALAR_VALUE(:)
    END SUBROUTINE SVG_Polyline

    ! 28. SVG_GroupStart (subroutine)
    MODULE SUBROUTINE SVG_GroupStart(OUTPUT_FILE,ROTATE,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: ROTATE(3),SCALAR_VALUE(:)
    END SUBROUTINE SVG_GroupStart

    ! 29. SVG_GroupEnd (subroutine)
    MODULE SUBROUTINE SVG_GroupEnd(OUTPUT_FILE)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    END SUBROUTINE SVG_GroupEnd

    ! 30. SVG_Polygon (subroutine)
    MODULE SUBROUTINE SVG_Polygon(OUTPUT_FILE,X,Y, &
        & STROKE_WIDTH,FILL_OPACITY,STROKE_RGB,FILL_RGB, &
        & ROTATE,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X(:),Y(:),STROKE_WIDTH,FILL_OPACITY
    INTEGER,INTENT(IN):: STROKE_RGB(3),FILL_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: ROTATE(3),SCALAR_VALUE(:)
    END SUBROUTINE SVG_Polygon

    ! 31. SVG_Text (subroutine)
    MODULE SUBROUTINE SVG_Text(OUTPUT_FILE,STRING,X,Y, &
        & FONT,FONT_SIZE,FILL_OPACITY,FILL_RGB, &
        & BOLD,ITALIC,ANCHOR,ROTATE,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),STRING*(*),FONT*(*)
    REAL(SRK),INTENT(IN):: X,Y,FILL_OPACITY,FONT_SIZE
    INTEGER,INTENT(IN):: FILL_RGB(3)
    LOGICAL,OPTIONAL,INTENT(IN):: BOLD,ITALIC
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ANCHOR*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: ROTATE(3),SCALAR_VALUE(:)
    END SUBROUTINE SVG_Text

    ! 32. SVG_ActionButton (subroutine)
    MODULE SUBROUTINE SVG_ActionButton(OUTPUT_FILE,SCRIPT,TARGET_ID,X,Y,WIDTH,HEIGHT, &
        & STROKE_WIDTH,BUTTON_FILL_OPACITY,STROKE_RGB,BUTTON_FILL_RGB, &
        & STRING,FONT,FONT_SIZE,TEXT_FILL_OPACITY,TEXT_FILL_RGB)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),SCRIPT*(*),STRING*(*),FONT*(*)
    CHARACTER,INTENT(IN):: TARGET_ID*(*)
    REAL(SRK),INTENT(IN):: X,Y,WIDTH,HEIGHT,STROKE_WIDTH
    REAL(SRK),INTENT(IN):: BUTTON_FILL_OPACITY,TEXT_FILL_OPACITY,FONT_SIZE
    INTEGER,INTENT(IN):: STROKE_RGB(3),BUTTON_FILL_RGB(3),TEXT_FILL_RGB(3)
    END SUBROUTINE SVG_ActionButton

    ! 33. SVG_Vanish (subroutine)
    MODULE SUBROUTINE SVG_Vanish(OUTPUT_FILE)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    END SUBROUTINE SVG_Vanish

    ! 34. SVG_GroupSelect (subroutine)
    MODULE SUBROUTINE SVG_GroupSelect(OUTPUT_FILE,TARGET_IDS,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    CHARACTER,INTENT(IN):: TARGET_IDS(:)*(*)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: SCALAR_VALUE(:)
    END SUBROUTINE SVG_GroupSelect

    ! 35. SVG_BezierQuadratic (subroutine)
    MODULE SUBROUTINE SVG_BezierQuadratic(OUTPUT_FILE,X,Y, &
        & STROKE_WIDTH,FILL_OPACITY,STROKE_RGB,FILL_RGB, &
        & ROTATE,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X(:),Y(:),STROKE_WIDTH,FILL_OPACITY
    INTEGER,INTENT(IN):: STROKE_RGB(3),FILL_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: ROTATE(3),SCALAR_VALUE(:)
    END SUBROUTINE SVG_BezierQuadratic

    ! 36. SVG_GridStructured (subroutine)
    MODULE SUBROUTINE SVG_GridStructured(OUTPUT_FILE,X,Y, &
        & LINE_WIDTH,LINE_RGB,NODE_SIZE,NODE_RGB, &
        & CELL_PROPERTY,CELL_PROPERTY_NAME,CELL_COLOR_SCHEME, &
        & NODE_PROPERTY,NODE_PROPERTY_NAME,NODE_COLOR_SCHEME, &
        & ID_LINES,ID_CELLS,ID_NODES)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X(:,:),Y(:,:),LINE_WIDTH,NODE_SIZE
    INTEGER,INTENT(IN):: LINE_RGB(3),NODE_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: CELL_PROPERTY_NAME*(*),NODE_PROPERTY_NAME*(*)
    CHARACTER,OPTIONAL,INTENT(IN):: CELL_COLOR_SCHEME*(*),NODE_COLOR_SCHEME*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: CELL_PROPERTY(:,:),NODE_PROPERTY(:,:)
    CHARACTER,OPTIONAL,INTENT(IN):: ID_LINES*(*),ID_CELLS*(*),ID_NODES*(*)
    END SUBROUTINE SVG_GridStructured

    ! 37. SVG_ColorBar (subroutine)
    MODULE SUBROUTINE SVG_ColorBar(OUTPUT_FILE,TITLE,X,Y,WIDTH,HEIGHT,MINIMUM,MAXIMUM, &
        & DECIMAL_PLACES,SCIENTIFIC,FONT,FONT_SIZE,FONT_RGB,GRAYSCALE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),TITLE*(*),FONT*(*)
    REAL(SRK),INTENT(IN):: X,Y,WIDTH,HEIGHT,MINIMUM,MAXIMUM,FONT_SIZE
    INTEGER,INTENT(IN):: FONT_RGB(3),DECIMAL_PLACES
    LOGICAL,INTENT(IN):: SCIENTIFIC
    LOGICAL,OPTIONAL,INTENT(IN):: GRAYSCALE
    CHARACTER,OPTIONAL,INTENT(IN):: ID*(*)
    END SUBROUTINE SVG_ColorBar

    ! 38. SVG_Resurrect (subroutine)
    MODULE SUBROUTINE SVG_Resurrect(OUTPUT_FILE)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    END SUBROUTINE SVG_Resurrect

    ! 39. SVG_Triangle (subroutine)
    MODULE SUBROUTINE SVG_Triangle(OUTPUT_FILE,X,Y,SIDE, &
        & STROKE_WIDTH,FILL_OPACITY,STROKE_RGB,FILL_RGB, &
        & ROTATE,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X,Y,SIDE,STROKE_WIDTH,FILL_OPACITY
    INTEGER,INTENT(IN):: STROKE_RGB(3),FILL_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: ROTATE(3),SCALAR_VALUE(:)
    END SUBROUTINE SVG_Triangle

    ! 40. SVG_Cross (subroutine)
    MODULE SUBROUTINE SVG_Cross(OUTPUT_FILE,X,Y,SIDE,STROKE_WIDTH,STROKE_RGB, &
        & ROTATE,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X,Y,SIDE,STROKE_WIDTH
    INTEGER,INTENT(IN):: STROKE_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: ROTATE(3),SCALAR_VALUE(:)
    END SUBROUTINE SVG_Cross

    ! 41. SVG_Vector (subroutine)
    MODULE SUBROUTINE SVG_Vector(OUTPUT_FILE,X,Y,STROKE_WIDTH,STROKE_RGB,HEAD_SIZE, &
        & CHANGE_MARKER,ROTATE,SCALAR_NAME,SCALAR_VALUE,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X(2),Y(2),HEAD_SIZE,STROKE_WIDTH
    INTEGER,INTENT(IN):: STROKE_RGB(3)
    LOGICAL,OPTIONAL,INTENT(IN):: CHANGE_MARKER
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: ROTATE(3),SCALAR_VALUE(:)
    END SUBROUTINE SVG_Vector

    ! 42. FormatReal (function)
    MODULE FUNCTION FormatReal(NUMERICAL_VALUE,DECIMAL_PLACES,SCIENTIFIC)
    REAL(SRK),INTENT(IN):: NUMERICAL_VALUE
    INTEGER,INTENT(IN):: DECIMAL_PLACES
    LOGICAL,INTENT(IN):: SCIENTIFIC
    CHARACTER:: FormatReal*(DEFAULT_STRING_LENGTH)
    END FUNCTION FormatReal

    ! 43. SVG_VectorFieldStructured (subroutine)
    MODULE SUBROUTINE SVG_VectorFieldStructured(OUTPUT_FILE,X,Y, &
        & ARRAY1,ARRAY2,DATA_TYPE,HEAD_SIZE,STROKE_WIDTH,STROKE_RGB, &
        & PROPERTY_NAME,PROPERTY_VALUE,COLOR_SCHEME,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),DATA_TYPE*(*)
    REAL(SRK),INTENT(IN):: X(:,:),Y(:,:),ARRAY1(:,:),ARRAY2(:,:)
    REAL(SRK),INTENT(IN):: HEAD_SIZE,STROKE_WIDTH
    INTEGER,INTENT(IN):: STROKE_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: PROPERTY_NAME*(*),COLOR_SCHEME*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: PROPERTY_VALUE(:,:)
    END SUBROUTINE SVG_VectorFieldStructured

    ! 44. SVG_GridPixel (subroutine)
    MODULE SUBROUTINE SVG_GridPixel(OUTPUT_FILE,X,Y, &
        & RESOLUTION_X,RESOLUTION_Y,PIXEL_WIDTH,PIXEL_HEIGHT, &
        & LINE_WIDTH,LINE_RGB,NODE_SIZE,NODE_RGB, &
        & CELL_PROPERTY,CELL_PROPERTY_NAME,CELL_COLOR_SCHEME, &
        & NODE_PROPERTY,NODE_PROPERTY_NAME,NODE_COLOR_SCHEME, &
        & ID_CELLS,ID_NODES)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X,Y,PIXEL_WIDTH,PIXEL_HEIGHT,LINE_WIDTH,NODE_SIZE
    INTEGER,INTENT(IN):: RESOLUTION_X,RESOLUTION_Y,LINE_RGB(3),NODE_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: CELL_PROPERTY_NAME*(*),NODE_PROPERTY_NAME*(*)
    CHARACTER,OPTIONAL,INTENT(IN):: CELL_COLOR_SCHEME*(*),NODE_COLOR_SCHEME*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: CELL_PROPERTY(:,:),NODE_PROPERTY(:,:)
    CHARACTER,OPTIONAL,INTENT(IN):: ID_CELLS*(*),ID_NODES*(*)
    END SUBROUTINE SVG_GridPixel

    ! 45. SVG_VectorFieldPixel (subroutine)
    MODULE SUBROUTINE SVG_VectorFieldPixel(OUTPUT_FILE,X,Y, &
        & RESOLUTION_X,RESOLUTION_Y,PIXEL_WIDTH,PIXEL_HEIGHT, &
        & ARRAY1,ARRAY2,DATA_TYPE,HEAD_SIZE,STROKE_WIDTH,STROKE_RGB, &
        & PROPERTY_NAME,PROPERTY_VALUE,COLOR_SCHEME,ID)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),DATA_TYPE*(*)
    REAL(SRK),INTENT(IN):: X,Y,ARRAY1(:,:),ARRAY2(:,:),PIXEL_WIDTH,PIXEL_HEIGHT
    REAL(SRK),INTENT(IN):: HEAD_SIZE,STROKE_WIDTH
    INTEGER,INTENT(IN):: RESOLUTION_X,RESOLUTION_Y,STROKE_RGB(3)
    CHARACTER,OPTIONAL,INTENT(IN):: PROPERTY_NAME*(*),COLOR_SCHEME*(*),ID*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: PROPERTY_VALUE(:,:)
    END SUBROUTINE SVG_VectorFieldPixel

    ! 46. EQP_InequalityParser (function)
    MODULE FUNCTION EQP_InequalityParser(INEQUALITY,VARIABLE_NAMES,VARIABLE_VALUES, &
        & TOLERANCE)
    CHARACTER,INTENT(IN):: INEQUALITY*(*)
    CHARACTER,POINTER:: VARIABLE_NAMES(:)*(*)
    REAL(SRK),POINTER:: VARIABLE_VALUES(:)
    REAL(SRK),OPTIONAL:: TOLERANCE
    LOGICAL:: EQP_InequalityParser
    END FUNCTION EQP_InequalityParser

    ! 47. ArrayExpandCharacter (subroutine)
    MODULE SUBROUTINE ArrayExpandCharacter(ARRAY_POINTER,SCALAR_VALUE)
    CHARACTER,INTENT(IN):: SCALAR_VALUE*(*)
    CHARACTER,POINTER:: ARRAY_POINTER(:)*(*)
    END SUBROUTINE ArrayExpandCharacter

    ! 48. CrossPoint (subroutine)
    MODULE SUBROUTINE CrossPoint(X1,X2,Y1,Y2,XM,YM)
    REAL(SRK),INTENT(IN):: X1(2),X2(2),Y1(2),Y2(2)
    REAL(SRK),INTENT(OUT):: XM,YM
    END SUBROUTINE CrossPoint

    ! 49. SVG_TernaryPlot (subroutine)
    MODULE SUBROUTINE SVG_TernaryPlot(OUTPUT_FILE, &
        & A_POINTS,B_POINTS,C_POINTS,A_TITLE,B_TITLE,C_TITLE, &
        & DIAGRAM_TITLE,DATA_TITLE,TITLE_DIAGRAM_FONT_SIZE, &
        & TITLE_AXIS_FONT_SIZE,NUMBERS_AXIS_FONT_SIZE, &
        & FONT_RGB,AXIS_STROKE_RGB,AXIS_STROKE_WIDTH, &
        & DRAW_TICKS,TICK_LENGTH,TICK_WIDTH, &
        & DRAW_GRID,GRID_STROKE_WIDTH,GRID_STROKE_RGB, &
        & SHAPE_TYPE,SHAPE_SIZE,SHAPE_STROKE_WIDTH, &
        & SHAPE_FILL_RGB,SHAPE_STROKE_RGB, &
        & LINE_TYPE,LINE_STROKE_WIDTH,LINE_STROKE_RGB)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),SHAPE_TYPE*(*),LINE_TYPE*(*)
    CHARACTER,INTENT(IN):: DIAGRAM_TITLE*(*),A_TITLE*(*),B_TITLE*(*),C_TITLE*(*)
    CHARACTER,INTENT(IN):: DATA_TITLE*(*)
    REAL(SRK),INTENT(IN):: A_POINTS(:),B_POINTS(:),C_POINTS(:)
    REAL(SRK),INTENT(IN):: AXIS_STROKE_WIDTH,GRID_STROKE_WIDTH
    REAL(SRK),INTENT(IN):: SHAPE_SIZE,SHAPE_STROKE_WIDTH,LINE_STROKE_WIDTH
    REAL(SRK),INTENT(IN):: TITLE_AXIS_FONT_SIZE,NUMBERS_AXIS_FONT_SIZE
    REAL(SRK),INTENT(IN):: TITLE_DIAGRAM_FONT_SIZE
    REAL(SRK),INTENT(IN):: TICK_LENGTH,TICK_WIDTH
    INTEGER,INTENT(IN):: AXIS_STROKE_RGB(3),GRID_STROKE_RGB(3),FONT_RGB(3)
    INTEGER,INTENT(IN):: SHAPE_FILL_RGB(3),SHAPE_STROKE_RGB(3),LINE_STROKE_RGB(3)
    LOGICAL,INTENT(IN):: DRAW_TICKS,DRAW_GRID
    END SUBROUTINE SVG_TernaryPlot

    ! 50. HTML_Initialize (subroutine)
    MODULE SUBROUTINE HTML_Initialize(OUTPUT_FILE)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    END SUBROUTINE HTML_Initialize

    ! 51. HTML_Finalize (subroutine)
    MODULE SUBROUTINE HTML_Finalize(OUTPUT_FILE)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    END SUBROUTINE HTML_Finalize

    ! 52. HTML_Table (subroutine)
    MODULE SUBROUTINE HTML_Table(OUTPUT_FILE,NUMBERS,HEADINGS,DECIMAL_PLACES,SCIENTIFIC)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),HEADINGS(:)*(*)
    REAL(SRK),INTENT(IN):: NUMBERS(:,:)
    INTEGER,INTENT(IN):: DECIMAL_PLACES(:)
    LOGICAL,INTENT(IN):: SCIENTIFIC(:)
    END SUBROUTINE HTML_Table

    ! 53. SVG_Link (subroutine)
    MODULE SUBROUTINE SVG_Link(OUTPUT_FILE,TARGET_IDS,LINK_STRING)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),TARGET_IDS(:)*(*),LINK_STRING*(*)
    END SUBROUTINE SVG_Link

    ! 54. SVG_LinkButton (subroutine)
    MODULE SUBROUTINE SVG_LinkButton(OUTPUT_FILE,LINK_STRING,X,Y,WIDTH,HEIGHT, &
        & STROKE_WIDTH,BUTTON_FILL_OPACITY,STROKE_RGB,BUTTON_FILL_RGB, &
        & STRING,FONT,FONT_SIZE,TEXT_FILL_OPACITY,TEXT_FILL_RGB)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),LINK_STRING*(*),STRING*(*),FONT*(*)
    REAL(SRK),INTENT(IN):: X,Y,WIDTH,HEIGHT,STROKE_WIDTH
    REAL(SRK),INTENT(IN):: BUTTON_FILL_OPACITY,TEXT_FILL_OPACITY,FONT_SIZE
    INTEGER,INTENT(IN):: STROKE_RGB(3),BUTTON_FILL_RGB(3),TEXT_FILL_RGB(3)
    END SUBROUTINE SVG_LinkButton

    ! 55. HTML_Heading (subroutine)
    MODULE SUBROUTINE HTML_Heading(OUTPUT_FILE,STRING,LEVEL)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),STRING*(*)
    INTEGER,INTENT(IN):: LEVEL
    END SUBROUTINE HTML_Heading

    ! 56. HTML_Paragraph (subroutine)
    MODULE SUBROUTINE HTML_Paragraph(OUTPUT_FILE,TEXT)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),TEXT*(*)
    END SUBROUTINE HTML_Paragraph

    ! 57. HTML_Link (subroutine)
    MODULE SUBROUTINE HTML_Link(OUTPUT_FILE,TEXT,LINK_STRING)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),TEXT*(*),LINK_STRING*(*)
    END SUBROUTINE HTML_Link

    ! 58. SVG_CartesianPlot (subroutine)
    MODULE SUBROUTINE SVG_CartesianPlot(OUTPUT_FILE, &
        & X_POINTS,Y_POINTS,X_TITLE,Y_TITLE, &
        & X_START,X_END,Y_START,Y_END, &
        & X_DECIMAL_PLACES,Y_DECIMAL_PLACES,SCIENTIFIC_X,SCIENTIFIC_Y, &
        & X_TICK_INTERVAL,Y_TICK_INTERVAL, &
        & DRAW_TICKS,TICK_LENGTH,TICK_WIDTH, &
        & DIAGRAM_TITLE,DATA_TITLE,TITLE_DIAGRAM_FONT_SIZE, &
        & TITLE_AXIS_FONT_SIZE,NUMBERS_AXIS_FONT_SIZE, &
        & FONT_RGB,AXIS_STROKE_RGB,AXIS_STROKE_WIDTH, &
        & DRAW_GRID,GRID_STROKE_WIDTH,GRID_STROKE_RGB, &
        & SHAPE_TYPE,SHAPE_SIZE,SHAPE_STROKE_WIDTH, &
        & SHAPE_FILL_RGB,SHAPE_STROKE_RGB, &
        & LINE_TYPE,LINE_STROKE_WIDTH,LINE_STROKE_RGB)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),SHAPE_TYPE*(*),LINE_TYPE*(*)
    CHARACTER,INTENT(IN):: DIAGRAM_TITLE*(*),X_TITLE*(*),Y_TITLE*(*)
    CHARACTER,INTENT(IN):: DATA_TITLE*(*)
    REAL(SRK),INTENT(IN):: X_POINTS(:),Y_POINTS(:),X_START,X_END,Y_START,Y_END
    REAL(SRK),INTENT(IN):: X_TICK_INTERVAL,Y_TICK_INTERVAL,TICK_LENGTH,TICK_WIDTH
    REAL(SRK),INTENT(IN):: AXIS_STROKE_WIDTH,GRID_STROKE_WIDTH
    REAL(SRK),INTENT(IN):: SHAPE_SIZE,SHAPE_STROKE_WIDTH,LINE_STROKE_WIDTH
    REAL(SRK),INTENT(IN):: TITLE_AXIS_FONT_SIZE,NUMBERS_AXIS_FONT_SIZE
    REAL(SRK),INTENT(IN):: TITLE_DIAGRAM_FONT_SIZE
    INTEGER,INTENT(IN):: X_DECIMAL_PLACES,Y_DECIMAL_PLACES
    INTEGER,INTENT(IN):: AXIS_STROKE_RGB(3),GRID_STROKE_RGB(3),FONT_RGB(3)
    INTEGER,INTENT(IN):: SHAPE_FILL_RGB(3),SHAPE_STROKE_RGB(3),LINE_STROKE_RGB(3)
    LOGICAL,INTENT(IN):: DRAW_TICKS,DRAW_GRID,SCIENTIFIC_X,SCIENTIFIC_Y
    END SUBROUTINE SVG_CartesianPlot

    ! 59. AxesSetup (subroutine)
    MODULE SUBROUTINE AxesSetup(LOWER,UPPER, &
        & STARTS,STOPS,INTERVAL,DECIMAL_PLACES,SCIENTIFIC)
    REAL(SRK),INTENT(IN):: LOWER,UPPER
    REAL(SRK),INTENT(OUT):: STARTS,STOPS,INTERVAL
    INTEGER,INTENT(OUT):: DECIMAL_PLACES
    LOGICAL,INTENT(OUT):: SCIENTIFIC
    END SUBROUTINE AxesSetup

    ! 60. SVG_CartesianPlotDefault (subroutine)
    MODULE SUBROUTINE SVG_CartesianPlotDefault(OUTPUT_FILE,X_POINTS,Y_POINTS, &
        & X_TITLE,Y_TITLE,DIAGRAM_TITLE,DATA_TITLE,SHAPE_TYPE,SHAPE_SIZE, &
        & SHAPE_STROKE_WIDTH,SHAPE_FILL_RGB,SHAPE_STROKE_RGB, &
        & LINE_TYPE,LINE_STROKE_WIDTH,LINE_STROKE_RGB)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*),SHAPE_TYPE*(*),LINE_TYPE*(*)
    CHARACTER,INTENT(IN):: DIAGRAM_TITLE*(*),X_TITLE*(*),Y_TITLE*(*),DATA_TITLE*(*)
    REAL(SRK),INTENT(IN):: X_POINTS(:),Y_POINTS(:)
    REAL(SRK),INTENT(IN):: SHAPE_SIZE,SHAPE_STROKE_WIDTH,LINE_STROKE_WIDTH
    INTEGER,INTENT(IN):: SHAPE_FILL_RGB(3),SHAPE_STROKE_RGB(3),LINE_STROKE_RGB(3)
    END SUBROUTINE SVG_CartesianPlotDefault

    ! 61. VTK_Initialize (subroutine)
    MODULE SUBROUTINE VTK_Initialize(OUTPUT_FILE)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    END SUBROUTINE VTK_Initialize

    ! 62. VTK_Finalize (subroutine)
    MODULE SUBROUTINE VTK_Finalize(OUTPUT_FILE)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    END SUBROUTINE VTK_Finalize

    ! 63. VTK_Sphere (subroutine)
    MODULE SUBROUTINE VTK_Sphere(OUTPUT_FILE,CENTER,DIAMETER,RADIAL_RES,AXIAL_RES)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: CENTER(3),DIAMETER
    INTEGER,INTENT(IN):: RADIAL_RES,AXIAL_RES
    END SUBROUTINE VTK_Sphere

    ! 64. VTK_Path (subroutine)
    MODULE SUBROUTINE VTK_Path(OUTPUT_FILE,POINTS,SCALAR_NAME,SCALAR_VALUE)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: POINTS(:,:)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: SCALAR_VALUE(:,:)
    END SUBROUTINE VTK_Path

    ! 65. VTK_Surface (subroutine)
    MODULE SUBROUTINE VTK_Surface(OUTPUT_FILE,X,Y,Z,SCALAR_NAME,SCALAR_VALUE)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X(:,:),Y(:,:),Z(:,:)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: SCALAR_VALUE(:,:,:)
    END SUBROUTINE VTK_Surface

    ! 66. VTK_VectorField (subroutine)
    MODULE SUBROUTINE VTK_VectorField(OUTPUT_FILE,X,Y,Z,VX,VY,VZ,SCALAR_NAME,SCALAR_VALUE)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X(:,:),Y(:,:),Z(:,:),VX(:,:),VY(:,:),VZ(:,:)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: SCALAR_VALUE(:,:,:)
    END SUBROUTINE VTK_VectorField

    ! 67. VTK_MultiLine (subroutine)
    MODULE SUBROUTINE VTK_MultiLine(OUTPUT_FILE,X1,Y1,Z1,X2,Y2,Z2, &
        & SCALAR_NAME,SCALAR_VALUE)
    CHARACTER,INTENT(IN):: OUTPUT_FILE*(*)
    REAL(SRK),INTENT(IN):: X1(:,:),Y1(:,:),Z1(:,:),X2(:,:),Y2(:,:),Z2(:,:)
    CHARACTER,OPTIONAL,INTENT(IN):: SCALAR_NAME(:)*(*)
    REAL(SRK),OPTIONAL,INTENT(IN):: SCALAR_VALUE(:,:,:)
    END SUBROUTINE VTK_MultiLine

END INTERFACE

! ------------------------------------------------------------------------------

END MODULE ModLib_FENIA

! ------------------------------------------------------------------------------
! ------------------------------------------------------------------------------

